// 함수 설명 (자동 완성 · 함수 삽입 대화상자)
export const CATEGORIES = ['수학/삼각', '통계', '논리', '텍스트', '찾기/참조', '날짜/시간', '정보', '재무', '공학', '데이터베이스', '호환성', '웹', '구글 스프레드시트'];

const F = (cat, sig, desc) => ({ cat, sig, desc });

export const FUNC_INFO = {
  SUM: F('수학/삼각', 'SUM(number1, [number2], ...)', '인수들의 합을 구합니다.'),
  PRODUCT: F('수학/삼각', 'PRODUCT(number1, [number2], ...)', '인수들의 곱을 구합니다.'),
  SUMPRODUCT: F('수학/삼각', 'SUMPRODUCT(array1, [array2], ...)', '배열의 대응 요소를 곱한 뒤 합을 구합니다.'),
  SUMIF: F('수학/삼각', 'SUMIF(range, criteria, [sum_range])', '조건에 맞는 셀의 합을 구합니다.'),
  SUMIFS: F('수학/삼각', 'SUMIFS(sum_range, criteria_range1, criteria1, ...)', '여러 조건에 맞는 셀의 합을 구합니다.'),
  ROUND: F('수학/삼각', 'ROUND(number, num_digits)', '수를 지정한 자릿수로 반올림합니다.'),
  ROUNDUP: F('수학/삼각', 'ROUNDUP(number, num_digits)', '수를 지정한 자릿수로 올림합니다.'),
  ROUNDDOWN: F('수학/삼각', 'ROUNDDOWN(number, num_digits)', '수를 지정한 자릿수로 내림합니다.'),
  TRUNC: F('수학/삼각', 'TRUNC(number, [num_digits])', '수의 소수점 이하를 버립니다.'),
  INT: F('수학/삼각', 'INT(number)', '가장 가까운 정수로 내림합니다.'),
  ABS: F('수학/삼각', 'ABS(number)', '절대값을 구합니다.'),
  SIGN: F('수학/삼각', 'SIGN(number)', '수의 부호를 구합니다.'),
  MOD: F('수학/삼각', 'MOD(number, divisor)', '나눗셈의 나머지를 구합니다.'),
  POWER: F('수학/삼각', 'POWER(number, power)', '거듭제곱을 구합니다.'),
  SQRT: F('수학/삼각', 'SQRT(number)', '양의 제곱근을 구합니다.'),
  EXP: F('수학/삼각', 'EXP(number)', 'e를 number만큼 거듭제곱합니다.'),
  LN: F('수학/삼각', 'LN(number)', '자연 로그를 구합니다.'),
  LOG: F('수학/삼각', 'LOG(number, [base])', '지정한 밑의 로그를 구합니다.'),
  LOG10: F('수학/삼각', 'LOG10(number)', '밑이 10인 로그를 구합니다.'),
  PI: F('수학/삼각', 'PI()', '원주율 값을 반환합니다.'),
  RAND: F('수학/삼각', 'RAND()', '0 이상 1 미만의 난수를 반환합니다.'),
  RANDBETWEEN: F('수학/삼각', 'RANDBETWEEN(bottom, top)', '두 수 사이의 정수 난수를 반환합니다.'),

  SUBTOTAL: F('수학/삼각', 'SUBTOTAL(function_num, ref1, ...)', '목록의 부분합을 구합니다. 101~111은 숨긴 행을 제외합니다 (109 = 합계).'),
  AVERAGE: F('통계', 'AVERAGE(number1, [number2], ...)', '인수들의 평균을 구합니다.'),
  STDEV: F('통계', 'STDEV(number1, [number2], ...)', '표본의 표준 편차를 구합니다.'),
  'STDEV.S': F('통계', 'STDEV.S(number1, [number2], ...)', '표본의 표준 편차를 구합니다.'),
  STDEVP: F('통계', 'STDEVP(number1, [number2], ...)', '모집단의 표준 편차를 구합니다.'),
  'STDEV.P': F('통계', 'STDEV.P(number1, [number2], ...)', '모집단의 표준 편차를 구합니다.'),
  VAR: F('통계', 'VAR(number1, [number2], ...)', '표본의 분산을 구합니다.'),
  'VAR.S': F('통계', 'VAR.S(number1, [number2], ...)', '표본의 분산을 구합니다.'),
  VARP: F('통계', 'VARP(number1, [number2], ...)', '모집단의 분산을 구합니다.'),
  'VAR.P': F('통계', 'VAR.P(number1, [number2], ...)', '모집단의 분산을 구합니다.'),
  AVERAGEIF: F('통계', 'AVERAGEIF(range, criteria, [average_range])', '조건에 맞는 셀의 평균을 구합니다.'),
  COUNT: F('통계', 'COUNT(value1, [value2], ...)', '숫자가 포함된 셀의 개수를 셉니다.'),
  COUNTA: F('통계', 'COUNTA(value1, [value2], ...)', '비어 있지 않은 셀의 개수를 셉니다.'),
  COUNTBLANK: F('통계', 'COUNTBLANK(range)', '빈 셀의 개수를 셉니다.'),
  COUNTIF: F('통계', 'COUNTIF(range, criteria)', '조건에 맞는 셀의 개수를 셉니다.'),
  COUNTIFS: F('통계', 'COUNTIFS(criteria_range1, criteria1, ...)', '여러 조건에 맞는 셀의 개수를 셉니다.'),
  MAX: F('통계', 'MAX(number1, [number2], ...)', '최대값을 구합니다.'),
  MIN: F('통계', 'MIN(number1, [number2], ...)', '최소값을 구합니다.'),
  MEDIAN: F('통계', 'MEDIAN(number1, [number2], ...)', '중간값을 구합니다.'),

  IF: F('논리', 'IF(logical_test, [value_if_true], [value_if_false])', '조건이 참이면 한 값을, 거짓이면 다른 값을 반환합니다.'),
  IFS: F('논리', 'IFS(logical_test1, value1, ...)', '첫 번째로 참인 조건의 값을 반환합니다.'),
  IFERROR: F('논리', 'IFERROR(value, value_if_error)', '오류이면 지정한 값을, 아니면 수식 결과를 반환합니다.'),
  IFNA: F('논리', 'IFNA(value, value_if_na)', '#N/A 오류이면 지정한 값을 반환합니다.'),
  AND: F('논리', 'AND(logical1, [logical2], ...)', '모든 인수가 참이면 TRUE를 반환합니다.'),
  OR: F('논리', 'OR(logical1, [logical2], ...)', '하나 이상의 인수가 참이면 TRUE를 반환합니다.'),
  NOT: F('논리', 'NOT(logical)', '논리값을 반대로 바꿉니다.'),
  TRUE: F('논리', 'TRUE()', '논리값 TRUE를 반환합니다.'),
  FALSE: F('논리', 'FALSE()', '논리값 FALSE를 반환합니다.'),
  CHOOSE: F('논리', 'CHOOSE(index_num, value1, [value2], ...)', '목록에서 index_num 번째 값을 고릅니다.'),

  CONCATENATE: F('텍스트', 'CONCATENATE(text1, [text2], ...)', '여러 텍스트를 하나로 연결합니다.'),
  CONCAT: F('텍스트', 'CONCAT(text1, [text2], ...)', '범위를 포함한 텍스트를 연결합니다.'),
  TEXTJOIN: F('텍스트', 'TEXTJOIN(delimiter, ignore_empty, text1, ...)', '구분 기호를 넣어 텍스트를 연결합니다.'),
  LEN: F('텍스트', 'LEN(text)', '텍스트의 문자 수를 구합니다.'),
  LEFT: F('텍스트', 'LEFT(text, [num_chars])', '텍스트의 왼쪽부터 문자를 반환합니다.'),
  RIGHT: F('텍스트', 'RIGHT(text, [num_chars])', '텍스트의 오른쪽부터 문자를 반환합니다.'),
  MID: F('텍스트', 'MID(text, start_num, num_chars)', '텍스트의 중간에서 문자를 반환합니다.'),
  UPPER: F('텍스트', 'UPPER(text)', '대문자로 바꿉니다.'),
  LOWER: F('텍스트', 'LOWER(text)', '소문자로 바꿉니다.'),
  PROPER: F('텍스트', 'PROPER(text)', '각 단어의 첫 글자를 대문자로 바꿉니다.'),
  TRIM: F('텍스트', 'TRIM(text)', '불필요한 공백을 제거합니다.'),
  REPT: F('텍스트', 'REPT(text, number_times)', '텍스트를 지정한 횟수만큼 반복합니다.'),
  SUBSTITUTE: F('텍스트', 'SUBSTITUTE(text, old_text, new_text, [instance_num])', '텍스트의 일부를 바꿉니다.'),
  FIND: F('텍스트', 'FIND(find_text, within_text, [start_num])', '텍스트의 위치를 찾습니다(대/소문자 구분).'),
  SEARCH: F('텍스트', 'SEARCH(find_text, within_text, [start_num])', '텍스트의 위치를 찾습니다(와일드카드 사용 가능).'),
  EXACT: F('텍스트', 'EXACT(text1, text2)', '두 텍스트가 정확히 같은지 확인합니다.'),
  VALUE: F('텍스트', 'VALUE(text)', '텍스트를 숫자로 바꿉니다.'),
  TEXT: F('텍스트', 'TEXT(value, format_text)', '숫자에 서식을 지정하여 텍스트로 바꿉니다.'),

  VLOOKUP: F('찾기/참조', 'VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])', '표의 첫 열에서 값을 찾아 같은 행의 값을 반환합니다.'),
  HLOOKUP: F('찾기/참조', 'HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])', '표의 첫 행에서 값을 찾아 같은 열의 값을 반환합니다.'),
  XLOOKUP: F('찾기/참조', 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])', '범위에서 값을 찾아 대응하는 항목을 반환합니다. match_mode: 0 정확, -1 작거나 같음, 1 크거나 같음, 2 와일드카드, 3 정규식.'),
  REGEXVLOOKUP: F('찾기/참조', 'REGEXVLOOKUP(pattern, table_array, col_index_num, [case_sensitivity])', '표의 첫 열에서 정규식과 일치하는 첫 행을 찾아 같은 행의 값을 반환합니다 (위셀 확장, case_sensitivity 1 = 대소문자 무시).'),
  REGEXHLOOKUP: F('찾기/참조', 'REGEXHLOOKUP(pattern, table_array, row_index_num, [case_sensitivity])', '표의 첫 행에서 정규식과 일치하는 첫 열을 찾아 같은 열의 값을 반환합니다 (위셀 확장).'),
  REGEXMATCHPOS: F('찾기/참조', 'REGEXMATCHPOS(pattern, lookup_array, [case_sensitivity])', '정규식과 일치하는 첫 항목의 상대 위치를 반환합니다 — INDEX 와 함께 쓰는 MATCH 의 정규식판 (위셀 확장).'),
  INDEX: F('찾기/참조', 'INDEX(array, row_num, [column_num])', '범위에서 지정한 위치의 값을 반환합니다.'),
  MATCH: F('찾기/참조', 'MATCH(lookup_value, lookup_array, [match_type])', '범위에서 값의 상대 위치를 반환합니다.'),
  ROWS: F('찾기/참조', 'ROWS(array)', '범위의 행 수를 반환합니다.'),
  COLUMNS: F('찾기/참조', 'COLUMNS(array)', '범위의 열 수를 반환합니다.'),

  TODAY: F('날짜/시간', 'TODAY()', '오늘 날짜를 반환합니다.'),
  NOW: F('날짜/시간', 'NOW()', '현재 날짜와 시간을 반환합니다.'),
  DATE: F('날짜/시간', 'DATE(year, month, day)', '날짜 일련 번호를 반환합니다.'),
  YEAR: F('날짜/시간', 'YEAR(serial_number)', '연도를 반환합니다.'),
  MONTH: F('날짜/시간', 'MONTH(serial_number)', '월을 반환합니다.'),
  DAY: F('날짜/시간', 'DAY(serial_number)', '일을 반환합니다.'),
  HOUR: F('날짜/시간', 'HOUR(serial_number)', '시를 반환합니다.'),
  MINUTE: F('날짜/시간', 'MINUTE(serial_number)', '분을 반환합니다.'),
  SECOND: F('날짜/시간', 'SECOND(serial_number)', '초를 반환합니다.'),
  WEEKDAY: F('날짜/시간', 'WEEKDAY(serial_number, [return_type])', '요일 번호를 반환합니다.'),

  ISBLANK: F('정보', 'ISBLANK(value)', '빈 셀이면 TRUE를 반환합니다.'),
  ISNUMBER: F('정보', 'ISNUMBER(value)', '숫자이면 TRUE를 반환합니다.'),
  ISTEXT: F('정보', 'ISTEXT(value)', '텍스트이면 TRUE를 반환합니다.'),
  ISLOGICAL: F('정보', 'ISLOGICAL(value)', '논리값이면 TRUE를 반환합니다.'),
  ISERROR: F('정보', 'ISERROR(value)', '오류 값이면 TRUE를 반환합니다.'),
  ISERR: F('정보', 'ISERR(value)', '#N/A를 제외한 오류이면 TRUE를 반환합니다.'),
  ISNA: F('정보', 'ISNA(value)', '#N/A 오류이면 TRUE를 반환합니다.'),
  NA: F('정보', 'NA()', '#N/A 오류 값을 반환합니다.'),

  // 확장 함수
  'ACOS': F('수학/삼각', 'ACOS(number)', '아크코사인 값을 구합니다.'),
  'ACOSH': F('수학/삼각', 'ACOSH(number)', '역 쌍곡 코사인 값을 구합니다.'),
  'ACOT': F('수학/삼각', 'ACOT(number)', '아크코탄젠트 값을 구합니다.'),
  'ACOTH': F('수학/삼각', 'ACOTH(number)', '역 쌍곡 코탄젠트 값을 구합니다.'),
  'ASIN': F('수학/삼각', 'ASIN(number)', '아크사인 값을 구합니다.'),
  'ASINH': F('수학/삼각', 'ASINH(number)', '역 쌍곡 사인 값을 구합니다.'),
  'ATAN': F('수학/삼각', 'ATAN(number)', '아크탄젠트 값을 구합니다.'),
  'ATAN2': F('수학/삼각', 'ATAN2(x_num, y_num)', 'x, y 좌표의 아크탄젠트 값을 구합니다.'),
  'ATANH': F('수학/삼각', 'ATANH(number)', '역 쌍곡 탄젠트 값을 구합니다.'),
  'COS': F('수학/삼각', 'COS(number)', '코사인 값을 구합니다.'),
  'COSH': F('수학/삼각', 'COSH(number)', '쌍곡 코사인 값을 구합니다.'),
  'COT': F('수학/삼각', 'COT(number)', '코탄젠트 값을 구합니다.'),
  'COTH': F('수학/삼각', 'COTH(number)', '쌍곡 코탄젠트 값을 구합니다.'),
  'CSC': F('수학/삼각', 'CSC(number)', '코시컨트 값을 구합니다.'),
  'CSCH': F('수학/삼각', 'CSCH(number)', '쌍곡 코시컨트 값을 구합니다.'),
  'SEC': F('수학/삼각', 'SEC(number)', '시컨트 값을 구합니다.'),
  'SECH': F('수학/삼각', 'SECH(number)', '쌍곡 시컨트 값을 구합니다.'),
  'SIN': F('수학/삼각', 'SIN(number)', '사인 값을 구합니다.'),
  'SINH': F('수학/삼각', 'SINH(number)', '쌍곡 사인 값을 구합니다.'),
  'TAN': F('수학/삼각', 'TAN(number)', '탄젠트 값을 구합니다.'),
  'TANH': F('수학/삼각', 'TANH(number)', '쌍곡 탄젠트 값을 구합니다.'),
  'DEGREES': F('수학/삼각', 'DEGREES(angle)', '라디안을 도로 바꿉니다.'),
  'RADIANS': F('수학/삼각', 'RADIANS(angle)', '도를 라디안으로 바꿉니다.'),
  'ARABIC': F('수학/삼각', 'ARABIC(text)', '로마 숫자를 아라비아 숫자로 바꿉니다.'),
  'ROMAN': F('수학/삼각', 'ROMAN(number, [form])', '아라비아 숫자를 로마 숫자 텍스트로 바꿉니다.'),
  'BASE': F('수학/삼각', 'BASE(number, radix, [min_length])', '수를 지정한 진법의 텍스트로 바꿉니다.'),
  'DECIMAL': F('수학/삼각', 'DECIMAL(text, radix)', '지정한 진법의 텍스트를 10진수로 바꿉니다.'),
  'CEILING': F('수학/삼각', 'CEILING(number, significance)', '수를 기준 배수로 올림합니다.'),
  'CEILING.MATH': F('수학/삼각', 'CEILING.MATH(number, [significance], [mode])', '수를 가장 가까운 정수 또는 배수로 올림합니다.'),
  'CEILING.PRECISE': F('수학/삼각', 'CEILING.PRECISE(number, [significance])', '부호와 관계없이 배수로 올림합니다.'),
  'ISO.CEILING': F('수학/삼각', 'ISO.CEILING(number, [significance])', '부호와 관계없이 배수로 올림합니다.'),
  'FLOOR': F('수학/삼각', 'FLOOR(number, significance)', '수를 기준 배수로 내림합니다.'),
  'FLOOR.MATH': F('수학/삼각', 'FLOOR.MATH(number, [significance], [mode])', '수를 가장 가까운 정수 또는 배수로 내림합니다.'),
  'FLOOR.PRECISE': F('수학/삼각', 'FLOOR.PRECISE(number, [significance])', '부호와 관계없이 배수로 내림합니다.'),
  'MROUND': F('수학/삼각', 'MROUND(number, multiple)', '수를 지정한 배수로 반올림합니다.'),
  'EVEN': F('수학/삼각', 'EVEN(number)', '가장 가까운 짝수로 올림합니다.'),
  'ODD': F('수학/삼각', 'ODD(number)', '가장 가까운 홀수로 올림합니다.'),
  'FACT': F('수학/삼각', 'FACT(number)', '계승 값을 구합니다.'),
  'FACTDOUBLE': F('수학/삼각', 'FACTDOUBLE(number)', '이중 계승 값을 구합니다.'),
  'COMBIN': F('수학/삼각', 'COMBIN(number, number_chosen)', '조합의 수를 구합니다.'),
  'COMBINA': F('수학/삼각', 'COMBINA(number, number_chosen)', '중복 조합의 수를 구합니다.'),
  'PERMUT': F('통계', 'PERMUT(number, number_chosen)', '순열의 수를 구합니다.'),
  'PERMUTATIONA': F('통계', 'PERMUTATIONA(number, number_chosen)', '중복 순열의 수를 구합니다.'),
  'GCD': F('수학/삼각', 'GCD(number1, [number2], ...)', '최대 공약수를 구합니다.'),
  'LCM': F('수학/삼각', 'LCM(number1, [number2], ...)', '최소 공배수를 구합니다.'),
  'MULTINOMIAL': F('수학/삼각', 'MULTINOMIAL(number1, [number2], ...)', '다항 계수를 구합니다.'),
  'QUOTIENT': F('수학/삼각', 'QUOTIENT(numerator, denominator)', '나눗셈 몫의 정수 부분을 구합니다.'),
  'SQRTPI': F('수학/삼각', 'SQRTPI(number)', '(number * π)의 제곱근을 구합니다.'),
  'SUMSQ': F('수학/삼각', 'SUMSQ(number1, [number2], ...)', '인수의 제곱의 합을 구합니다.'),
  'SUMX2MY2': F('수학/삼각', 'SUMX2MY2(array_x, array_y)', '두 배열의 대응 값 제곱의 차의 합을 구합니다.'),
  'SUMX2PY2': F('수학/삼각', 'SUMX2PY2(array_x, array_y)', '두 배열의 대응 값 제곱의 합의 합을 구합니다.'),
  'SUMXMY2': F('수학/삼각', 'SUMXMY2(array_x, array_y)', '두 배열의 대응 값 차의 제곱의 합을 구합니다.'),
  'SERIESSUM': F('수학/삼각', 'SERIESSUM(x, n, m, coefficients)', '멱급수의 합을 구합니다.'),
  'MMULT': F('수학/삼각', 'MMULT(array1, array2)', '두 배열의 행렬 곱을 구합니다.'),
  'MDETERM': F('수학/삼각', 'MDETERM(array)', '행렬식을 구합니다.'),
  'MINVERSE': F('수학/삼각', 'MINVERSE(array)', '역행렬을 구합니다.'),
  'MUNIT': F('수학/삼각', 'MUNIT(dimension)', '단위 행렬을 반환합니다.'),
  'RANDARRAY': F('수학/삼각', 'RANDARRAY([rows], [columns], [min], [max], [whole_number])', '난수 배열을 반환합니다.'),
  'SEQUENCE': F('수학/삼각', 'SEQUENCE(rows, [columns], [start], [step])', '연속된 숫자 배열을 만듭니다.'),
  'AGGREGATE': F('수학/삼각', 'AGGREGATE(function_num, options, ref1, ...)', '숨긴 행·오류를 무시하는 옵션으로 집계합니다.'),
  'AVERAGEIFS': F('통계', 'AVERAGEIFS(average_range, criteria_range1, criteria1, ...)', '여러 조건에 맞는 셀의 평균을 구합니다.'),
  'MAXIFS': F('통계', 'MAXIFS(max_range, criteria_range1, criteria1, ...)', '조건에 맞는 셀의 최대값을 구합니다.'),
  'MINIFS': F('통계', 'MINIFS(min_range, criteria_range1, criteria1, ...)', '조건에 맞는 셀의 최소값을 구합니다.'),
  'AVERAGEA': F('통계', 'AVERAGEA(value1, [value2], ...)', '텍스트·논리값을 포함한 평균을 구합니다.'),
  'MAXA': F('통계', 'MAXA(value1, [value2], ...)', '텍스트·논리값을 포함한 최대값을 구합니다.'),
  'MINA': F('통계', 'MINA(value1, [value2], ...)', '텍스트·논리값을 포함한 최소값을 구합니다.'),
  'STDEVA': F('통계', 'STDEVA(value1, [value2], ...)', '텍스트·논리값을 포함한 표본 표준 편차를 구합니다.'),
  'STDEVPA': F('통계', 'STDEVPA(value1, [value2], ...)', '텍스트·논리값을 포함한 모집단 표준 편차를 구합니다.'),
  'VARA': F('통계', 'VARA(value1, [value2], ...)', '텍스트·논리값을 포함한 표본 분산을 구합니다.'),
  'VARPA': F('통계', 'VARPA(value1, [value2], ...)', '텍스트·논리값을 포함한 모집단 분산을 구합니다.'),
  'AVEDEV': F('통계', 'AVEDEV(number1, [number2], ...)', '평균 절대 편차를 구합니다.'),
  'DEVSQ': F('통계', 'DEVSQ(number1, [number2], ...)', '편차 제곱의 합을 구합니다.'),
  'GEOMEAN': F('통계', 'GEOMEAN(number1, [number2], ...)', '기하 평균을 구합니다.'),
  'HARMEAN': F('통계', 'HARMEAN(number1, [number2], ...)', '조화 평균을 구합니다.'),
  'KURT': F('통계', 'KURT(number1, [number2], ...)', '첨도를 구합니다.'),
  'SKEW': F('통계', 'SKEW(number1, [number2], ...)', '표본 왜도를 구합니다.'),
  'SKEW.P': F('통계', 'SKEW.P(number1, [number2], ...)', '모집단 왜도를 구합니다.'),
  'TRIMMEAN': F('통계', 'TRIMMEAN(array, percent)', '양 끝 일부를 제외한 평균을 구합니다.'),
  'LARGE': F('통계', 'LARGE(array, k)', 'k번째로 큰 값을 구합니다.'),
  'SMALL': F('통계', 'SMALL(array, k)', 'k번째로 작은 값을 구합니다.'),
  'MODE': F('호환성', 'MODE(number1, [number2], ...)', '최빈값을 구합니다.'),
  'MODE.SNGL': F('통계', 'MODE.SNGL(number1, [number2], ...)', '최빈값을 구합니다.'),
  'MODE.MULT': F('통계', 'MODE.MULT(number1, [number2], ...)', '최빈값을 모두 세로 배열로 반환합니다.'),
  'RANK': F('호환성', 'RANK(number, ref, [order])', '목록에서 수의 순위를 구합니다.'),
  'RANK.EQ': F('통계', 'RANK.EQ(number, ref, [order])', '목록에서 수의 순위를 구합니다 (같은 값은 가장 높은 순위).'),
  'RANK.AVG': F('통계', 'RANK.AVG(number, ref, [order])', '목록에서 수의 순위를 구합니다 (같은 값은 평균 순위).'),
  'PERCENTILE': F('호환성', 'PERCENTILE(array, k)', 'k번째 백분위수를 구합니다.'),
  'PERCENTILE.INC': F('통계', 'PERCENTILE.INC(array, k)', 'k번째 백분위수를 구합니다 (0, 1 포함).'),
  'PERCENTILE.EXC': F('통계', 'PERCENTILE.EXC(array, k)', 'k번째 백분위수를 구합니다 (0, 1 제외).'),
  'QUARTILE': F('호환성', 'QUARTILE(array, quart)', '사분위수를 구합니다.'),
  'QUARTILE.INC': F('통계', 'QUARTILE.INC(array, quart)', '사분위수를 구합니다 (0, 1 포함).'),
  'QUARTILE.EXC': F('통계', 'QUARTILE.EXC(array, quart)', '사분위수를 구합니다 (0, 1 제외).'),
  'PERCENTRANK': F('호환성', 'PERCENTRANK(array, x, [significance])', '백분율 순위를 구합니다.'),
  'PERCENTRANK.INC': F('통계', 'PERCENTRANK.INC(array, x, [significance])', '백분율 순위를 구합니다 (0, 1 포함).'),
  'PERCENTRANK.EXC': F('통계', 'PERCENTRANK.EXC(array, x, [significance])', '백분율 순위를 구합니다 (0, 1 제외).'),
  'CORREL': F('통계', 'CORREL(array1, array2)', '상관 계수를 구합니다.'),
  'PEARSON': F('통계', 'PEARSON(array1, array2)', '피어슨 상관 계수를 구합니다.'),
  'RSQ': F('통계', 'RSQ(known_y\'s, known_x\'s)', '결정 계수(R 제곱)를 구합니다.'),
  'SLOPE': F('통계', 'SLOPE(known_y\'s, known_x\'s)', '선형 회귀선의 기울기를 구합니다.'),
  'INTERCEPT': F('통계', 'INTERCEPT(known_y\'s, known_x\'s)', '선형 회귀선의 y 절편을 구합니다.'),
  'STEYX': F('통계', 'STEYX(known_y\'s, known_x\'s)', '회귀의 표준 오차를 구합니다.'),
  'COVAR': F('호환성', 'COVAR(array1, array2)', '공분산을 구합니다.'),
  'COVARIANCE.P': F('통계', 'COVARIANCE.P(array1, array2)', '모집단 공분산을 구합니다.'),
  'COVARIANCE.S': F('통계', 'COVARIANCE.S(array1, array2)', '표본 공분산을 구합니다.'),
  'FORECAST': F('호환성', 'FORECAST(x, known_y\'s, known_x\'s)', '선형 추세로 값을 예측합니다.'),
  'FORECAST.LINEAR': F('통계', 'FORECAST.LINEAR(x, known_y\'s, known_x\'s)', '선형 추세로 값을 예측합니다.'),
  'FORECAST.ETS': F('통계', 'FORECAST.ETS(target_date, values, timeline, [seasonality], [data_completion], [aggregation])', '지수 평활(AAA) 알고리즘으로 미래 값을 예측합니다.'),
  'FORECAST.ETS.CONFINT': F('통계', 'FORECAST.ETS.CONFINT(target_date, values, timeline, [confidence_level], [seasonality], [data_completion], [aggregation])', '예측 값의 신뢰 구간(± 폭)을 반환합니다.'),
  'FORECAST.ETS.SEASONALITY': F('통계', 'FORECAST.ETS.SEASONALITY(values, timeline, [data_completion], [aggregation])', '시계열에서 찾은 계절 패턴의 길이를 반환합니다.'),
  'FORECAST.ETS.STAT': F('통계', 'FORECAST.ETS.STAT(values, timeline, statistic_type, [seasonality], [data_completion], [aggregation])', '지수 평활 예측의 통계 값(1 알파 … 8 단계 크기)을 반환합니다.'),
  'TREND': F('통계', 'TREND(known_y\'s, [known_x\'s], [new_x\'s], [const])', '선형 추세 값을 배열로 반환합니다.'),
  'GROWTH': F('통계', 'GROWTH(known_y\'s, [known_x\'s], [new_x\'s], [const])', '지수 추세 값을 배열로 반환합니다.'),
  'LINEST': F('통계', 'LINEST(known_y\'s, [known_x\'s], [const], [stats])', '선형 회귀 계수를 배열로 반환합니다.'),
  'LOGEST': F('통계', 'LOGEST(known_y\'s, [known_x\'s], [const], [stats])', '지수 회귀 계수를 배열로 반환합니다.'),
  'FREQUENCY': F('통계', 'FREQUENCY(data_array, bins_array)', '구간별 빈도를 세로 배열로 반환합니다.'),
  'PROB': F('통계', 'PROB(x_range, prob_range, lower_limit, [upper_limit])', '값이 구간에 있을 확률을 구합니다.'),
  'NORM.DIST': F('통계', 'NORM.DIST(x, mean, standard_dev, cumulative)', '정규 분포 값을 구합니다.'),
  'NORM.INV': F('통계', 'NORM.INV(probability, mean, standard_dev)', '정규 누적 분포의 역함수 값을 구합니다.'),
  'NORM.S.DIST': F('통계', 'NORM.S.DIST(z, cumulative)', '표준 정규 분포 값을 구합니다.'),
  'NORM.S.INV': F('통계', 'NORM.S.INV(probability)', '표준 정규 누적 분포의 역함수 값을 구합니다.'),
  'NORMDIST': F('호환성', 'NORMDIST(x, mean, standard_dev, cumulative)', '정규 분포 값을 구합니다.'),
  'NORMINV': F('호환성', 'NORMINV(probability, mean, standard_dev)', '정규 누적 분포의 역함수 값을 구합니다.'),
  'NORMSDIST': F('호환성', 'NORMSDIST(z)', '표준 정규 누적 분포 값을 구합니다.'),
  'NORMSINV': F('호환성', 'NORMSINV(probability)', '표준 정규 누적 분포의 역함수 값을 구합니다.'),
  'PHI': F('통계', 'PHI(x)', '표준 정규 분포의 밀도 함수 값을 구합니다.'),
  'GAUSS': F('통계', 'GAUSS(z)', '표준 정규 분포에서 평균과 z 사이의 확률을 구합니다.'),
  'STANDARDIZE': F('통계', 'STANDARDIZE(x, mean, standard_dev)', '정규화된 값을 구합니다.'),
  'LOGNORM.DIST': F('통계', 'LOGNORM.DIST(x, mean, standard_dev, cumulative)', '로그 정규 분포 값을 구합니다.'),
  'LOGNORM.INV': F('통계', 'LOGNORM.INV(probability, mean, standard_dev)', '로그 정규 누적 분포의 역함수 값을 구합니다.'),
  'LOGNORMDIST': F('호환성', 'LOGNORMDIST(x, mean, standard_dev)', '로그 정규 누적 분포 값을 구합니다.'),
  'LOGINV': F('호환성', 'LOGINV(probability, mean, standard_dev)', '로그 정규 누적 분포의 역함수 값을 구합니다.'),
  'EXPON.DIST': F('통계', 'EXPON.DIST(x, lambda, cumulative)', '지수 분포 값을 구합니다.'),
  'EXPONDIST': F('호환성', 'EXPONDIST(x, lambda, cumulative)', '지수 분포 값을 구합니다.'),
  'POISSON.DIST': F('통계', 'POISSON.DIST(x, mean, cumulative)', '포아송 분포 값을 구합니다.'),
  'POISSON': F('호환성', 'POISSON(x, mean, cumulative)', '포아송 분포 값을 구합니다.'),
  'BINOM.DIST': F('통계', 'BINOM.DIST(number_s, trials, probability_s, cumulative)', '이항 분포 확률을 구합니다.'),
  'BINOM.INV': F('통계', 'BINOM.INV(trials, probability_s, alpha)', '누적 이항 분포가 기준값 이상이 되는 최소값을 구합니다.'),
  'BINOMDIST': F('호환성', 'BINOMDIST(number_s, trials, probability_s, cumulative)', '이항 분포 확률을 구합니다.'),
  'CRITBINOM': F('호환성', 'CRITBINOM(trials, probability_s, alpha)', '누적 이항 분포가 기준값 이상이 되는 최소값을 구합니다.'),
  'NEGBINOM.DIST': F('통계', 'NEGBINOM.DIST(number_f, number_s, probability_s, cumulative)', '음이항 분포 값을 구합니다.'),
  'NEGBINOMDIST': F('호환성', 'NEGBINOMDIST(number_f, number_s, probability_s)', '음이항 분포 값을 구합니다.'),
  'HYPGEOM.DIST': F('통계', 'HYPGEOM.DIST(sample_s, number_sample, population_s, number_pop, cumulative)', '초기하 분포 값을 구합니다.'),
  'HYPGEOMDIST': F('호환성', 'HYPGEOMDIST(sample_s, number_sample, population_s, number_pop)', '초기하 분포 값을 구합니다.'),
  'GAMMA': F('통계', 'GAMMA(x)', '감마 함수 값을 구합니다.'),
  'GAMMALN': F('통계', 'GAMMALN(x)', '감마 함수의 자연 로그 값을 구합니다.'),
  'GAMMALN.PRECISE': F('통계', 'GAMMALN.PRECISE(x)', '감마 함수의 자연 로그 값을 구합니다.'),
  'GAMMA.DIST': F('통계', 'GAMMA.DIST(x, alpha, beta, cumulative)', '감마 분포 값을 구합니다.'),
  'GAMMA.INV': F('통계', 'GAMMA.INV(probability, alpha, beta)', '감마 누적 분포의 역함수 값을 구합니다.'),
  'GAMMADIST': F('호환성', 'GAMMADIST(x, alpha, beta, cumulative)', '감마 분포 값을 구합니다.'),
  'GAMMAINV': F('호환성', 'GAMMAINV(probability, alpha, beta)', '감마 누적 분포의 역함수 값을 구합니다.'),
  'BETA.DIST': F('통계', 'BETA.DIST(x, alpha, beta, cumulative, [A], [B])', '베타 분포 값을 구합니다.'),
  'BETA.INV': F('통계', 'BETA.INV(probability, alpha, beta, [A], [B])', '베타 누적 분포의 역함수 값을 구합니다.'),
  'BETADIST': F('호환성', 'BETADIST(x, alpha, beta, [A], [B])', '베타 누적 분포 값을 구합니다.'),
  'BETAINV': F('호환성', 'BETAINV(probability, alpha, beta, [A], [B])', '베타 누적 분포의 역함수 값을 구합니다.'),
  'T.DIST': F('통계', 'T.DIST(x, deg_freedom, cumulative)', 't 분포 값을 구합니다.'),
  'T.DIST.2T': F('통계', 'T.DIST.2T(x, deg_freedom)', '양측 t 분포 값을 구합니다.'),
  'T.DIST.RT': F('통계', 'T.DIST.RT(x, deg_freedom)', '우측 t 분포 값을 구합니다.'),
  'T.INV': F('통계', 'T.INV(probability, deg_freedom)', 't 분포의 좌측 역함수 값을 구합니다.'),
  'T.INV.2T': F('통계', 'T.INV.2T(probability, deg_freedom)', 't 분포의 양측 역함수 값을 구합니다.'),
  'TDIST': F('호환성', 'TDIST(x, deg_freedom, tails)', 't 분포 값을 구합니다.'),
  'TINV': F('호환성', 'TINV(probability, deg_freedom)', 't 분포의 양측 역함수 값을 구합니다.'),
  'T.TEST': F('통계', 'T.TEST(array1, array2, tails, type)', 't 검정 확률을 구합니다.'),
  'TTEST': F('호환성', 'TTEST(array1, array2, tails, type)', 't 검정 확률을 구합니다.'),
  'Z.TEST': F('통계', 'Z.TEST(array, x, [sigma])', 'z 검정의 단측 P 값을 구합니다.'),
  'ZTEST': F('호환성', 'ZTEST(array, x, [sigma])', 'z 검정의 단측 P 값을 구합니다.'),
  'CHISQ.DIST': F('통계', 'CHISQ.DIST(x, deg_freedom, cumulative)', '카이 제곱 분포 값을 구합니다.'),
  'CHISQ.DIST.RT': F('통계', 'CHISQ.DIST.RT(x, deg_freedom)', '카이 제곱 분포의 우측 확률을 구합니다.'),
  'CHISQ.INV': F('통계', 'CHISQ.INV(probability, deg_freedom)', '카이 제곱 분포의 좌측 역함수 값을 구합니다.'),
  'CHISQ.INV.RT': F('통계', 'CHISQ.INV.RT(probability, deg_freedom)', '카이 제곱 분포의 우측 역함수 값을 구합니다.'),
  'CHISQ.TEST': F('통계', 'CHISQ.TEST(actual_range, expected_range)', '카이 제곱 독립성 검정 값을 구합니다.'),
  'CHIDIST': F('호환성', 'CHIDIST(x, deg_freedom)', '카이 제곱 분포의 우측 확률을 구합니다.'),
  'CHIINV': F('호환성', 'CHIINV(probability, deg_freedom)', '카이 제곱 분포의 우측 역함수 값을 구합니다.'),
  'CHITEST': F('호환성', 'CHITEST(actual_range, expected_range)', '카이 제곱 독립성 검정 값을 구합니다.'),
  'F.DIST': F('통계', 'F.DIST(x, deg_freedom1, deg_freedom2, cumulative)', 'F 분포 값을 구합니다.'),
  'F.DIST.RT': F('통계', 'F.DIST.RT(x, deg_freedom1, deg_freedom2)', 'F 분포의 우측 확률을 구합니다.'),
  'F.INV': F('통계', 'F.INV(probability, deg_freedom1, deg_freedom2)', 'F 분포의 좌측 역함수 값을 구합니다.'),
  'F.INV.RT': F('통계', 'F.INV.RT(probability, deg_freedom1, deg_freedom2)', 'F 분포의 우측 역함수 값을 구합니다.'),
  'F.TEST': F('통계', 'F.TEST(array1, array2)', 'F 검정 결과를 구합니다.'),
  'FDIST': F('호환성', 'FDIST(x, deg_freedom1, deg_freedom2)', 'F 분포의 우측 확률을 구합니다.'),
  'FINV': F('호환성', 'FINV(probability, deg_freedom1, deg_freedom2)', 'F 분포의 우측 역함수 값을 구합니다.'),
  'FTEST': F('호환성', 'FTEST(array1, array2)', 'F 검정 결과를 구합니다.'),
  'WEIBULL.DIST': F('통계', 'WEIBULL.DIST(x, alpha, beta, cumulative)', '와이블 분포 값을 구합니다.'),
  'WEIBULL': F('호환성', 'WEIBULL(x, alpha, beta, cumulative)', '와이블 분포 값을 구합니다.'),
  'CONFIDENCE': F('호환성', 'CONFIDENCE(alpha, standard_dev, size)', '정규 분포를 사용한 신뢰 구간을 구합니다.'),
  'CONFIDENCE.NORM': F('통계', 'CONFIDENCE.NORM(alpha, standard_dev, size)', '정규 분포를 사용한 신뢰 구간을 구합니다.'),
  'CONFIDENCE.T': F('통계', 'CONFIDENCE.T(alpha, standard_dev, size)', 't 분포를 사용한 신뢰 구간을 구합니다.'),
  'FISHER': F('통계', 'FISHER(x)', '피셔 변환 값을 구합니다.'),
  'FISHERINV': F('통계', 'FISHERINV(y)', '피셔 변환의 역변환 값을 구합니다.'),
  'ERF': F('공학', 'ERF(lower_limit, [upper_limit])', '오차 함수 값을 구합니다.'),
  'ERF.PRECISE': F('공학', 'ERF.PRECISE(x)', '오차 함수 값을 구합니다.'),
  'ERFC': F('공학', 'ERFC(x)', '여오차 함수 값을 구합니다.'),
  'ERFC.PRECISE': F('공학', 'ERFC.PRECISE(x)', '여오차 함수 값을 구합니다.'),
  'SWITCH': F('논리', 'SWITCH(expression, value1, result1, ..., [default])', '값에 따라 결과를 고릅니다.'),
  'XOR': F('논리', 'XOR(logical1, [logical2], ...)', '참인 인수가 홀수 개이면 TRUE를 반환합니다.'),
  'LET': F('논리', 'LET(name1, value1, ..., calculation)', '계산 결과에 이름을 붙여 수식 안에서 다시 사용합니다.'),
  'LAMBDA': F('논리', 'LAMBDA([parameter1, ...], calculation)', '다시 사용할 수 있는 사용자 함수를 만듭니다.'),
  'MAP': F('논리', 'MAP(array1, ..., lambda)', '배열의 각 값에 LAMBDA를 적용한 배열을 반환합니다.'),
  'REDUCE': F('논리', 'REDUCE([initial_value], array, lambda)', '배열을 LAMBDA로 누적해 하나의 값으로 줄입니다.'),
  'SCAN': F('논리', 'SCAN([initial_value], array, lambda)', '배열을 LAMBDA로 누적한 중간 값을 배열로 반환합니다.'),
  'BYROW': F('논리', 'BYROW(array, lambda)', '각 행에 LAMBDA를 적용한 결과를 세로 배열로 반환합니다.'),
  'BYCOL': F('논리', 'BYCOL(array, lambda)', '각 열에 LAMBDA를 적용한 결과를 가로 배열로 반환합니다.'),
  'MAKEARRAY': F('논리', 'MAKEARRAY(rows, columns, lambda)', '행·열 번호로 LAMBDA를 계산한 배열을 만듭니다.'),
  'ISOMITTED': F('정보', 'ISOMITTED(argument)', 'LAMBDA의 인수가 생략되었는지 확인합니다.'),
  'CHAR': F('텍스트', 'CHAR(number)', '코드 번호에 해당하는 문자를 반환합니다.'),
  'CODE': F('텍스트', 'CODE(text)', '첫 문자의 코드 번호를 반환합니다.'),
  'UNICHAR': F('텍스트', 'UNICHAR(number)', '유니코드 번호에 해당하는 문자를 반환합니다.'),
  'UNICODE': F('텍스트', 'UNICODE(text)', '첫 문자의 유니코드 번호를 반환합니다.'),
  'CLEAN': F('텍스트', 'CLEAN(text)', '인쇄할 수 없는 문자를 제거합니다.'),
  'REPLACE': F('텍스트', 'REPLACE(old_text, start_num, num_chars, new_text)', '텍스트의 일부를 다른 텍스트로 바꿉니다.'),
  'REPLACEB': F('텍스트', 'REPLACEB(old_text, start_num, num_bytes, new_text)', '바이트 단위로 텍스트의 일부를 바꿉니다.'),
  'FINDB': F('텍스트', 'FINDB(find_text, within_text, [start_num])', '바이트 단위로 텍스트 위치를 찾습니다.'),
  'LEFTB': F('텍스트', 'LEFTB(text, [num_bytes])', '왼쪽부터 지정한 바이트 수만큼 반환합니다.'),
  'RIGHTB': F('텍스트', 'RIGHTB(text, [num_bytes])', '오른쪽부터 지정한 바이트 수만큼 반환합니다.'),
  'MIDB': F('텍스트', 'MIDB(text, start_num, num_bytes)', '중간에서 지정한 바이트 수만큼 반환합니다.'),
  'LENB': F('텍스트', 'LENB(text)', '텍스트의 바이트 수를 구합니다 (한글은 2바이트).'),
  'FIXED': F('텍스트', 'FIXED(number, [decimals], [no_commas])', '수를 고정 소수점 텍스트로 바꿉니다.'),
  'DOLLAR': F('텍스트', 'DOLLAR(number, [decimals])', '수를 통화 서식 텍스트로 바꿉니다.'),
  'WON': F('텍스트', 'WON(number, [decimals])', '수를 원화(₩) 서식 텍스트로 바꿉니다.'),
  'NUMBERVALUE': F('텍스트', 'NUMBERVALUE(text, [decimal_separator], [group_separator])', '지역 형식에 관계없이 텍스트를 숫자로 바꿉니다.'),
  'NUMBERSTRING': F('텍스트', 'NUMBERSTRING(number, type)', '숫자를 한글(1)·한자(2)·한글 숫자 나열(3)로 읽습니다.'),
  'ASC': F('텍스트', 'ASC(text)', '전자(전각) 문자를 반자(반각) 문자로 바꿉니다.'),
  'DBCS': F('텍스트', 'DBCS(text)', '반자(반각) 문자를 전자(전각) 문자로 바꿉니다.'),
  'JIS': F('텍스트', 'JIS(text)', '반자(반각) 문자를 전자(전각) 문자로 바꿉니다.'),
  'PHONETIC': F('텍스트', 'PHONETIC(reference)', '윗주(발음) 문자열을 추출합니다.'),
  'TEXTBEFORE': F('텍스트', 'TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', '구분 기호 앞의 텍스트를 반환합니다.'),
  'TEXTAFTER': F('텍스트', 'TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])', '구분 기호 뒤의 텍스트를 반환합니다.'),
  'TEXTSPLIT': F('텍스트', 'TEXTSPLIT(text, col_delimiter, [row_delimiter], [ignore_empty], [match_mode], [pad_with])', '구분 기호로 텍스트를 나눠 배열로 반환합니다.'),
  'ARRAYTOTEXT': F('텍스트', 'ARRAYTOTEXT(array, [format])', '배열을 텍스트로 바꿉니다.'),
  'VALUETOTEXT': F('텍스트', 'VALUETOTEXT(value, [format])', '값을 텍스트로 바꿉니다.'),
  'REGEXTEST': F('텍스트', 'REGEXTEST(text, pattern, [case_sensitivity])', '텍스트가 정규식과 일치하는지 확인합니다.'),
  'REGEXSEARCH': F('텍스트', 'REGEXSEARCH(pattern, within_text, [start_num], [case_sensitivity])', '정규식과 처음 일치하는 위치를 반환합니다 — SEARCH 의 정규식판 (위셀 확장).'),
  'REGEXMATCH': F('텍스트', 'REGEXMATCH(text, regular_expression)', '텍스트가 정규식과 일치하면 TRUE (구글 스프레드시트와 같음).'),
  'REGEXEXTRACT': F('텍스트', 'REGEXEXTRACT(text, pattern, [return_mode], [case_sensitivity])', '정규식과 일치하는 텍스트를 추출합니다.'),
  'REGEXREPLACE': F('텍스트', 'REGEXREPLACE(text, pattern, replacement, [occurrence], [case_sensitivity])', '정규식과 일치하는 텍스트를 바꿉니다.'),
  'T': F('텍스트', 'T(value)', '값이 텍스트이면 그대로, 아니면 빈 텍스트를 반환합니다.'),
  'ADDRESS': F('찾기/참조', 'ADDRESS(row_num, column_num, [abs_num], [a1], [sheet_text])', '행·열 번호로 셀 주소 텍스트를 만듭니다.'),
  'AREAS': F('찾기/참조', 'AREAS(reference)', '참조 안의 영역 수를 반환합니다.'),
  'CHOOSECOLS': F('찾기/참조', 'CHOOSECOLS(array, col_num1, ...)', '배열에서 지정한 열을 반환합니다.'),
  'CHOOSEROWS': F('찾기/참조', 'CHOOSEROWS(array, row_num1, ...)', '배열에서 지정한 행을 반환합니다.'),
  'COLUMN': F('찾기/참조', 'COLUMN([reference])', '참조의 열 번호를 반환합니다.'),
  'ROW': F('찾기/참조', 'ROW([reference])', '참조의 행 번호를 반환합니다.'),
  'DROP': F('찾기/참조', 'DROP(array, rows, [columns])', '배열의 처음 또는 끝에서 행·열을 제외합니다.'),
  'TAKE': F('찾기/참조', 'TAKE(array, rows, [columns])', '배열의 처음 또는 끝에서 행·열을 가져옵니다.'),
  'EXPAND': F('찾기/참조', 'EXPAND(array, rows, [columns], [pad_with])', '배열을 지정한 크기로 늘립니다.'),
  'FILTER': F('찾기/참조', 'FILTER(array, include, [if_empty])', '조건에 맞는 행(열)만 걸러 반환합니다.'),
  'SORT': F('찾기/참조', 'SORT(array, [sort_index], [sort_order], [by_col])', '배열을 정렬해 반환합니다.'),
  'SORTBY': F('찾기/참조', 'SORTBY(array, by_array1, [sort_order1], ...)', '다른 배열 값을 기준으로 정렬합니다.'),
  'UNIQUE': F('찾기/참조', 'UNIQUE(array, [by_col], [exactly_once])', '고유한 값 목록을 반환합니다.'),
  'TRANSPOSE': F('찾기/참조', 'TRANSPOSE(array)', '배열의 행과 열을 바꿉니다.'),
  'VSTACK': F('찾기/참조', 'VSTACK(array1, [array2], ...)', '배열을 세로로 이어 붙입니다.'),
  'HSTACK': F('찾기/참조', 'HSTACK(array1, [array2], ...)', '배열을 가로로 이어 붙입니다.'),
  'TOCOL': F('찾기/참조', 'TOCOL(array, [ignore], [scan_by_column])', '배열을 한 열로 바꿉니다.'),
  'TOROW': F('찾기/참조', 'TOROW(array, [ignore], [scan_by_column])', '배열을 한 행으로 바꿉니다.'),
  'WRAPCOLS': F('찾기/참조', 'WRAPCOLS(vector, wrap_count, [pad_with])', '벡터를 지정한 개수마다 열로 나눕니다.'),
  'WRAPROWS': F('찾기/참조', 'WRAPROWS(vector, wrap_count, [pad_with])', '벡터를 지정한 개수마다 행으로 나눕니다.'),
  'FORMULATEXT': F('찾기/참조', 'FORMULATEXT(reference)', '셀의 수식을 텍스트로 반환합니다.'),
  'GETPIVOTDATA': F('찾기/참조', 'GETPIVOTDATA(data_field, pivot_table, [field1, item1], ...)', '피벗 테이블에서 값을 가져옵니다.'),
  'IMAGE': F('찾기/참조', 'IMAGE(source, [alt_text], [sizing], [height], [width])', '웹 주소의 그림을 셀 안에 표시합니다. sizing: 0 셀에 맞춤, 1 셀 채우기, 2 원래 크기, 3 높이·너비 지정.'),
  'HYPERLINK': F('찾기/참조', 'HYPERLINK(link_location, [friendly_name])', '하이퍼링크를 만듭니다.'),
  'INDIRECT': F('찾기/참조', 'INDIRECT(ref_text, [a1])', '텍스트로 지정한 참조를 반환합니다.'),
  'LOOKUP': F('찾기/참조', 'LOOKUP(lookup_value, lookup_vector, [result_vector])', '벡터나 배열에서 값을 찾습니다.'),
  'OFFSET': F('찾기/참조', 'OFFSET(reference, rows, cols, [height], [width])', '기준 참조에서 떨어진 참조를 반환합니다.'),
  'XMATCH': F('찾기/참조', 'XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])', '배열에서 항목의 상대 위치를 반환합니다. match_mode 3 = 정규식.'),
  'GROUPBY': F('찾기/참조', 'GROUPBY(row_fields, values, function, [field_headers], [total_depth], [sort_order], [filter_array])', '행 필드로 묶어 값을 집계합니다.'),
  'PIVOTBY': F('찾기/참조', 'PIVOTBY(row_fields, col_fields, values, function, [field_headers], [row_total_depth], [row_sort_order], [col_total_depth], [col_sort_order], [filter_array])', '행·열 필드로 묶어 값을 집계합니다.'),
  'PERCENTOF': F('수학/삼각', 'PERCENTOF(data_subset, data_all)', '부분합이 전체에서 차지하는 비율을 구합니다.'),
  'DATEDIF': F('날짜/시간', 'DATEDIF(start_date, end_date, unit)', '두 날짜 사이의 일·월·년 수를 구합니다.'),
  'DATESTRING': F('날짜/시간', 'DATESTRING(serial_number)', '날짜를 "YY년 MM월 DD일" 텍스트로 바꿉니다.'),
  'DATEVALUE': F('날짜/시간', 'DATEVALUE(date_text)', '날짜 텍스트를 일련 번호로 바꿉니다.'),
  'DAYS': F('날짜/시간', 'DAYS(end_date, start_date)', '두 날짜 사이의 일수를 구합니다.'),
  'DAYS360': F('날짜/시간', 'DAYS360(start_date, end_date, [method])', '1년을 360일로 보고 두 날짜 사이의 일수를 구합니다.'),
  'EDATE': F('날짜/시간', 'EDATE(start_date, months)', '지정한 개월 수 전후의 날짜를 구합니다.'),
  'EOMONTH': F('날짜/시간', 'EOMONTH(start_date, months)', '지정한 개월 수 전후 달의 마지막 날짜를 구합니다.'),
  'ISOWEEKNUM': F('날짜/시간', 'ISOWEEKNUM(date)', 'ISO 주 번호를 구합니다.'),
  'NETWORKDAYS': F('날짜/시간', 'NETWORKDAYS(start_date, end_date, [holidays])', '두 날짜 사이의 작업일 수를 구합니다.'),
  'NETWORKDAYS.INTL': F('날짜/시간', 'NETWORKDAYS.INTL(start_date, end_date, [weekend], [holidays])', '주말을 지정해 작업일 수를 구합니다.'),
  'TIME': F('날짜/시간', 'TIME(hour, minute, second)', '시간 일련 번호를 구합니다.'),
  'TIMEVALUE': F('날짜/시간', 'TIMEVALUE(time_text)', '시간 텍스트를 일련 번호로 바꿉니다.'),
  'WEEKNUM': F('날짜/시간', 'WEEKNUM(serial_number, [return_type])', '연중 주 번호를 구합니다.'),
  'WORKDAY': F('날짜/시간', 'WORKDAY(start_date, days, [holidays])', '작업일 수만큼 지난 날짜를 구합니다.'),
  'WORKDAY.INTL': F('날짜/시간', 'WORKDAY.INTL(start_date, days, [weekend], [holidays])', '주말을 지정해 작업일 수만큼 지난 날짜를 구합니다.'),
  'YEARFRAC': F('날짜/시간', 'YEARFRAC(start_date, end_date, [basis])', '두 날짜 사이의 기간을 연 단위 비율로 구합니다.'),
  'CELL': F('정보', 'CELL(info_type, [reference])', '셀의 서식·위치·내용 정보를 반환합니다.'),
  'ERROR.TYPE': F('정보', 'ERROR.TYPE(error_val)', '오류 종류에 해당하는 번호를 반환합니다.'),
  'INFO': F('정보', 'INFO(type_text)', '현재 운영 환경 정보를 반환합니다.'),
  'ISEVEN': F('정보', 'ISEVEN(number)', '짝수이면 TRUE를 반환합니다.'),
  'ISODD': F('정보', 'ISODD(number)', '홀수이면 TRUE를 반환합니다.'),
  'ISFORMULA': F('정보', 'ISFORMULA(reference)', '수식이 들어 있는 셀이면 TRUE를 반환합니다.'),
  'ISNONTEXT': F('정보', 'ISNONTEXT(value)', '텍스트가 아니면 TRUE를 반환합니다.'),
  'ISREF': F('정보', 'ISREF(value)', '참조이면 TRUE를 반환합니다.'),
  'N': F('정보', 'N(value)', '값을 숫자로 바꿉니다.'),
  'SHEET': F('정보', 'SHEET([value])', '시트 번호를 반환합니다.'),
  'SHEETS': F('정보', 'SHEETS([reference])', '시트 수를 반환합니다.'),
  'TYPE': F('정보', 'TYPE(value)', '값의 종류를 나타내는 번호를 반환합니다.'),
  'FV': F('재무', 'FV(rate, nper, pmt, [pv], [type])', '투자의 미래 가치를 구합니다.'),
  'PV': F('재무', 'PV(rate, nper, pmt, [fv], [type])', '투자의 현재 가치를 구합니다.'),
  'PMT': F('재무', 'PMT(rate, nper, pv, [fv], [type])', '대출의 정기 상환액을 구합니다.'),
  'NPER': F('재무', 'NPER(rate, pmt, pv, [fv], [type])', '투자의 납입 기간 수를 구합니다.'),
  'RATE': F('재무', 'RATE(nper, pmt, pv, [fv], [type], [guess])', '기간별 이자율을 구합니다.'),
  'IPMT': F('재무', 'IPMT(rate, per, nper, pv, [fv], [type])', '지정한 기간의 이자 상환액을 구합니다.'),
  'PPMT': F('재무', 'PPMT(rate, per, nper, pv, [fv], [type])', '지정한 기간의 원금 상환액을 구합니다.'),
  'CUMIPMT': F('재무', 'CUMIPMT(rate, nper, pv, start_period, end_period, type)', '두 기간 사이의 누적 이자를 구합니다.'),
  'CUMPRINC': F('재무', 'CUMPRINC(rate, nper, pv, start_period, end_period, type)', '두 기간 사이의 누적 원금을 구합니다.'),
  'ISPMT': F('재무', 'ISPMT(rate, per, nper, pv)', '원금 균등 상환 시 특정 기간의 이자를 구합니다.'),
  'NPV': F('재무', 'NPV(rate, value1, [value2], ...)', '순 현재 가치를 구합니다.'),
  'XNPV': F('재무', 'XNPV(rate, values, dates)', '비정기 현금 흐름의 순 현재 가치를 구합니다.'),
  'IRR': F('재무', 'IRR(values, [guess])', '내부 수익률을 구합니다.'),
  'XIRR': F('재무', 'XIRR(values, dates, [guess])', '비정기 현금 흐름의 내부 수익률을 구합니다.'),
  'MIRR': F('재무', 'MIRR(values, finance_rate, reinvest_rate)', '수정 내부 수익률을 구합니다.'),
  'FVSCHEDULE': F('재무', 'FVSCHEDULE(principal, schedule)', '변동 이자율을 적용한 미래 가치를 구합니다.'),
  'EFFECT': F('재무', 'EFFECT(nominal_rate, npery)', '실효 연이율을 구합니다.'),
  'NOMINAL': F('재무', 'NOMINAL(effect_rate, npery)', '명목 연이율을 구합니다.'),
  'PDURATION': F('재무', 'PDURATION(rate, pv, fv)', '투자가 목표 가치에 이르는 기간 수를 구합니다.'),
  'RRI': F('재무', 'RRI(nper, pv, fv)', '투자 증가에 해당하는 이자율을 구합니다.'),
  'SLN': F('재무', 'SLN(cost, salvage, life)', '정액법 감가상각액을 구합니다.'),
  'SYD': F('재무', 'SYD(cost, salvage, life, per)', '연수 합계법 감가상각액을 구합니다.'),
  'DB': F('재무', 'DB(cost, salvage, life, period, [month])', '정률법 감가상각액을 구합니다.'),
  'DDB': F('재무', 'DDB(cost, salvage, life, period, [factor])', '이중 체감법 감가상각액을 구합니다.'),
  'VDB': F('재무', 'VDB(cost, salvage, life, start_period, end_period, [factor], [no_switch])', '기간을 지정해 체감법 감가상각액을 구합니다.'),
  'DOLLARDE': F('재무', 'DOLLARDE(fractional_dollar, fraction)', '분수로 표시된 가격을 소수로 바꿉니다.'),
  'DOLLARFR': F('재무', 'DOLLARFR(decimal_dollar, fraction)', '소수로 표시된 가격을 분수로 바꿉니다.'),
  'TBILLEQ': F('재무', 'TBILLEQ(settlement, maturity, discount)', '국채의 채권 등가 수익률을 구합니다.'),
  'TBILLPRICE': F('재무', 'TBILLPRICE(settlement, maturity, discount)', '국채의 액면가 100당 가격을 구합니다.'),
  'TBILLYIELD': F('재무', 'TBILLYIELD(settlement, maturity, pr)', '국채의 수익률을 구합니다.'),
  'DISC': F('재무', 'DISC(settlement, maturity, pr, redemption, [basis])', '유가 증권의 할인율을 구합니다.'),
  'INTRATE': F('재무', 'INTRATE(settlement, maturity, investment, redemption, [basis])', '완전 투자한 유가 증권의 이자율을 구합니다.'),
  'RECEIVED': F('재무', 'RECEIVED(settlement, maturity, investment, discount, [basis])', '만기 시 받는 금액을 구합니다.'),
  'PRICEDISC': F('재무', 'PRICEDISC(settlement, maturity, discount, redemption, [basis])', '할인된 유가 증권의 가격을 구합니다.'),
  'YIELDDISC': F('재무', 'YIELDDISC(settlement, maturity, pr, redemption, [basis])', '할인된 유가 증권의 연 수익률을 구합니다.'),
  'ACCRINTM': F('재무', 'ACCRINTM(issue, settlement, rate, [par], [basis])', '만기에 이자를 지급하는 증권의 경과 이자를 구합니다.'),
  'PRICE': F('재무', 'PRICE(settlement, maturity, rate, yld, redemption, frequency, [basis])', '정기 이자 지급 증권의 가격을 구합니다.'),
  'YIELD': F('재무', 'YIELD(settlement, maturity, rate, pr, redemption, frequency, [basis])', '정기 이자 지급 증권의 수익률을 구합니다.'),
  'DURATION': F('재무', 'DURATION(settlement, maturity, coupon, yld, frequency, [basis])', '증권의 매콜리 듀레이션을 구합니다.'),
  'MDURATION': F('재무', 'MDURATION(settlement, maturity, coupon, yld, frequency, [basis])', '증권의 수정 듀레이션을 구합니다.'),
  'COUPDAYBS': F('재무', 'COUPDAYBS(settlement, maturity, frequency, [basis])', '이자 지급 기간 시작일부터 결산일까지의 일수를 구합니다.'),
  'COUPDAYS': F('재무', 'COUPDAYS(settlement, maturity, frequency, [basis])', '결산일이 속한 이자 지급 기간의 일수를 구합니다.'),
  'COUPDAYSNC': F('재무', 'COUPDAYSNC(settlement, maturity, frequency, [basis])', '결산일부터 다음 이자 지급일까지의 일수를 구합니다.'),
  'COUPNCD': F('재무', 'COUPNCD(settlement, maturity, frequency, [basis])', '결산일 다음 이자 지급일을 구합니다.'),
  'COUPNUM': F('재무', 'COUPNUM(settlement, maturity, frequency, [basis])', '결산일과 만기일 사이의 이자 지급 횟수를 구합니다.'),
  'COUPPCD': F('재무', 'COUPPCD(settlement, maturity, frequency, [basis])', '결산일 이전 이자 지급일을 구합니다.'),
  'BIN2DEC': F('공학', 'BIN2DEC(number)', '2진수를 10진수로 바꿉니다.'),
  'BIN2HEX': F('공학', 'BIN2HEX(number, [places])', '2진수를 16진수로 바꿉니다.'),
  'BIN2OCT': F('공학', 'BIN2OCT(number, [places])', '2진수를 8진수로 바꿉니다.'),
  'DEC2BIN': F('공학', 'DEC2BIN(number, [places])', '10진수를 2진수로 바꿉니다.'),
  'DEC2HEX': F('공학', 'DEC2HEX(number, [places])', '10진수를 16진수로 바꿉니다.'),
  'DEC2OCT': F('공학', 'DEC2OCT(number, [places])', '10진수를 8진수로 바꿉니다.'),
  'HEX2BIN': F('공학', 'HEX2BIN(number, [places])', '16진수를 2진수로 바꿉니다.'),
  'HEX2DEC': F('공학', 'HEX2DEC(number)', '16진수를 10진수로 바꿉니다.'),
  'HEX2OCT': F('공학', 'HEX2OCT(number, [places])', '16진수를 8진수로 바꿉니다.'),
  'OCT2BIN': F('공학', 'OCT2BIN(number, [places])', '8진수를 2진수로 바꿉니다.'),
  'OCT2DEC': F('공학', 'OCT2DEC(number)', '8진수를 10진수로 바꿉니다.'),
  'OCT2HEX': F('공학', 'OCT2HEX(number, [places])', '8진수를 16진수로 바꿉니다.'),
  'BITAND': F('공학', 'BITAND(number1, number2)', '비트 단위 AND 값을 구합니다.'),
  'BITOR': F('공학', 'BITOR(number1, number2)', '비트 단위 OR 값을 구합니다.'),
  'BITXOR': F('공학', 'BITXOR(number1, number2)', '비트 단위 XOR 값을 구합니다.'),
  'BITLSHIFT': F('공학', 'BITLSHIFT(number, shift_amount)', '비트를 왼쪽으로 이동합니다.'),
  'BITRSHIFT': F('공학', 'BITRSHIFT(number, shift_amount)', '비트를 오른쪽으로 이동합니다.'),
  'CONVERT': F('공학', 'CONVERT(number, from_unit, to_unit)', '측정 단위를 변환합니다.'),
  'DELTA': F('공학', 'DELTA(number1, [number2])', '두 값이 같으면 1, 다르면 0을 반환합니다.'),
  'GESTEP': F('공학', 'GESTEP(number, [step])', '수가 기준값 이상이면 1을 반환합니다.'),
  'DAVERAGE': F('데이터베이스', 'DAVERAGE(database, field, criteria)', '조건에 맞는 레코드의 평균을 구합니다.'),
  'DCOUNT': F('데이터베이스', 'DCOUNT(database, [field], criteria)', '조건에 맞는 레코드에서 숫자 셀 수를 셉니다.'),
  'DCOUNTA': F('데이터베이스', 'DCOUNTA(database, [field], criteria)', '조건에 맞는 레코드에서 비어 있지 않은 셀 수를 셉니다.'),
  'DGET': F('데이터베이스', 'DGET(database, field, criteria)', '조건에 맞는 하나의 값을 가져옵니다.'),
  'DMAX': F('데이터베이스', 'DMAX(database, field, criteria)', '조건에 맞는 레코드의 최대값을 구합니다.'),
  'DMIN': F('데이터베이스', 'DMIN(database, field, criteria)', '조건에 맞는 레코드의 최소값을 구합니다.'),
  'DPRODUCT': F('데이터베이스', 'DPRODUCT(database, field, criteria)', '조건에 맞는 레코드의 곱을 구합니다.'),
  'DSTDEV': F('데이터베이스', 'DSTDEV(database, field, criteria)', '조건에 맞는 레코드의 표본 표준 편차를 구합니다.'),
  'DSTDEVP': F('데이터베이스', 'DSTDEVP(database, field, criteria)', '조건에 맞는 레코드의 모집단 표준 편차를 구합니다.'),
  'DSUM': F('데이터베이스', 'DSUM(database, field, criteria)', '조건에 맞는 레코드의 합을 구합니다.'),
  'DVAR': F('데이터베이스', 'DVAR(database, field, criteria)', '조건에 맞는 레코드의 표본 분산을 구합니다.'),
  'DVARP': F('데이터베이스', 'DVARP(database, field, criteria)', '조건에 맞는 레코드의 모집단 분산을 구합니다.'),
  'IMPORTXML': F('구글 스프레드시트', 'IMPORTXML(url, xpath_query)', '웹 페이지 · XML 에서 XPath 로 고른 값들을 가져옵니다. 예: IMPORTXML("https://…", "//h2")'),
  'IMPORTHTML': F('구글 스프레드시트', 'IMPORTHTML(url, "table"|"list", index)', '웹 페이지의 몇 번째 표 또는 목록을 가져옵니다.'),
  'IMPORTDATA': F('구글 스프레드시트', 'IMPORTDATA(url, [delimiter], [locale])', '웹의 CSV · TSV 파일을 표로 가져옵니다.'),
  'IMPORTFEED': F('구글 스프레드시트', 'IMPORTFEED(url, [query], [headers], [num_items])', 'RSS · Atom 피드의 항목(제목 · 링크 · 날짜 · 요약)을 가져옵니다.'),
  'IMPORTRANGE': F('구글 스프레드시트', 'IMPORTRANGE(spreadsheet_url, range_string)', '공개 Google Sheets 주소·문서 ID 또는 WIXEL 문서 이름의 범위를 가져옵니다. A1:C처럼 끝 행을 생략할 수 있습니다. 시트 이름을 생략하면 주소의 gid와 관계없이 첫 탭을 가져옵니다. 특정 탭은 시트명!A1:C로 지정하세요. 게시 주소는 gid로 탭을 지정하세요. 비공개 Google 시트 인증은 지원하지 않습니다. F9 또는 모두 새로 고침으로 다시 가져옵니다.'),
  'GOOGLEFINANCE': F('구글 스프레드시트', 'GOOGLEFINANCE(ticker, [attribute], [start_date], [end_date|num_days], [interval])', '주식 · 환율 시세를 가져옵니다. 예: GOOGLEFINANCE("KRX:005930"), GOOGLEFINANCE("NASDAQ:GOOG","price"), GOOGLEFINANCE("CURRENCY:USDKRW")'),
  'GOOGLETRANSLATE': F('구글 스프레드시트', 'GOOGLETRANSLATE(text, [source_language], [target_language])', '텍스트를 번역합니다. 언어 코드 예: "en", "ko", "ja", 자동 감지 "auto"'),
  'DETECTLANGUAGE': F('구글 스프레드시트', 'DETECTLANGUAGE(text_or_range)', '텍스트의 언어 코드를 알아냅니다 (예: "en").'),
  'SPARKLINE': F('구글 스프레드시트', 'SPARKLINE(data, [options])', '셀 안에 작은 차트를 그립니다. 옵션: {"charttype","column"; "color","red"} — line · column · bar · winloss'),
  'QUERY': F('구글 스프레드시트', 'QUERY(data, query, [headers])', 'select·where·group by·pivot·order by·limit·offset·label·format으로 조회합니다. headers는 머리글 행 수(0=없음, -1=추측). 혼합 자료형은 다수 자료형만 사용합니다. format은 실제 숫자를 유지하며 표시를 바꿉니다. 가져온 배열은 Col1·Col2로 열을 지정하세요.'),
  'ARRAYFORMULA': F('구글 스프레드시트', 'ARRAYFORMULA(array_formula)', '배열 수식의 결과를 여러 셀에 표시합니다 (WIXEL 은 동적 배열이라 그대로 계산).'),
  'SPLIT': F('구글 스프레드시트', 'SPLIT(text, delimiter, [split_by_each], [remove_empty_text])', '구분 기호로 텍스트를 나누어 여러 셀에 넣습니다.'),
  'JOIN': F('구글 스프레드시트', 'JOIN(delimiter, value_or_array1, [value_or_array2], ...)', '값과 배열의 요소를 구분 기호로 이어 붙입니다.'),
  'FLATTEN': F('구글 스프레드시트', 'FLATTEN(range1, [range2], ...)', '여러 범위를 한 열로 펼칩니다.'),
  'SORTN': F('구글 스프레드시트', 'SORTN(range, [n], [display_ties_mode], [sort_column], [is_ascending], ...)', '정렬한 뒤 처음 n개 행을 돌려줍니다 (동점 · 중복 처리 모드 0~3).'),
  'ARRAY_CONSTRAIN': F('구글 스프레드시트', 'ARRAY_CONSTRAIN(input_range, num_rows, num_cols)', '배열 결과를 지정한 크기로 자릅니다.'),
  'COUNTUNIQUE': F('구글 스프레드시트', 'COUNTUNIQUE(value1, [value2], ...)', '고유한 값의 개수를 셉니다.'),
  'COUNTUNIQUEIFS': F('구글 스프레드시트', 'COUNTUNIQUEIFS(range, criteria_range1, criterion1, ...)', '조건에 맞는 고유한 값의 개수를 셉니다.'),
  'AVERAGE.WEIGHTED': F('구글 스프레드시트', 'AVERAGE.WEIGHTED(values, weights, [additional_values, additional_weights], ...)', '가중 평균을 구합니다.'),
  'MARGINOFERROR': F('구글 스프레드시트', 'MARGINOFERROR(range, confidence)', '표본의 오차 범위(신뢰 수준)를 구합니다.'),
  'ISEMAIL': F('구글 스프레드시트', 'ISEMAIL(value)', '이메일 주소 형식이면 TRUE 입니다.'),
  'ISURL': F('구글 스프레드시트', 'ISURL(value)', '웹 주소(URL) 형식이면 TRUE 입니다.'),
  'ISBETWEEN': F('구글 스프레드시트', 'ISBETWEEN(value, lower, upper, [lower_inclusive], [upper_inclusive])', '값이 두 값 사이에 있으면 TRUE 입니다.'),
  'TO_DATE': F('구글 스프레드시트', 'TO_DATE(value)', '수를 날짜로 표시합니다.'),
  'TO_TEXT': F('구글 스프레드시트', 'TO_TEXT(value)', '값을 텍스트로 바꿉니다.'),
  'TO_PERCENT': F('구글 스프레드시트', 'TO_PERCENT(value)', '수를 백분율로 표시합니다.'),
  'TO_DOLLARS': F('구글 스프레드시트', 'TO_DOLLARS(value)', '수를 통화로 표시합니다.'),
  'TO_PURE_NUMBER': F('구글 스프레드시트', 'TO_PURE_NUMBER(value)', '날짜 · 백분율 · 통화 텍스트를 서식 없는 수로 바꿉니다.'),
  'EPOCHTODATE': F('구글 스프레드시트', 'EPOCHTODATE(timestamp, [unit])', '유닉스 시간(초=1 · 밀리초=2 · 마이크로초=3)을 날짜/시간(UTC)으로 바꿉니다.'),
  'ADD': F('구글 스프레드시트', 'ADD(value1, value2)', '두 수를 더합니다 (+ 연산자).'),
  'MINUS': F('구글 스프레드시트', 'MINUS(value1, value2)', '두 수의 차를 구합니다 (- 연산자).'),
  'MULTIPLY': F('구글 스프레드시트', 'MULTIPLY(factor1, factor2)', '두 수를 곱합니다 (* 연산자).'),
  'DIVIDE': F('구글 스프레드시트', 'DIVIDE(dividend, divisor)', '나눕니다 (/ 연산자).'),
  'POW': F('구글 스프레드시트', 'POW(base, exponent)', '거듭제곱을 구합니다 (^ 연산자).'),
  'EQ': F('구글 스프레드시트', 'EQ(value1, value2)', '두 값이 같으면 TRUE (= 연산자).'),
  'NE': F('구글 스프레드시트', 'NE(value1, value2)', '두 값이 다르면 TRUE (<> 연산자).'),
  'GT': F('구글 스프레드시트', 'GT(value1, value2)', '앞 값이 크면 TRUE (> 연산자).'),
  'GTE': F('구글 스프레드시트', 'GTE(value1, value2)', '앞 값이 크거나 같으면 TRUE (>= 연산자).'),
  'LT': F('구글 스프레드시트', 'LT(value1, value2)', '앞 값이 작으면 TRUE (< 연산자).'),
  'LTE': F('구글 스프레드시트', 'LTE(value1, value2)', '앞 값이 작거나 같으면 TRUE (<= 연산자).'),
  'UMINUS': F('구글 스프레드시트', 'UMINUS(value)', '부호를 바꿉니다.'),
  'UPLUS': F('구글 스프레드시트', 'UPLUS(value)', '값을 그대로 돌려줍니다.'),
  'UNARY_PERCENT': F('구글 스프레드시트', 'UNARY_PERCENT(percentage)', '값을 100으로 나눕니다 (% 연산자).'),
  'WEBSERVICE': F('웹', 'WEBSERVICE(url)', '웹 서비스(URL)가 돌려주는 데이터를 텍스트로 가져옵니다.'),
  'ENCODEURL': F('웹', 'ENCODEURL(text)', '텍스트를 URL 인코딩합니다.'),
  'FILTERXML': F('웹', 'FILTERXML(xml, xpath)', 'XML 텍스트에서 XPath 로 값을 골라냅니다.'),
  'TRANSLATE': F('텍스트', 'TRANSLATE(text, [source_language], [target_language])', '텍스트를 다른 언어로 번역합니다 (Microsoft 365).'),
  'STOCKHISTORY': F('재무', 'STOCKHISTORY(stock, start_date, [end_date], [interval], [headers], [property0], ...)', '주식의 과거 시세(날짜 · 종가 · 시가 · 고가 · 저가 · 거래량)를 가져옵니다.'),
  'TRIMRANGE': F('찾기/참조', 'TRIMRANGE(range, [trim_rows], [trim_cols])', '범위 가장자리의 빈 행 · 열을 잘라냅니다 (0 없음 · 1 앞 · 2 뒤 · 3 둘 다).'),
  'ACCRINT': F('재무', 'ACCRINT(issue, first_interest, settlement, rate, par, frequency, [basis], [calc_method])', '정기적으로 이자를 지급하는 증권의 경과 이자를 구합니다.'),
  'BAHTTEXT': F('텍스트', 'BAHTTEXT(number)', '수를 태국어 바트 텍스트로 바꿉니다.'),
  'SEARCHB': F('텍스트', 'SEARCHB(find_text, within_text, [start_num])', '바이트 단위로 텍스트 위치를 찾습니다 (대/소문자 무시, 와일드카드).'),
  'ECMA.CEILING': F('호환성', 'ECMA.CEILING(number, significance)', '수를 significance 의 배수로 올림합니다.'),
  'BINOM.DIST.RANGE': F('통계', 'BINOM.DIST.RANGE(trials, probability_s, number_s, [number_s2])', '시행 결과가 범위 안에 들 이항 분포 확률을 구합니다.'),
};
