// 함수 설명 (자동 완성 · 함수 삽입 대화상자)
export const CATEGORIES = ['수학/삼각', '통계', '논리', '텍스트', '찾기/참조', '날짜/시간', '정보'];

const F = (cat, sig, desc) => ({ cat, sig, desc });

export const FUNC_INFO = {
  SUM: F('수학/삼각', 'SUM(number1, [number2], ...)', '인수들의 합을 구합니다.'),
  PRODUCT: F('수학/삼각', 'PRODUCT(number1, [number2], ...)', '인수들의 곱을 구합니다.'),
  SUMPRODUCT: F('수학/삼각', 'SUMPRODUCT(array1, [array2], ...)', '배열의 대응 요소를 곱한 뒤 합을 구합니다.'),
  SUMIF: F('수학/삼각', 'SUMIF(range, criteria, [sum_range])', '조건에 맞는 셀의 합을 구합니다.'),
  SUMIFS: F('수학/삼각', 'SUMIFS(sum_range, criteria_range1, criteria1, ...)', '여러 조건에 맞는 셀의 합을 구합니다.'),
  ROUND: F('수학/삼각', 'ROUND(number, num_digits)', '수를 지정한 자릿수로 반올림합니다.'),
  ROUNDUP: F('수학/삼각', 'ROUNDUP(number, num_digits)', '수를 지정한 자릿수로 올림합니다.'),
  ROUNDDOWN: F('수학/삼각', 'ROUNDDOWN(number, num_digits)', '수를 지정한 자릿수로 내림합니다.'),
  TRUNC: F('수학/삼각', 'TRUNC(number, [num_digits])', '수의 소수점 이하를 버립니다.'),
  INT: F('수학/삼각', 'INT(number)', '가장 가까운 정수로 내림합니다.'),
  ABS: F('수학/삼각', 'ABS(number)', '절대값을 구합니다.'),
  SIGN: F('수학/삼각', 'SIGN(number)', '수의 부호를 구합니다.'),
  MOD: F('수학/삼각', 'MOD(number, divisor)', '나눗셈의 나머지를 구합니다.'),
  POWER: F('수학/삼각', 'POWER(number, power)', '거듭제곱을 구합니다.'),
  SQRT: F('수학/삼각', 'SQRT(number)', '양의 제곱근을 구합니다.'),
  EXP: F('수학/삼각', 'EXP(number)', 'e를 number만큼 거듭제곱합니다.'),
  LN: F('수학/삼각', 'LN(number)', '자연 로그를 구합니다.'),
  LOG: F('수학/삼각', 'LOG(number, [base])', '지정한 밑의 로그를 구합니다.'),
  LOG10: F('수학/삼각', 'LOG10(number)', '밑이 10인 로그를 구합니다.'),
  PI: F('수학/삼각', 'PI()', '원주율 값을 반환합니다.'),
  RAND: F('수학/삼각', 'RAND()', '0 이상 1 미만의 난수를 반환합니다.'),
  RANDBETWEEN: F('수학/삼각', 'RANDBETWEEN(bottom, top)', '두 수 사이의 정수 난수를 반환합니다.'),

  AVERAGE: F('통계', 'AVERAGE(number1, [number2], ...)', '인수들의 평균을 구합니다.'),
  AVERAGEIF: F('통계', 'AVERAGEIF(range, criteria, [average_range])', '조건에 맞는 셀의 평균을 구합니다.'),
  COUNT: F('통계', 'COUNT(value1, [value2], ...)', '숫자가 포함된 셀의 개수를 셉니다.'),
  COUNTA: F('통계', 'COUNTA(value1, [value2], ...)', '비어 있지 않은 셀의 개수를 셉니다.'),
  COUNTBLANK: F('통계', 'COUNTBLANK(range)', '빈 셀의 개수를 셉니다.'),
  COUNTIF: F('통계', 'COUNTIF(range, criteria)', '조건에 맞는 셀의 개수를 셉니다.'),
  COUNTIFS: F('통계', 'COUNTIFS(criteria_range1, criteria1, ...)', '여러 조건에 맞는 셀의 개수를 셉니다.'),
  MAX: F('통계', 'MAX(number1, [number2], ...)', '최대값을 구합니다.'),
  MIN: F('통계', 'MIN(number1, [number2], ...)', '최소값을 구합니다.'),
  MEDIAN: F('통계', 'MEDIAN(number1, [number2], ...)', '중간값을 구합니다.'),

  IF: F('논리', 'IF(logical_test, [value_if_true], [value_if_false])', '조건이 참이면 한 값을, 거짓이면 다른 값을 반환합니다.'),
  IFS: F('논리', 'IFS(logical_test1, value1, ...)', '첫 번째로 참인 조건의 값을 반환합니다.'),
  IFERROR: F('논리', 'IFERROR(value, value_if_error)', '오류이면 지정한 값을, 아니면 수식 결과를 반환합니다.'),
  IFNA: F('논리', 'IFNA(value, value_if_na)', '#N/A 오류이면 지정한 값을 반환합니다.'),
  AND: F('논리', 'AND(logical1, [logical2], ...)', '모든 인수가 참이면 TRUE를 반환합니다.'),
  OR: F('논리', 'OR(logical1, [logical2], ...)', '하나 이상의 인수가 참이면 TRUE를 반환합니다.'),
  NOT: F('논리', 'NOT(logical)', '논리값을 반대로 바꿉니다.'),
  TRUE: F('논리', 'TRUE()', '논리값 TRUE를 반환합니다.'),
  FALSE: F('논리', 'FALSE()', '논리값 FALSE를 반환합니다.'),
  CHOOSE: F('논리', 'CHOOSE(index_num, value1, [value2], ...)', '목록에서 index_num 번째 값을 고릅니다.'),

  CONCATENATE: F('텍스트', 'CONCATENATE(text1, [text2], ...)', '여러 텍스트를 하나로 연결합니다.'),
  CONCAT: F('텍스트', 'CONCAT(text1, [text2], ...)', '범위를 포함한 텍스트를 연결합니다.'),
  TEXTJOIN: F('텍스트', 'TEXTJOIN(delimiter, ignore_empty, text1, ...)', '구분 기호를 넣어 텍스트를 연결합니다.'),
  LEN: F('텍스트', 'LEN(text)', '텍스트의 문자 수를 구합니다.'),
  LEFT: F('텍스트', 'LEFT(text, [num_chars])', '텍스트의 왼쪽부터 문자를 반환합니다.'),
  RIGHT: F('텍스트', 'RIGHT(text, [num_chars])', '텍스트의 오른쪽부터 문자를 반환합니다.'),
  MID: F('텍스트', 'MID(text, start_num, num_chars)', '텍스트의 중간에서 문자를 반환합니다.'),
  UPPER: F('텍스트', 'UPPER(text)', '대문자로 바꿉니다.'),
  LOWER: F('텍스트', 'LOWER(text)', '소문자로 바꿉니다.'),
  PROPER: F('텍스트', 'PROPER(text)', '각 단어의 첫 글자를 대문자로 바꿉니다.'),
  TRIM: F('텍스트', 'TRIM(text)', '불필요한 공백을 제거합니다.'),
  REPT: F('텍스트', 'REPT(text, number_times)', '텍스트를 지정한 횟수만큼 반복합니다.'),
  SUBSTITUTE: F('텍스트', 'SUBSTITUTE(text, old_text, new_text, [instance_num])', '텍스트의 일부를 바꿉니다.'),
  FIND: F('텍스트', 'FIND(find_text, within_text, [start_num])', '텍스트의 위치를 찾습니다(대/소문자 구분).'),
  SEARCH: F('텍스트', 'SEARCH(find_text, within_text, [start_num])', '텍스트의 위치를 찾습니다(와일드카드 사용 가능).'),
  EXACT: F('텍스트', 'EXACT(text1, text2)', '두 텍스트가 정확히 같은지 확인합니다.'),
  VALUE: F('텍스트', 'VALUE(text)', '텍스트를 숫자로 바꿉니다.'),
  TEXT: F('텍스트', 'TEXT(value, format_text)', '숫자에 서식을 지정하여 텍스트로 바꿉니다.'),

  VLOOKUP: F('찾기/참조', 'VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])', '표의 첫 열에서 값을 찾아 같은 행의 값을 반환합니다.'),
  HLOOKUP: F('찾기/참조', 'HLOOKUP(lookup_value, table_array, row_index_num, [range_lookup])', '표의 첫 행에서 값을 찾아 같은 열의 값을 반환합니다.'),
  XLOOKUP: F('찾기/참조', 'XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found])', '범위에서 값을 찾아 대응하는 항목을 반환합니다.'),
  INDEX: F('찾기/참조', 'INDEX(array, row_num, [column_num])', '범위에서 지정한 위치의 값을 반환합니다.'),
  MATCH: F('찾기/참조', 'MATCH(lookup_value, lookup_array, [match_type])', '범위에서 값의 상대 위치를 반환합니다.'),
  ROWS: F('찾기/참조', 'ROWS(array)', '범위의 행 수를 반환합니다.'),
  COLUMNS: F('찾기/참조', 'COLUMNS(array)', '범위의 열 수를 반환합니다.'),

  TODAY: F('날짜/시간', 'TODAY()', '오늘 날짜를 반환합니다.'),
  NOW: F('날짜/시간', 'NOW()', '현재 날짜와 시간을 반환합니다.'),
  DATE: F('날짜/시간', 'DATE(year, month, day)', '날짜 일련 번호를 반환합니다.'),
  YEAR: F('날짜/시간', 'YEAR(serial_number)', '연도를 반환합니다.'),
  MONTH: F('날짜/시간', 'MONTH(serial_number)', '월을 반환합니다.'),
  DAY: F('날짜/시간', 'DAY(serial_number)', '일을 반환합니다.'),
  HOUR: F('날짜/시간', 'HOUR(serial_number)', '시를 반환합니다.'),
  MINUTE: F('날짜/시간', 'MINUTE(serial_number)', '분을 반환합니다.'),
  SECOND: F('날짜/시간', 'SECOND(serial_number)', '초를 반환합니다.'),
  WEEKDAY: F('날짜/시간', 'WEEKDAY(serial_number, [return_type])', '요일 번호를 반환합니다.'),

  ISBLANK: F('정보', 'ISBLANK(value)', '빈 셀이면 TRUE를 반환합니다.'),
  ISNUMBER: F('정보', 'ISNUMBER(value)', '숫자이면 TRUE를 반환합니다.'),
  ISTEXT: F('정보', 'ISTEXT(value)', '텍스트이면 TRUE를 반환합니다.'),
  ISLOGICAL: F('정보', 'ISLOGICAL(value)', '논리값이면 TRUE를 반환합니다.'),
  ISERROR: F('정보', 'ISERROR(value)', '오류 값이면 TRUE를 반환합니다.'),
  ISERR: F('정보', 'ISERR(value)', '#N/A를 제외한 오류이면 TRUE를 반환합니다.'),
  ISNA: F('정보', 'ISNA(value)', '#N/A 오류이면 TRUE를 반환합니다.'),
  NA: F('정보', 'NA()', '#N/A 오류 값을 반환합니다.'),
};
