import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const { chromium }=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5191/',browser=await chromium.launch(),results=[];
let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++;},ok=a=>{assert.ok(a);checks++;};
const fixture=()=>({sheets:[{name:'차트 합성',cells:{'0,0':{raw:'품목'},'0,1':{raw:'금액'},'1,0':{raw:'가'},'1,1':{raw:'30'},'2,0':{raw:'나'},'2,1':{raw:'70'}},charts:[{id:'ch',type:'column',range:{r1:0,c1:0,r2:2,c2:1},x:60,y:80,w:620,h:350,title:'검증 차트',legend:'b',plotFill:'#eeeeee',fill:'#123456',seriesFmt:[{color:'#70ad47'}]}]},{name:'다른 시트',cells:{}}]});
const chart=p=>p.locator('.obj.chart[data-id="ch"]').first(),menu=p=>p.locator('#menuLayer>.menu[data-level="0"]');
const state=p=>p.evaluate(()=>window.tabula.wb().serialize());
async function open(p,part='plot'){const o=chart(p);await o.waitFor();if(part==='plot')await o.locator('[data-el="plot"]').first().click({button:'right',position:{x:100,y:40},force:true});else await o.click({button:'right',position:{x:4,y:4},force:true});await menu(p).waitFor();}
async function test(name,fn,mobile=false){const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile}),p=await ctx.newPage(),errors=[],writes=[];const start=checks;
 p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(!['GET','HEAD','OPTIONS'].includes(r.method())){writes.push(r.url());return route.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/'))return route.abort();return route.continue();});
 await p.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;window.__saved=[];window.showSaveFilePicker=async options=>{window.__saved.push(options);return{name:options.suggestedName,createWritable:async()=>({write:async blob=>{window.__savedBytes=[...new Uint8Array(await blob.arrayBuffer())];},close:async()=>{},abort:async()=>{}})};};Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{},readText:async()=>''}});});
 try{await p.goto(url,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>!!window.tabula?.wb());await p.evaluate(data=>{const t=window.tabula;t.wb().restore(data);t.switchSheet(0);t.gv().layout();t.gv().renderAll();t.wb().undoStack=[];},fixture());await fn(p);eq(errors,[]);eq(writes,[]);results.push({name,ok:true,checks:checks-start});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.stack,errors,menu:await menu(p).innerText().catch(()=>''),part:await p.evaluate(()=>window.tabula.chartPart)});console.error('NG '+name+': '+e.stack);}finally{await ctx.close();}}
try{
await test('그림 영역 메뉴와 전용 패널',async p=>{await open(p);const text=await menu(p).innerText();for(const name of ['차트 삭제','스타일에 맞게 다시 설정','차트 종류 변경','서식 파일로 저장','데이터 선택','3차원 회전','그림 영역 서식'])ok(text.includes(name));ok(await menu(p).getByRole('menuitem',{name:/3차원 회전/}).isDisabled());await menu(p).getByRole('menuitem',{name:/그림 영역 서식/}).click();await p.getByRole('dialog',{name:'그림 영역 서식',exact:true}).waitFor();ok(await p.getByRole('radio',{name:'그라데이션 채우기',exact:true}).count()>0);});
await test('스타일 재설정은 그림 영역만 변경하고 Undo',async p=>{const before=await state(p);await open(p);await menu(p).getByRole('menuitem',{name:/스타일에 맞게 다시 설정/}).click();const after=await state(p);eq(after.sheets[0].charts[0].fill,'#123456');eq(after.sheets[0].charts[0].plotFill,undefined);eq(after.sheets[0].cells,before.sheets[0].cells);await p.evaluate(()=>window.tabula.run('undo'));eq(await state(p),before);});
await test('CRTX 저장 창과 저장 bytes·재적용',async p=>{const before=await state(p);await open(p);await menu(p).getByRole('menuitem',{name:/서식 파일로 저장/}).click();await p.waitForFunction(()=>window.__savedBytes?.length);const result=await p.evaluate(()=>({options:window.__saved,bytes:window.__savedBytes}));eq(result.options.length,1);ok(result.options[0].suggestedName.endsWith('.crtx'));eq(result.bytes.slice(0,2),[80,75]);eq(await state(p),before);await open(p);const chooser=p.waitForEvent('filechooser');await menu(p).getByRole('menuitem',{name:/서식 파일 적용/}).click();await(await chooser).setFiles({name:'합성.crtx',mimeType:'application/octet-stream',buffer:Buffer.from(result.bytes)});await p.waitForFunction(()=>document.querySelector('#toast')?.textContent.includes('서식을 적용'));eq((await state(p)).sheets[0].cells,before.sheets[0].cells);eq((await state(p)).sheets[0].charts[0].range,before.sheets[0].charts[0].range);});
await test('영역 삭제 후 Undo는 차트와 원본 보존',async p=>{const before=await state(p);await open(p);await menu(p).getByRole('menuitem',{name:/차트 삭제/}).click();eq((await state(p)).sheets[0].charts.length,0);eq((await state(p)).sheets[0].cells,before.sheets[0].cells);await p.evaluate(()=>window.tabula.run('undo'));eq(await state(p),before);});
await test('3D 메뉴는 3D 차트에서 동작',async p=>{await p.evaluate(()=>{const w=window.tabula.wb();w.transact(()=>w.setSheetProp(0,'charts',w.sheets[0].charts.map(x=>({...x,threeD:true}))));window.tabula.gv().renderObjectsAll();});await open(p);await menu(p).getByRole('menuitem',{name:/3차원 회전/}).click();const d=p.getByRole('dialog',{name:'3차원 회전',exact:true});await d.waitFor();await d.getByRole('spinbutton').first().fill('45');await d.getByRole('button',{name:/확인/}).click();eq((await state(p)).sheets[0].charts[0].view3D.rotX,45);});
await test('보호된 차트는 서식·삭제 차단',async p=>{await p.evaluate(()=>{window.tabula.wb().props={markedFinal:true};});const before=await state(p);await open(p);eq(await menu(p).getByRole('menuitem',{name:/차트 삭제/}).isDisabled(),true);eq(await menu(p).getByRole('menuitem',{name:/스타일에 맞게 다시 설정/}).isDisabled(),true);eq(await state(p),before);});
await test('모바일 메뉴·패널이 화면 안에 표시',async p=>{await open(p);const b=await menu(p).boundingBox();ok(b.x>=0&&b.x+b.width<=391);await menu(p).getByRole('menuitem',{name:/그림 영역 서식/}).click();const d=p.getByRole('dialog',{name:'그림 영역 서식',exact:true});await d.waitFor();const db=await d.boundingBox();ok(db.x>=0&&db.x+db.width<=391);mkdirSync('D:/Codex/Temp/wixel-chart-context',{recursive:true});await p.screenshot({path:'D:/Codex/Temp/wixel-chart-context/mobile.png'});},true);
}finally{await browser.close();}console.log(JSON.stringify({url,checks,results},null,2));if(results.some(r=>!r.ok))process.exitCode=1;
