// 합성 문서의 실제 파일 입력으로 문서 전환·편집·복구와 지연 열기 경쟁을 검사합니다.
// 실제 Safari 기기/메모리 종료는 에뮬레이션하지 않습니다. 원격 쓰기는 모두 차단합니다.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { Workbook } from '../src/workbook.js';
import { writeXlsx } from '../src/xlsx.js';
const pw = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = process.env.WIXEL_URL || 'http://127.0.0.1:5191/';
if (!['localhost','127.0.0.1','[::1]'].includes(new URL(url).hostname)) throw Error('로컬 합성 문서 전용 검사입니다.');
const out = process.env.WIXEL_DOCUMENT_SWITCH_OUT || 'D:/Codex/Temp/wixel-document-switch/source';
const only = process.env.WIXEL_DOCUMENT_SWITCH_FILTER || '';
const engines = (process.env.WIXEL_BROWSER || 'chromium,webkit').split(',');
await mkdir(out,{recursive:true});
const results=[],assets=new Set();let checks=0;
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);};
const ok=(a,m)=>{checks++;assert.ok(a,m);};
const fixture=id=>({sheets:[{name:id+' 원본',cells:{'0,0':{raw:id+' 고유 문서'},'0,1':{raw:id==='A'?'101':'202'},'1,1':{raw:'=B1*2'},'2,2':{raw:'열기 전'}}},{name:id+' 보조',cells:{'0,0':{raw:id+' 보조 시트'}}}]});
const files=Object.fromEntries(['A','B','C'].map(id=>[id,{name:id+'.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(writeXlsx(new Workbook(fixture(id))))}]));
const raf=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const state=p=>p.evaluate(()=>({title:document.title,names:tabula.wb().sheets.map(s=>s.name),marker:tabula.wb().getRaw(0,0,0),edit:tabula.wb().getRaw(0,2,2),undo:tabula.wb().undoStack.length,redo:tabula.wb().redoStack.length,si:tabula.si}));
async function isBook(p,id){await p.waitForFunction(id=>window.tabula?.wb().sheets[0]?.name===id+' 원본'&&!document.querySelector('.load-progress'),id);await raf(p);eq((await state(p)).marker,id+' 고유 문서','문서 고유 값');eq((await state(p)).names,[id+' 원본',id+' 보조'],'문서 시트 목록');}
async function open(p,id){await p.locator('#fileInput').setInputFiles(files[id]);await isBook(p,id);}
async function edit(p,value='B 편집 유지'){await raf(p);eq(await p.locator('.load-progress').count(),0,'최신 문서 편집을 이전 파일 진행 창이 가로막지 않음');await p.evaluate(()=>tabula.selectCell(2,2));await p.locator('#cellEditor').focus();await p.keyboard.press('F2');await p.locator('#cellEditor').fill(value);await p.keyboard.press('Enter');await raf(p);eq((await state(p)).edit,value,'실제 입력 편집 반영');}
async function checkB(p,editValue){const s=await state(p);eq(s.marker,'B 고유 문서','B 문서 유지');eq(s.names,['B 원본','B 보조'],'B 시트 유지');if(editValue!==undefined)eq(s.edit,editValue,'B 편집 유지');}
const tests=[];const test=(name,fn,options={})=>tests.push({name,fn,...options});
test('sequential-edit-undo-redo-sheet',async p=>{await open(p,'A');await edit(p,'A 편집 이력');ok((await state(p)).undo>0,'A 실행 취소 이력 생성');await open(p,'B');eq((await state(p)).undo,0,'문서 전환 시 A 실행 취소 이력 폐기');eq((await state(p)).redo,0,'문서 전환 시 다시 실행 이력 폐기');await edit(p);await checkB(p,'B 편집 유지');await p.evaluate(()=>tabula.run('undo'));await raf(p);await checkB(p,'열기 전');await p.evaluate(()=>tabula.run('undo'));await raf(p);await checkB(p,'열기 전');await p.evaluate(()=>tabula.run('redo'));await raf(p);await checkB(p,'B 편집 유지');await p.evaluate(()=>tabula.switchSheet(1));await raf(p);eq((await state(p)).si,1,'B 보조 시트 이동');await p.evaluate(()=>tabula.switchSheet(0));await raf(p);await checkB(p,'B 편집 유지');});
test('autosave-and-reload',async p=>{await open(p,'A');await edit(p,'A 저장 이력');await open(p,'B');await edit(p);await p.waitForFunction(()=>{const s=JSON.parse(localStorage.getItem('tabula.workbook.v1')||'null');return s?.docName==='B'&&s?.workbook?.sheets?.[0]?.cells?.['2,2']?.raw==='B 편집 유지';});await checkB(p,'B 편집 유지');await p.waitForTimeout(5500);await checkB(p,'B 편집 유지');await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.tabula?.wb());await checkB(p,'B 편집 유지');});
test('background-resume',async p=>{await open(p,'A');await open(p,'B');await edit(p);await p.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));window.dispatchEvent(new Event('blur'));window.dispatchEvent(new Event('focus'));document.dispatchEvent(new Event('visibilitychange'));});await p.waitForTimeout(1700);await checkB(p,'B 편집 유지');});
test('older-read-finishes-last',async p=>{await open(p,'C');await p.evaluate(()=>{window.__fileGate={started:false,released:false};const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='A.xlsx'){window.__fileGate.started=true;await new Promise(r=>window.__releaseFile=()=>{window.__fileGate.released=true;r();});}return original.call(this);};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__fileGate.started);await p.locator('#fileInput').setInputFiles(files.B);await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='B 원본');await edit(p);await p.evaluate(()=>window.__releaseFile());await p.waitForFunction(()=>!document.querySelector('.load-progress'));await raf(p);await checkB(p,'B 편집 유지');await p.waitForTimeout(1700);await checkB(p,'B 편집 유지');});
test('older-read-after-new-workbook',async p=>{await open(p,'C');await p.evaluate(()=>{window.__fileGate={started:false};const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='A.xlsx'){window.__fileGate.started=true;await new Promise(r=>window.__releaseFile=r);}return original.call(this);};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__fileGate.started);await p.evaluate(()=>tabula.newWorkbook());await p.waitForFunction(()=>tabula.wb().sheets[0].name==='Sheet1');await raf(p);eq(await p.locator('.load-progress').count(),0,'새 문서를 이전 파일 진행 창이 가로막지 않음');await p.evaluate(()=>window.__releaseFile());await p.waitForFunction(()=>!document.querySelector('.load-progress'));await raf(p);eq((await state(p)).names,['Sheet1'],'새 통합 문서가 이전 지연 열기로 대체되지 않음');});
test('older-workbook-preparation-finishes-last',async p=>{await open(p,'C');await p.evaluate(()=>{window.__prepareGate={started:false};const proto=tabula.wb().constructor.prototype,original=proto.loadAsync;proto.loadAsync=async function(data,...args){await original.call(this,data,...args);if(data.sheets[0]?.name==='A 원본'){window.__prepareGate.started=true;await new Promise(r=>window.__releasePreparation=r);}};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__prepareGate.started);await p.locator('#fileInput').setInputFiles(files.B);await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='B 원본');await edit(p);await p.evaluate(()=>window.__releasePreparation());await p.waitForFunction(()=>!document.querySelector('.load-progress'));await checkB(p,'B 편집 유지');});
test('older-failed-read-after-latest',async p=>{await open(p,'C');await p.evaluate(()=>{window.__fileGate={started:false};const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='A.xlsx'){window.__fileGate.started=true;await new Promise(r=>window.__releaseFile=r);throw Error('합성 이전 파일 읽기 실패');}return original.call(this);};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__fileGate.started);await p.locator('#fileInput').setInputFiles(files.B);await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='B 원본');await edit(p);await p.evaluate(()=>window.__releaseFile());await p.waitForFunction(()=>!document.querySelector('.load-progress'));await checkB(p,'B 편집 유지');eq(await p.locator('#dialogLayer .dialog').count(),0,'이전 파일의 늦은 오류 안내로 새 문서 작업을 가로막지 않음');});
test('older-read-after-wixel',async p=>{await open(p,'C');await p.evaluate(()=>{window.__fileGate={started:false};const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='A.xlsx'){window.__fileGate.started=true;await new Promise(r=>window.__releaseFile=r);}return original.call(this);};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__fileGate.started);await p.locator('#fileInput').setInputFiles({name:'B.wixel',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({docName:'B',workbook:fixture('B')}))});await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='B 원본');await edit(p);await p.evaluate(()=>window.__releaseFile());await p.waitForFunction(()=>!document.querySelector('.load-progress'));await checkB(p,'B 편집 유지');});
test('three-file-latest-wins',async p=>{await open(p,'C');await p.evaluate(()=>{window.__fileGate={started:false};const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=async function(){if(this.name==='A.xlsx'){window.__fileGate.started=true;await new Promise(r=>window.__releaseFile=r);}return original.call(this);};});await p.locator('#fileInput').setInputFiles(files.A);await p.waitForFunction(()=>window.__fileGate.started);await p.locator('#fileInput').setInputFiles(files.B);await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='B 원본');await p.locator('#fileInput').setInputFiles(files.C);await p.waitForFunction(()=>tabula.wb().sheets[0]?.name==='C 원본');await edit(p,'C 최신 편집');await p.evaluate(()=>window.__releaseFile());await p.waitForFunction(()=>!document.querySelector('.load-progress'));const s=await state(p);eq(s.marker,'C 고유 문서','세 번째 최신 문서 유지');eq(s.edit,'C 최신 편집','세 번째 문서 편집 유지');});
test('same-name-distinct-document-autosave',async p=>{await p.locator('#fileInput').setInputFiles({...files.A,name:'같은이름.xlsx'});await isBook(p,'A');const oldId=await p.evaluate(()=>JSON.parse(localStorage.getItem('tabula.workbook.v1')).docId);await p.locator('#fileInput').setInputFiles({...files.B,name:'같은이름.xlsx'});await isBook(p,'B');const next=await p.evaluate(()=>JSON.parse(localStorage.getItem('tabula.workbook.v1')));ok(next.docId!==oldId,'같은 파일 이름이어도 새 문서 보관 ID');eq(next.docName,'같은이름','파일 이름과 보관 제목 일치');eq(next.workbook.sheets[0].cells['0,0'].raw,'B 고유 문서','보관 내용이 새 B 문서');await edit(p);await p.waitForFunction(()=>JSON.parse(localStorage.getItem('tabula.workbook.v1'))?.workbook?.sheets?.[0]?.cells?.['2,2']?.raw==='B 편집 유지');await p.reload({waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.tabula?.wb());await checkB(p,'B 편집 유지');eq((await state(p)).title,'같은이름 - WIXEL','복구 제목 일치');});
for(const engine of engines){const browser=await pw[engine].launch();try{for(const t of tests){const label=engine+'-'+t.name;if(only&&!label.includes(only))continue;const context=await browser.newContext({viewport:{width:1180,height:820},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1',serviceWorkers:'block'}),p=await context.newPage(),errors=[],writes=[];p.setDefaultTimeout(14000);await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;localStorage.setItem('wixel.mobile-work.v1','on');});await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD'].includes(q.method())){writes.push(u.pathname);return r.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/'))return r.abort();return r.continue();});p.on('pageerror',e=>errors.push(e.message));const start=checks;try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());assets.add(await p.evaluate(()=>[...document.scripts].map(s=>s.getAttribute('src')).find(s=>s?.includes('wixel-'))||'source'));await t.fn(p);if(t.name==='older-read-finishes-last')await p.screenshot({path:out+'/'+label+'.png'});eq(errors,[],'페이지 실행 오류 없음');eq(writes,[],'원격 쓰기 없음');results.push({label,ok:true,checks:checks-start});console.log('OK '+label);}catch(e){results.push({label,ok:false,error:e.message,checks:checks-start,errors,writes,state:await state(p).catch(()=>null)});console.error('NG '+label+': '+e.message);await p.screenshot({path:out+'/'+label+'-failure.png'}).catch(()=>{});}finally{await context.close();}}}finally{await browser.close();}}
const result={url,assets:[...assets],cases:results.length,passed:results.filter(r=>r.ok).length,checks,results};await writeFile(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(result.passed!==result.cases)process.exitCode=1;
