// 합성 이미지와 셀만 사용. 격리 브라우저·메모리 파일 선택기, 외부/API/원격 쓰기 차단.
import assert from 'node:assert/strict';
import { gzipSync } from 'node:zlib';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5191/',out=process.env.WIXEL_IMAGE_EXPORT_OUT||'D:/Codex/Temp/wixel-image-export/source',only=process.env.WIXEL_IMAGE_EXPORT_FILTER||'';
await mkdir(out,{recursive:true});
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();
const results=[],errors=[],writes=[],blocked=[],mockedReads=[];let checks=0,assets=[];
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);},ok=(a,m)=>{checks++;assert.ok(a,m);};
p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());
await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;localStorage.setItem('wixel:version','3.0.0');Object.defineProperty(navigator,'clipboard',{configurable:true,value:{read:async()=>[],readText:async()=>'',write:async()=>{},writeText:async()=>{}}});
  window.__imageCapture={files:[],calls:[],mode:'normal'};const blobs=new Map(),nativeCreate=URL.createObjectURL.bind(URL);URL.createObjectURL=blob=>{const key=nativeCreate(blob);blobs.set(key,blob);return key;};
  const nativeClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.download&&blobs.has(this.href)){window.__imageCapture.files.push({name:this.download,blob:blobs.get(this.href),download:true});return;}return nativeClick.call(this);};
  window.__installPicker=()=>{window.showSaveFilePicker=async options=>{const state=window.__imageCapture;state.calls.push(options);if(state.mode==='abort')throw new DOMException('합성 취소','AbortError');if(state.mode==='error')throw new DOMException('합성 권한 오류','NotAllowedError');if(state.mode==='hold')await new Promise(resolve=>{state.release=resolve;});return{kind:'file',name:options.suggestedName,createWritable:async()=>({write:async blob=>{if(state.mode==='writeError')throw new DOMException('합성 쓰기 실패','QuotaExceededError');state.files.push({name:options.suggestedName,blob});},close:async()=>{state.closed=true;},abort:async()=>{state.aborted=true;}})};};};window.__installPicker();
});
await context.route('**/*',route=>{const q=route.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(u.pathname);return route.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/')){blocked.push(u.pathname);return route.abort();}return route.continue();});
const run=cmd=>p.evaluate(cmd=>window.tabula.run(cmd),cmd),d=()=>p.getByRole('dialog').filter({has:p.locator('[name="imageFormat"]')}),field=name=>d().locator('[name="'+name+'"]');
const state=()=>p.evaluate(()=>{const t=window.tabula,w=t.wb();return{data:w.serialize().sheets.map(({view,zoom,...s})=>s),undo:w.undoStack.length,redo:w.redoStack.length};});
const files=()=>p.evaluate(()=>window.__imageCapture.files.length),calls=()=>p.evaluate(()=>window.__imageCapture.calls.length);
async function select(ids){for(let i=0;i<ids.length;i++)await p.locator('.obj[data-id="'+ids[i]+'"]').first().click({position:{x:25,y:25},modifiers:i?['Control']:[]});}
async function reset(){for(let i=0;i<6;i++)await p.keyboard.press('Escape');for(const b of await p.locator('#dialogLayer .dialog-head button[aria-label="닫기"]').all())await b.click();await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{
  const t=window.tabula,w=t.wb();if(t.mobile().active)t.run('mobileWorkMode');t.selectCell(0,0);const c=document.createElement('canvas');c.width=160;c.height=100;const cx=c.getContext('2d');cx.fillStyle='#ff0000';cx.fillRect(20,20,50,60);cx.fillStyle='#0000ff';cx.fillRect(90,20,50,60);const src=c.toDataURL();
  const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path fill="#2244aa" d="M0 0H40V100H0Z M60 0H100V100H60Z"/></svg>';
  w.restore({sheets:[{name:'그림 저장 합성',cells:{'0,0':{raw:'빨강',style:{fill:'#ff0000',font:'Arial',size:11}},'0,1':{raw:'초록',style:{fill:'#00ff00'}},'0,2':{raw:'파랑',style:{fill:'#0000ff'}},'1,0':{raw:'합성 병합',style:{fill:'#ffff00',bold:true}},'1,2':{raw:'=2+3'},'2,0':{raw:'보존'},'2,2':{raw:'1234.5',style:{numFmt:'custom',code:'#,##0.0'}}},defColW:90,defRowH:30,merges:[{r1:1,c1:0,r2:1,c2:1}],images:[{id:'photo',name:'합성 사진',src,x:80,y:130,w:160,h:100,z:1},{id:'icon',name:'합성 아이콘',src:'data:image/svg+xml;base64,'+btoa(svg),x:520,y:130,w:100,h:100,z:3}],shapes:[{id:'shape',name:'합성 도형',kind:'rect',x:300,y:130,w:160,h:100,fill:'#00ff00',stroke:null,z:2},{id:'group',name:'혼합 그룹',kind:'group',x:700,y:130,w:180,h:100,groupSize:{w:180,h:100},groupItems:[{id:'child-shape',kind:'rect',x:0,y:0,w:80,h:100,fill:'#ff0000',stroke:null},{id:'child-image',kind:'picture',x:90,y:0,w:90,h:100,src}]}]},{name:'다른 합성',cells:{'0,0':{raw:'다른 시트 보존'}}}]});
  t.switchSheet(1);t.switchSheet(0);t.selectCell(0,0);t.gv().setZoom(100);t.gv().layout();t.gv().renderAll();w.undoStack=[];w.redoStack=[];window.__imageCapture={files:[],calls:[],mode:'normal'};window.__installPicker();
});}
async function open(cmd='objectSaveImage',ids=['photo']){if(ids)await select(ids);await run(cmd);await d().waitFor();await p.waitForFunction(()=>{const s=document.querySelector('.image-export-status');return s&& !s.textContent.includes('준비하고');});}
async function configure({format='png',scale='1',background='transparent',name='합성 저장'}={}){await field('imageFormat').selectOption(format);if(await field('imageScale').isEnabled())await field('imageScale').selectOption(scale);if(await field('imageBackground').isEnabled())await field('imageBackground').selectOption(background);await field('imageFilename').fill(name);}
async function save(){const before=await files();await p.waitForFunction(()=>{const s=document.querySelector('.image-export-status');return s&&!s.textContent.includes('준비하고');});await d().getByRole('button',{name:/^저장(?:\s*\(S\))?$/}).click();await p.waitForFunction(before=>window.__imageCapture.files.length>before,before);await d().waitFor({state:'detached'});return saved();}
async function saved(){return p.evaluate(async()=>{const f=window.__imageCapture.files.at(-1),bytes=new Uint8Array(await f.blob.arrayBuffer()),base={name:f.name,type:f.blob.type,size:bytes.length,head:[...bytes.slice(0,12)],download:!!f.download};if(f.blob.type.includes('svg')||f.name.endsWith('.svg')){const text=await f.blob.text(),doc=new DOMParser().parseFromString(text,'image/svg+xml');return{...base,text,embedded:[...doc.querySelectorAll('image')].map(n=>n.getAttribute('href')||n.getAttribute('xlink:href')||'').filter(x=>/^data:image\/svg\+xml/i.test(x)).map(x=>x.includes(';base64,')?atob(x.split(',')[1]):decodeURIComponent(x.slice(x.indexOf(',')+1))),xmlError:!!doc.querySelector('parsererror'),width:doc.documentElement.getAttribute('width'),height:doc.documentElement.getAttribute('height'),viewBox:doc.documentElement.getAttribute('viewBox'),foreign:doc.querySelectorAll('foreignObject').length,texts:[...doc.querySelectorAll('text')].map(n=>n.textContent)};}
 const im=new Image(),src=URL.createObjectURL(f.blob);try{im.src=src;await im.decode();const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d');x.drawImage(im,0,0);const px=x.getImageData(0,0,c.width,c.height).data,colors={red:0,green:0,blue:0,yellow:0,transparent:0,white:0,dark:0};for(let i=0;i<px.length;i+=4){const[r,g,b,a]=px.slice(i,i+4);if(a<10)colors.transparent++;else if(r>230&&g<40&&b<40)colors.red++;else if(g>230&&r<40&&b<40)colors.green++;else if(b>180&&r<70&&g<120)colors.blue++;else if(r>230&&g>230&&b<40)colors.yellow++;else if(r>240&&g>240&&b>240)colors.white++;else if(r<60&&g<60&&b<60)colors.dark++;}return{...base,width:c.width,height:c.height,colors};}finally{URL.revokeObjectURL(src);}
});}
async function commentsFixture(){await p.evaluate(()=>{const t=window.tabula,w=t.wb();w.transact(()=>{w.setSheetProp(0,'merges',[]);w.setInput(0,1,0,'선택하지 않은 중간 셀');w.setComment(0,0,0,'첫 메모');w.setComment(0,2,0,'마지막 메모');});w.undoStack=[];w.redoStack=[];t.selectRange({r1:0,c1:0,r2:2,c2:0});t.gv().renderAll();});}
async function screenshot(name){await p.screenshot({path:out+'/'+name+'.png'});}
async function test(name,fn){if(only&&!name.includes(only))return;try{await reset();await fn();eq(errors,[],'페이지 오류');eq(writes,[],'원격 쓰기');results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message});console.error('NG '+name+': '+e.stack);await screenshot('failure-'+results.length).catch(()=>{});}}
try{
 await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());assets=await p.locator('script[src]').evaluateAll(ns=>ns.map(n=>n.getAttribute('src')));
 await test('그림 우클릭 PNG 저장은 색·투명도·크기와 원본을 보존한다',async()=>{await select(['photo']);const before=await state();await p.locator('.obj[data-id="photo"]').first().click({button:'right',position:{x:25,y:25}});await p.locator('.menu-item').filter({hasText:/^그림으로 저장/}).click();await d().waitFor();await configure();await screenshot('picture-dialog');const f=await save();eq([f.name,f.type,f.width,f.height],['합성 저장.png','image/png',160,100]);ok(f.colors.red>2500&&f.colors.blue>2500&&f.colors.transparent>5000);eq(await calls(),1);eq(await state(),before);});
 await test('도형 SVG는 벡터·텍스트·원본 크기를 보존하고 파일 이름을 정리한다',async()=>{await p.evaluate(()=>{window.tabula.wb().sheets[0].shapes[0].text='벡터 합성';window.tabula.gv().renderObjectsAll();});await select(['shape']);const before=await state();await p.locator('[data-ribbon-tab="objFormat"]').click();await p.locator('#ribbon [data-ribbon-command="objectSaveSvg"]').click();await d().waitFor();await p.waitForFunction(()=>!document.querySelector('.image-export-status')?.textContent.includes('준비하고'));eq(await field('imageFormat').inputValue(),'svg');await configure({format:'svg',name:'벡터:합성'});const f=await save();eq(f.name,'벡터_합성.svg');eq([Number(f.width),Number(f.height)],[160,100]);eq(f.xmlError,false);ok(f.text.includes('<path')||f.text.includes('<rect'));ok(f.text.includes('벡터 합성'));eq(f.foreign,0,'SVG는 foreignObject 의존 없이 열림');eq(await state(),before);});
 await test('SVG 아이콘은 SVG 저장 후에도 원래 벡터 색과 구멍을 유지한다',async()=>{await open('objectSaveSvg',['icon']);await configure({format:'svg',name:'아이콘'});const f=await save();eq(f.xmlError,false);const vector=f.text+' '+f.embedded.join(' ');ok(vector.toLowerCase().includes('#2244aa'));ok(vector.includes('<path'));eq(f.name,'아이콘.svg');});
 await test('래스터 사진에서는 SVG 저장을 지원하지 않는 상태를 명확히 표시한다',async()=>{await select(['photo']);await p.locator('.obj[data-id="photo"]').first().click({button:'right',position:{x:25,y:25}});const item=p.locator('.menu-item').filter({hasText:/^SVG로 저장/});if(await item.count())ok(await item.evaluate(e=>e.classList.contains('disabled')||e.getAttribute('aria-disabled')==='true'));await p.keyboard.press('Escape');await open('objectSaveImage',null);const opt=field('imageFormat').locator('option[value="svg"]');ok(!await opt.count()||await opt.isDisabled(),'벡터 원본이 없는 사진은 SVG 제한');await p.keyboard.press('Escape');eq(await files(),0);});
 await test('JPEG는 흰 배경·실제 JPEG 바이트·2배 픽셀로 저장된다',async()=>{await open();await configure({format:'jpeg',scale:'2',background:'white',name:'사진 JPEG'});const f=await save();eq(f.type,'image/jpeg');eq(f.head.slice(0,2),[255,216]);eq([f.width,f.height],[320,200]);eq(f.colors.transparent,0);ok(f.colors.white>10000);ok(/\.jpe?g$/i.test(f.name));});
 await test('PNG 3배 확대와 흰 배경 선택을 실제 픽셀에 적용한다',async()=>{await open();await configure({scale:'3',background:'white'});const f=await save();eq([f.width,f.height],[480,300]);eq(f.colors.transparent,0);ok(f.colors.white>30000);});
 await test('그림 회전·자르기·효과는 PNG에 반영되고 편집값과 Undo는 바뀌지 않는다',async()=>{await p.evaluate(()=>{const im=window.tabula.wb().sheets[0].images[0];Object.assign(im,{rot:90,crop:{l:.5},shadow:{color:'#000000',opacity:.5,blur:4,x:4,y:4}});window.tabula.gv().renderObjectsAll();});await select(['photo']);const before=await state();await open('objectSaveImage',null);await configure();const f=await save();ok(f.height>f.width,'회전 결과 세로가 더 큼');ok(f.colors.blue>1000);ok(f.colors.red<100,'잘린 왼쪽 빨강 제외');eq(await state(),before);});
 await test('혼합 그룹은 도형과 사진을 빠짐없이 하나의 PNG로 저장한다',async()=>{await select(['group']);const before=await state();await open('objectSaveImage',null);await configure();const f=await save();eq([f.width,f.height],[180,100]);ok(f.colors.red>7000&&f.colors.blue>1000);eq(await state(),before);});
 await test('연결된 그림 안의 외부 IMAGE 셀은 합성 응답을 포함해 독립 PNG로 저장한다',async()=>{const source='https://image-export.invalid/synthetic.png',data=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=100;const x=c.getContext('2d');x.fillStyle='#00ff00';x.fillRect(0,0,80,100);x.fillStyle='#ff00ff';x.fillRect(80,0,80,100);return c.toDataURL();});const handler=route=>{mockedReads.push('synthetic.png');return route.fulfill({status:200,contentType:'image/png',headers:{'access-control-allow-origin':'*'},body:Buffer.from(data.split(',')[1],'base64')});};await context.route(source,handler);try{await p.evaluate(source=>{const t=window.tabula,w=t.wb();w.transact(()=>{w.setInput(0,0,0,'=IMAGE("'+source+'","합성 외부 그림",1)');w.setStyle(0,0,0,{fill:'#ffffff'});w.setRowHeight(0,0,100);w.setColWidth(0,0,160);w.setSheetProp(0,'images',w.sheets[0].images.map(im=>im.id==='photo'?{...im,linked:{sheet:w.sheets[0].name,r1:0,c1:0,r2:0,c2:0}}:im));});w.undoStack=[];w.redoStack=[];t.gv().layout();t.gv().renderAll();},source);await select(['photo']);const before=await state();await open('objectSaveImage',null);await configure();const f=await save();eq([f.width,f.height],[160,100]);ok(f.colors.green>5000,'연결 원본 IMAGE의 초록 픽셀');ok(f.colors.red<50&&f.colors.blue<50,'기존 그림 fallback의 빨강/파랑은 저장하지 않음');eq(await state(),before);ok(mockedReads.length>0,'외부 네트워크 없이 합성 응답 사용');}finally{await context.unroute(source,handler);}});
 await test('Ctrl 다중 선택의 PNG는 전체 선택 경계와 각 개체 색을 보존한다',async()=>{await select(['photo','shape']);const before=await state();await open('objectSaveImage',null);await configure();const f=await save();eq([f.width,f.height],[380,100]);ok(f.colors.red>2500&&f.colors.blue>2500&&f.colors.green>15000);eq(await state(),before);});
 await test('셀 범위 PNG는 병합·계산값·채우기와 원본 행열 크기를 보존한다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:2,c2:2}));const before=await state();const point=await p.evaluate(()=>{const b=window.tabula.gv().clientRect({r1:0,c1:0,r2:0,c2:0});return{x:b.left+b.width/2,y:b.top+b.height/2};});await p.mouse.click(point.x,point.y,{button:'right'});await p.locator('.menu-item').filter({hasText:/^선택 영역을 그림으로 저장/}).click();await d().waitFor();await p.waitForFunction(()=>!document.querySelector('.image-export-status')?.textContent.includes('준비하고'));await configure({name:'선택 영역'});await screenshot('range-dialog');const f=await save();eq([f.width,f.height],[274,94],'270×90 셀 영역과 테두리 보존용 사방 2px');ok(f.colors.red>1500&&f.colors.green>1500&&f.colors.blue>1500&&f.colors.yellow>3000);ok(f.colors.dark>10,'텍스트 실제 렌더');eq(await state(),before);});
 await test('셀 범위 SVG는 수식 결과와 병합 텍스트를 담고 외부 참조를 만들지 않는다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:2,c2:2}));await open('rangeSaveImage',null);await configure({format:'svg',name:'범위 벡터'});const f=await save();eq(f.xmlError,false);eq(f.foreign,0);ok(f.text.includes('합성 병합')&&f.text.includes('1,234.5'),'병합 문자열과 표시 형식');ok(f.texts.some(s=>s==='5'),'수식 대신 표시된 계산 결과');ok(!/href=["']https?:/i.test(f.text));});
 await test('셀 범위 눈금선 옵션은 PNG 픽셀을 변경하고 모델은 그대로 둔다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:4,c1:0,r2:6,c2:2}));const before=await state();await open('rangeSaveImage',null);await configure();await field('imageGridlines').uncheck();const f=await save();await open('rangeSaveImage',null);await configure();await field('imageGridlines').check();const g=await save();eq([g.width,g.height],[f.width,f.height]);ok(g.size!==f.size||g.colors.dark!==f.colors.dark,'눈금선이 실제 출력에 반영');eq(await state(),before);});
 await test('메모가 있는 A1·A3만 고른 비연속 선택은 중간 A2를 저장하지 않는다',async()=>{await commentsFixture();await p.locator('#cellEditor').focus();await p.keyboard.press('Control+Shift+o');eq(await p.evaluate(()=>window.tabula.sel),{r1:0,c1:0,r2:2,c2:0});const before=await state();await run('rangeSaveImage');eq(await d().count(),0,'비연속 범위 저장 창을 열지 않음');ok(/비연속|연속된|떨어져|여러 영역/.test(await p.locator('#toast').innerText()),'지원되지 않는 선택에 대한 안내');eq(await calls(),0);eq(await files(),0);eq(await state(),before);});
 await test('같은 외곽 범위라도 저장 창을 연 뒤 메모 선택으로 바뀌면 저장을 차단한다',async()=>{await commentsFixture();const selection=await p.evaluate(()=>({...window.tabula.sel})),version=await p.evaluate(()=>window.tabula.wb().version),before=await state();await open('rangeSaveImage',null);await configure();await run('selectComments');eq(await p.evaluate(()=>window.tabula.sel),selection,'외곽 범위는 동일');eq(await p.evaluate(()=>window.tabula.wb().version),version,'문서 버전 변경 없는 선택 변화');await d().getByRole('button',{name:/^저장/}).click();await d().getByRole('alert').filter({hasText:/변경|다시/}).waitFor();eq(await calls(),0);eq(await files(),0);eq(await state(),before);});
 await test('초과 크기 범위는 조용히 잘라 저장하지 않고 오류를 알린다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:300,c2:60}));await run('rangeSaveImage');await p.waitForFunction(()=>document.querySelector('[name="imageFormat"]')||document.querySelector('[role="alert"]')||document.querySelector('#toast.show'));if(await d().count()){const saveButton=d().getByRole('button',{name:/^저장/});if(await saveButton.isEnabled())await saveButton.click();}await p.waitForFunction(()=>/크기|범위|픽셀|4096|초과/.test(document.querySelector('#dialogLayer')?.textContent+' '+document.querySelector('#toast')?.textContent));eq(await files(),0);eq(await calls(),0);});
 await test('저장 대화상자의 변경과 취소는 개체·셀·Undo에 영향을 주지 않는다',async()=>{await select(['shape']);const before=await state();await open('objectSaveImage',null);await configure({format:'svg',name:'취소할 이름'});await d().getByRole('button',{name:/^취소/}).click();eq(await state(),before);eq(await files(),0);eq(await calls(),0);});
 await test('파일 선택 취소는 자동 다운로드 없이 원본을 유지한다',async()=>{await open();const before=await state();await configure();await p.evaluate(()=>window.__imageCapture.mode='abort');await d().getByRole('button',{name:/^저장/}).click();await p.waitForFunction(()=>window.__imageCapture.calls.length===1);await p.waitForTimeout(40);eq(await files(),0);eq(await state(),before);});
 await test('파일 선택 또는 쓰기 오류는 자동 다운로드하지 않고 오류를 표시한다',async()=>{for(const mode of ['error','writeError']){await reset();await open();await configure();await p.evaluate(mode=>window.__imageCapture.mode=mode,mode);await d().getByRole('button',{name:/^저장/}).click();const alert=mode==='error'?p.getByRole('dialog',{name:'파일 저장',exact:true}):d().getByRole('alert').filter({hasText:'합성'});await alert.waitFor();ok(/합성|저장하지 않았습니다/.test(await alert.innerText()));eq(await files(),0);if(mode==='writeError')eq(await p.evaluate(()=>window.__imageCapture.aborted),true);await p.keyboard.press('Escape');}});
 await test('열린 저장 창에서 선택·시트·문서가 바뀌면 오래된 대상을 저장하지 않는다',async()=>{for(const change of ['selection','object','sheet','book']){await reset();if(change==='selection'){await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:2,c2:2}));await open('rangeSaveImage',null);}else await open();await configure();await p.evaluate(change=>{const t=window.tabula;if(change==='selection')t.selectCell(2,2);else if(change==='object')t.wb().sheets[0].images[0].w=180;else if(change==='sheet')t.switchSheet(1);else{t.wb().restore({sheets:[{name:'교체 합성',cells:{'0,0':{raw:'새 문서'}}}]});t.switchSheet(0);}},change);if(await d().count())await d().getByRole('button',{name:/^저장/}).click();await p.waitForTimeout(40);eq(await files(),0,change);eq(await calls(),0,change);}});
 await test('파일 선택 지연 중 원본이 바뀌면 완료된 선택기로도 파일을 쓰지 않는다',async()=>{await open();await configure();await p.evaluate(()=>window.__imageCapture.mode='hold');await d().getByRole('button',{name:/^저장/}).click();await p.waitForFunction(()=>!!window.__imageCapture.release);await p.evaluate(()=>{const w=window.tabula.wb();w.transact(()=>w.setInput(0,2,0,'지연 중 수정'));window.__imageCapture.release();});await p.waitForFunction(()=>/변경|취소|다시/.test(document.querySelector('#toast')?.textContent+' '+document.querySelector('#dialogLayer')?.textContent));eq(await files(),0);eq(await p.evaluate(()=>window.tabula.wb().getRaw(0,2,0)),'지연 중 수정');});
 await test('파일 선택 미지원 환경은 이름 확인 후에만 명시적으로 다운로드한다',async()=>{await p.evaluate(()=>{delete window.showSaveFilePicker;});await open();await configure({name:'브라우저 저장'});await d().getByRole('button',{name:/^저장/}).click();const fallback=p.getByRole('dialog',{name:'파일로 저장',exact:true});await fallback.waitFor();eq(await files(),0);await fallback.getByRole('textbox',{name:'파일 이름',exact:true}).fill('확인한 이름.png');await fallback.getByRole('button',{name:'다운로드',exact:true}).click();await p.waitForFunction(()=>window.__imageCapture.files.length>0);const f=await saved();eq(f.name,'확인한 이름.png');eq(f.download,true);eq(f.type,'image/png');eq(await calls(),0);});
 await test('기존 pictureSave 명령은 PNG 직접 저장 호환을 유지한다',async()=>{await select(['photo']);const before=await state();await run('pictureSave');await p.waitForFunction(()=>window.__imageCapture.files.length>0);const f=await saved();eq(f.type,'image/png');ok(f.width>=160&&f.height>=100);eq(await state(),before);});
 await test('홈 복사 화살표에서 선택 영역 그림 저장을 열고 취소할 수 있다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:2,c2:2}));const before=await state();await p.locator('[data-ribbon-tab="home"]').click();await p.locator('#ribbon [data-ribbon-menu="copyExport"] .caret').click();await p.locator('.menu-item').filter({hasText:/^선택 영역을 그림으로 저장/}).click();await d().waitFor();eq(await d().getAttribute('aria-label'),'선택 영역을 그림으로 저장');await d().getByRole('button',{name:/^취소/}).click();eq(await files(),0);eq(await state(),before);});
 await test('보호·최종본과 공개 읽기 전용에서도 원본을 바꾸지 않고 그림으로 저장한다',async()=>{await p.evaluate(()=>{const w=window.tabula.wb();w.sheets[0].protect={on:true,allow:{}};w.props={...w.props,markedFinal:true};});await select(['photo']);let before=await state();await open('objectSaveImage',null);await configure();let f=await save();eq([f.width,f.height],[160,100]);eq(await state(),before);const workbook=await p.evaluate(()=>window.tabula.wb().serialize()),target=url.split('#')[0]+(url.includes('?')?'&':'?')+'imageExportTest=readonly#view='+gzipSync(JSON.stringify({docName:'읽기 전용 합성',workbook,view:{headers:true}})).toString('base64url');try{await p.goto(target,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());await p.locator('.view-bar').waitFor();await select(['photo']);before=await state();await open('objectSaveImage',null);await configure();f=await save();eq([f.width,f.height],[160,100]);eq(await state(),before);eq(await calls(),1);await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:2,c2:2}));}finally{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());}});
 await test('320px 모바일에서 저장 옵션·미리보기·저장·취소에 접근할 수 있다',async()=>{await p.setViewportSize({width:320,height:740});await p.evaluate(()=>{if(!window.tabula.mobile().active)window.tabula.run('mobileWorkMode');});await open();await configure({scale:'1',name:'모바일 저장'});for(const name of ['imageFormat','imageScale','imageBackground','imageFilename']){const n=field(name);await n.scrollIntoViewIfNeeded();const b=await n.boundingBox();ok(b.x>=-1&&b.x+b.width<=321&&b.y>=-1&&b.y+b.height<=741,name+' 입력 접근');}ok(await d().evaluate(e=>e.scrollWidth<=e.clientWidth+2),'가로 넘침 없음');const b=d().getByRole('button',{name:/^저장/});await b.scrollIntoViewIfNeeded();await screenshot('mobile-320');const box=await b.boundingBox();ok(box.x>=0&&box.x+box.width<=321&&box.y+box.height<=741);const f=await save();eq([f.width,f.height],[160,100]);await open();await d().getByRole('button',{name:/^취소/}).click();eq(await d().count(),0);});
}finally{await browser.close();const result={url,assets,cases:results.length,passed:results.filter(r=>r.ok).length,checks,pageErrors:errors,remoteWrites:writes,blockedRequests:blocked,mockedReads,results};await writeFile(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(results.some(r=>!r.ok)||errors.length||writes.length)process.exitCode=1;}
