// 합성 문서/메모리 클립보드만 사용. 실제 iPadOS가 가로챈 키는 데스크톱 WebKit에서 입증할 수 없다.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const pw = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const engine = process.env.WIXEL_BROWSER || 'chromium';
const url = new URL(process.env.WIXEL_URL || 'http://127.0.0.1:5191/');
assert.ok(['chromium','webkit'].includes(engine));
assert.ok(['localhost','127.0.0.1','[::1]'].includes(url.hostname), '합성 검증은 로컬 서버만 사용');
const out = process.env.WIXEL_KEYBOARD_CHECK_OUT || 'D:/Codex/Temp/wixel-keyboard-check/source-' + engine;
await mkdir(out,{recursive:true});
const browser = await pw[engine].launch(), results=[], assets=new Set(); let checks=0;
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);},ok=(v,m)=>{checks++;assert.ok(v,m);};
const dialog = p=>p.getByRole('dialog',{name:'키보드 단축키 확인',exact:true});
const pad = p=>p.locator('[data-keyboard-check-pad]');
const status = (p,key)=>p.locator('[data-keyboard-check-action="Key'+key+'"]');
const state = p=>p.evaluate(()=>({json:JSON.stringify(tabula.wb().serialize()),undo:tabula.wb().undoStack.length,version:tabula.wb().version}));
async function open(p,mobile=true){await p.evaluate(cmd=>tabula.run(cmd),mobile?'mobileTools':'shortcuts');await p.getByRole('button',{name:'키보드 단축키 확인',exact:true}).click();await dialog(p).waitFor();}
async function test(name,action,{width=390,mobile=true}={}) {
 const c=await browser.newContext({viewport:{width,height:844},hasTouch:mobile,isMobile:mobile,serviceWorkers:'block'}),p=await c.newPage(),errors=[],requests=[];
 p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));
 await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(u.origin!==url.origin||u.pathname.startsWith('/api/')||!['GET','HEAD'].includes(q.method())){requests.push({method:q.method(),path:u.origin===url.origin?u.pathname:'external'});return r.fulfill({status:204,body:''});}return r.continue();});
 await c.addInitScript(mobile=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;localStorage.setItem('wixel:version','3.0.0');localStorage.setItem('wixel.mobile-work.v1',mobile?'on':'off');localStorage.setItem('wixel.mobile-keyboard.v1','hardware');window.__clipboardCalls=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{read:async()=>{__clipboardCalls.push('read');return[];},readText:async()=>{__clipboardCalls.push('readText');return'';},write:async()=>{__clipboardCalls.push('write');},writeText:async()=>{__clipboardCalls.push('writeText');}}});const exec=document.execCommand.bind(document);document.execCommand=(cmd,...args)=>{if(/^(copy|cut|paste)$/i.test(cmd)){__clipboardCalls.push(cmd);return true;}return exec(cmd,...args);};},mobile);
 try{await p.goto(url.href,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());for(const s of await p.locator('script[src]').evaluateAll(ns=>ns.map(n=>n.getAttribute('src'))))assets.add(s);await p.evaluate(()=>{const t=tabula,w=t.wb();w.restore({sheets:[{name:'합성 키보드',cells:{'0,0':{raw:'17'},'1,0':{raw:'=A1*2'}}},{name:'전환',cells:{}}]});t.switchSheet(1);t.switchSheet(0);t.selectCell(0,0);w.undoStack=[];w.redoStack=[];});await open(p,mobile);const before=await state(p),requestCount=requests.length;await action(p);eq(await state(p),before,'문서·버전·Undo 불변');eq(await p.evaluate(()=>window.__clipboardCalls),[],'실제 클립보드 API 호출 없음');eq(requests.slice(requestCount),[],'진단 중 네트워크 없음');eq(errors,[],'페이지 오류 없음');results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message,pageErrors:errors});console.error('NG '+name+': '+e.stack);await p.screenshot({path:out+'/failure-'+results.length+'.png'}).catch(()=>{});}finally{await c.close();}
}
try{
await test('모바일 진입·비편집 시험 영역·문자 미기록',async p=>{eq(await pad(p).evaluate(n=>({focus:n===document.activeElement,editable:n.isContentEditable,tag:n.tagName})),{focus:true,editable:false,tag:'DIV'});await p.keyboard.type('secret');const text=await dialog(p).innerText();ok(!text.includes('secret'),'타이핑 내용 미기록');ok((await p.locator('[data-keyboard-check-physical]').innerText()).includes('KeyT'));eq(await status(p,'C').innerText(),'수신 대기');});
await test('Ctrl·Alt·Command 좌우 단독 키 수신과 해제',async p=>{for(const [key,code,label] of [['ControlLeft','ControlLeft','Ctrl'],['AltLeft','AltLeft','Alt/Option'],['MetaRight','MetaRight','Command/Meta'],['ShiftRight','ShiftRight','Shift']]){await p.keyboard.down(key);ok((await p.locator('[data-keyboard-check-physical]').innerText()).includes(code));ok((await p.locator('[data-keyboard-check-modifiers]').innerText()).includes(label+': 켜짐'));await p.keyboard.up(key);ok((await p.locator('[data-keyboard-check-modifiers]').innerText()).includes(label+': 꺼짐'));}eq(await p.locator('.access-key-layer').count(),0,'진단 Alt는 접근키 모드 아님');});
await test('Ctrl·Command 복사/잘라내기/붙여넣기/Undo 실행 차단',async p=>{for(const modifier of ['Control','Meta'])for(const key of ['C','X','V','Z']){await p.keyboard.press(modifier+'+Key'+key);const text=await status(p,key).innerText();ok(text.includes(modifier==='Meta'?'Command/Meta':'Ctrl'));ok(text.includes('기본 조합'));ok(text.includes('실행 안 함'));}eq(await pad(p).evaluate(n=>n===document.activeElement),true);});
await test('Alt+V를 Command/Ctrl로 오인하지 않고 다시 시험',async p=>{await p.keyboard.press('AltLeft+KeyV');const text=await status(p,'V').innerText();ok(text.includes('Alt/Option'));ok(text.includes('다른 조합'));ok(!text.includes('Command/Meta'));await p.keyboard.press('Control+KeyV');ok((await status(p,'V').innerText()).includes('Ctrl + V'));await p.screenshot({path:out+'/keyboard-check-mobile.png'});});
await test('한글 키/legacy 물리 코드·알 수 없는 값 안전 표시',async p=>{const result=await pad(p).evaluate(n=>{const dispatch=opts=>{const e=new KeyboardEvent('keydown',{bubbles:true,cancelable:true,...opts});n.dispatchEvent(e);return e.defaultPrevented;};return [dispatch({key:'ㅊ',code:'KeyC',ctrlKey:true}),dispatch({key:'',keyCode:86,metaKey:true})];});eq(result,[true,true]);ok((await status(p,'C').innerText()).includes('Ctrl + C'));ok((await status(p,'V').innerText()).includes('Command/Meta + V'));ok((await p.locator('[data-keyboard-check-physical]').innerText()).includes('레거시 코드 86'));await pad(p).evaluate(n=>n.dispatchEvent(new KeyboardEvent('keydown',{bubbles:true,cancelable:true,key:'PRIVATE_TYPED_TEXT',code:'PRIVATE_TYPED_CODE'})));const text=await dialog(p).innerText();ok(!text.includes('PRIVATE_'));ok(!text.includes('ㅊ'));});
await test('IME·dead key 미가로채기 및 clipboard 이벤트 차단',async p=>{const before=await p.locator('[data-keyboard-check-physical]').innerText();const result=await pad(p).evaluate(n=>{const events=[new KeyboardEvent('keydown',{key:'Process',code:'KeyC',ctrlKey:true,isComposing:true,keyCode:229,bubbles:true,cancelable:true}),new KeyboardEvent('keydown',{key:'Dead',code:'KeyC',altKey:true,bubbles:true,cancelable:true}),new CompositionEvent('compositionstart',{data:'비공개',bubbles:true,cancelable:true}),new CompositionEvent('compositionend',{data:'비공개',bubbles:true,cancelable:true})];const ime=events.map(e=>{n.dispatchEvent(e);return e.defaultPrevented;});let reads=0;const clip=['copy','cut','paste'].map(type=>{const e=new Event(type,{bubbles:true,cancelable:true});Object.defineProperty(e,'clipboardData',{get:()=>{reads++;return null;}});n.dispatchEvent(e);return e.defaultPrevented;});return{ime,clip,reads};});eq(result,{ime:[false,false,false,false],clip:[true,true,true],reads:0});eq(await p.locator('[data-keyboard-check-physical]').innerText(),before);ok(!(await dialog(p).innerText()).includes('비공개'));});
await test('Tab 링크·닫기·Escape 및 재열기 상태 초기화',async p=>{await p.keyboard.press('Control+KeyC');await p.keyboard.press('Tab');eq(await p.evaluate(()=>document.activeElement.tagName),'A');const links=await dialog(p).locator('a').evaluateAll(ns=>ns.map(n=>({href:n.href,target:n.target,rel:n.rel})));eq(links.length,3);ok(links.every(n=>n.target==='_blank'&&n.rel.includes('noopener')&&n.rel.includes('noreferrer')));for(let i=0;i<3;i++)await p.keyboard.press('Tab');eq(await p.evaluate(()=>document.activeElement.textContent),'닫기');await p.keyboard.press('Enter');eq(await dialog(p).count(),0);await open(p);eq(await status(p,'C').innerText(),'수신 대기');await p.keyboard.press('Escape');eq(await dialog(p).count(),0);});
await test('320px 작은 화면 내용·닫기 경계',async p=>{const rect=await dialog(p).evaluate(n=>{const r=n.getBoundingClientRect(),b=n.querySelector('.dialog-body'),f=n.querySelector('.dialog-foot').getBoundingClientRect();return{x:r.x,right:r.right,bottom:r.bottom,w:innerWidth,h:innerHeight,overflow:b.scrollWidth>b.clientWidth+1,footer:f.bottom};});ok(rect.x>=-1&&rect.right<=rect.w+1);ok(rect.bottom<=rect.h+1&&rect.footer<=rect.h+1);eq(rect.overflow,false);await p.screenshot({path:out+'/keyboard-check-320.png'});},{width:320});
await test('데스크톱 도움말 진입과 정상 닫기',async p=>{await p.keyboard.press('Control+KeyV');ok((await status(p,'V').innerText()).includes('기본 조합'));await dialog(p).locator('.dialog-foot button').click();eq(await dialog(p).count(),0);},{width:1280,mobile:false});
}finally{await browser.close();const summary={url:url.href,engine,assets:[...assets],cases:results.length,passed:results.filter(r=>r.ok).length,checks,scope:'Synthetic workbook and mocked clipboard; Playwright desktop Chromium/WebKit, not physical iPadOS/Bluetooth or OS-swallowed keys.',results};await writeFile(out+'/result.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));if(results.some(r=>!r.ok))process.exitCode=1;}
