// 모바일 레이아웃/visualViewport 축소 모의. 실제 모바일 IME·터치 기기 인증 검사가 아님.
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5180/',browser=await chromium.launch(),results=[];
const filter=process.env.WIXEL_MOBILE_POPUP_FILTER;
const run=(p,cmd)=>p.evaluate(cmd=>window.tabula.run(cmd),cmd);
async function viewport(p,box){await p.evaluate(box=>{window.__mobilePopupViewport=box;for(const[k,v]of Object.entries({vw:box.width,vh:box.height,top:box.top,left:box.left}))document.documentElement.style.setProperty('--mobile-'+k,v+'px');window.visualViewport.dispatchEvent(new Event('resize'));window.dispatchEvent(new Event('resize'));},box);await p.waitForTimeout(80);}
async function inside(p,locator,label){await locator.waitFor();const b=await locator.boundingBox(),v=await p.evaluate(()=>window.__mobilePopupViewport||{left:0,top:0,width:innerWidth,height:innerHeight});assert.ok(b&&b.x>=v.left-1&&b.y>=v.top-1&&b.x+b.width<=v.left+v.width+1&&b.y+b.height<=v.top+v.height+1,label+': '+JSON.stringify({b,v}));}
async function usable(p,locator,label){await locator.scrollIntoViewIfNeeded();await inside(p,locator,label);assert.equal(await locator.isEnabled(),true,label+' 활성');}
async function test(width,name,fn){if(filter&&!name.includes(filter))return;const ctx=await browser.newContext({viewport:{width,height:760},hasTouch:true}),p=await ctx.newPage(),errors=[],writes=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(q.method());return r.abort();}return u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?r.continue():r.abort();});try{await ctx.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>'',writeText:async()=>{}}});for(const[k,from]of Object.entries({width:'width',height:'height',offsetTop:'top',offsetLeft:'left'})){const v=visualViewport[k];Object.defineProperty(visualViewport,k,{configurable:true,get:()=>window.__mobilePopupViewport?.[from]??v});}});await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());await p.evaluate(()=>{document.body.classList.add('mobile-work-mode');const t=window.tabula,w=t.wb(),cells={};[['지역','부서','매출'],['서울','영업','100'],['부산','개발','200'],['대구','영업','300']].forEach((row,r)=>row.forEach((raw,c)=>cells[r+','+c]={raw}));w.restore({sheets:[{name:'모바일 합성',cells}]});w.undoStack=[];w.redoStack=[];t.gv().layout();t.gv().renderAll();t.selectCell(0,0);});await viewport(p,{width,height:760,top:0,left:0});await fn(p,width);assert.deepEqual(errors,[],'페이지 오류');assert.deepEqual(writes,[],'원격 쓰기');results.push({width,name,ok:true});console.log('OK '+width+' '+name);}catch(e){results.push({width,name,ok:false,error:e.message,errors,writes});console.error('NG '+width+' '+name+': '+e.stack);}finally{await ctx.close();}}
const d=(p,name)=>p.getByRole('dialog',{name,exact:true});
async function chart(p){await p.evaluate(()=>{const t=window.tabula;t.selectRange({r1:0,c1:0,r2:3,c2:2});t.run('chartColumn');});}
async function pivot(p){await p.evaluate(()=>{const t=window.tabula,w=t.wb();w.transact(()=>{w.addSheet('피벗 합성');w.setSheetProp(1,'pivot',{name:'모바일피벗',source:'모바일 합성',range:{r1:0,c1:0,r2:3,c2:2},rows:['지역'],cols:[],values:[{field:'매출',agg:'sum'}],top:0,left:0});});t.switchSheet(1);t.run('pivotRefresh');t.selectCell(1,0);});}
try{for(const width of [320,390]){
await test(width,'셀 서식 6탭과 확인·취소 접근',async p=>{await run(p,'formatCells');const dialog=d(p,'셀 서식');await inside(p,dialog,'셀 서식');for(const name of ['표시 형식','맞춤','글꼴','테두리','채우기','보호']){const tab=dialog.getByRole('tab',{name,exact:true});await usable(p,tab,name+'탭');await tab.click();const inputs=dialog.locator('.fc-page input:visible,.fc-page select:visible');if(await inputs.count())await usable(p,inputs.last(),name+' 입력');}await usable(p,dialog.getByRole('button',{name:'취소',exact:true}),'취소');await dialog.getByRole('button',{name:'취소',exact:true}).click();await run(p,'formatCells');await usable(p,d(p,'셀 서식').getByRole('button',{name:'확인',exact:true}),'확인');await d(p,'셀 서식').getByRole('button',{name:'확인',exact:true}).click();});
await test(width,'찾기 바꾸기 모델리스 입력·옵션·닫기',async p=>{await run(p,'replace');const dialog=d(p,'찾기 및 바꾸기');await inside(p,dialog,'찾기창');const input=dialog.getByRole('textbox',{name:'찾을 내용',exact:true});await usable(p,input,'찾을 내용');await input.fill('서울');await dialog.getByRole('button',{name:'옵션 >>',exact:true}).click();await usable(p,dialog.getByRole('checkbox',{name:'대/소문자 구분',exact:true}),'대소문자');await usable(p,dialog.getByRole('button',{name:'닫기',exact:true}).last(),'닫기');await dialog.getByRole('button',{name:'닫기',exact:true}).last().click();});
await test(width,'필터 검색·선택·적용 버튼 접근',async p=>{await run(p,'toggleFilter');await p.locator('#cellEditor').focus();await p.keyboard.press('Alt+ArrowDown');const menu=p.locator('.filter-menu'),outer=p.locator('#menuLayer > .menu').last();await inside(p,outer,'필터 메뉴');await usable(p,menu.getByRole('searchbox'),'필터 검색');await menu.getByRole('searchbox').fill('서울');await usable(p,menu.getByRole('button',{name:'확인',exact:true}),'필터 확인');await menu.getByRole('button',{name:'확인',exact:true}).click();assert.deepEqual(await p.evaluate(()=>window.tabula.wb().sheets[0].filter.criteria[0]),['서울']);});
await test(width,'우클릭 미니 도구 및 하위 메뉴 끝 항목 접근',async p=>{await p.locator('#cellEditor').focus();await p.keyboard.press('Shift+F10');const menu=p.locator('#menuLayer > .menu[data-level="0"]');await inside(p,menu,'우클릭 메뉴');await inside(p,p.locator('.context-mini-toolbar'),'미니 도구');const sub=menu.getByRole('menuitem',{name:/숨기기 및 숨기기 취소/});await sub.scrollIntoViewIfNeeded();await sub.click();const child=p.locator('#menuLayer > .menu[data-level="1"]');await inside(p,child,'하위 메뉴');await usable(p,child.getByRole('menuitem').last(),'하위 끝 항목');await usable(p,child.getByRole('button',{name:'이전 메뉴',exact:true}),'이전 메뉴');await child.getByRole('button',{name:'이전 메뉴',exact:true}).click();await menu.waitFor();await p.keyboard.press('Escape');assert.equal(await menu.count(),0);});
await test(width,'차트 종류 검색·견본·확인 접근',async p=>{await chart(p);await run(p,'chartChangeType');const dialog=d(p,'차트 종류 변경');await inside(p,dialog,'차트 갤러리');const search=dialog.getByRole('searchbox',{name:'차트 종류 검색'});await usable(p,search,'차트 검색');await search.fill('꺾은선');const chip=dialog.locator('.cg-sub:visible').first();await usable(p,chip,'차트 견본');await chip.click();await usable(p,dialog.getByRole('button',{name:'확인',exact:true}),'차트 확인');await dialog.getByRole('button',{name:'확인',exact:true}).click();assert.equal(await p.evaluate(()=>window.tabula.wb().sheets[0].charts[0].type),'line');});
await test(width,'차트 서식과 키보드 viewport 축소·복원',async(p,width)=>{await chart(p);await run(p,'chartFormat');const dialog=d(p,'차트 서식');await inside(p,dialog,'차트 서식');const picker=dialog.getByRole('combobox',{name:'서식을 지정할 차트 요소'});await usable(p,picker,'계열 선택');await picker.selectOption({label:'차트 제목'});const input=dialog.locator('input[type=text]:visible').first();if(await input.count())await input.focus();await viewport(p,{width,height:330,top:68,left:0});await inside(p,dialog,'키보드 모의 차트창');if(await input.count())await usable(p,input,'키보드 모의 제목');await usable(p,dialog.locator('.dialog-head button'),'키보드 모의 닫기');await p.screenshot({path:'D:/Codex/Temp/wixel-mobile-popup-'+width+'.png'});await viewport(p,{width,height:760,top:0,left:0});await inside(p,dialog,'복원 차트창');await dialog.locator('.dialog-head button').click();});
await test(width,'피벗 필드 패널 검색·영역·닫기 및 격자 폭',async p=>{await pivot(p);if(!await p.locator('#pivotPane').count())await run(p,'pivotFieldList');const pane=p.locator('#pivotPane');await inside(p,pane,'피벗 패널');await usable(p,pane.getByRole('searchbox'),'피벗 검색');await pane.getByRole('searchbox').fill('매출');const gridWidth=await p.locator('#gridScroll').evaluate(e=>e.getBoundingClientRect().width);assert.ok(gridWidth>200,'격자 폭 '+gridWidth);await usable(p,pane.locator('.pp-head button'),'피벗 닫기');await pane.locator('.pp-head button').click();assert.equal(await p.locator('#pivotPane').isVisible(),false);});
await test(width,'선택 붙여넣기 12옵션과 작은 키보드 확인·취소',async(p,width)=>{await p.evaluate(()=>{const t=window.tabula;t.selectRange({r1:1,c1:0,r2:2,c2:1});t.run('copy');t.selectCell(5,0);});await run(p,'pasteSpecial');const dialog=d(p,'선택하여 붙여넣기');await inside(p,dialog,'선택 붙여넣기');for(const radio of await dialog.locator('input[name=psWhat]').all()){await usable(p,radio,'붙여넣기 옵션');await radio.check();}await viewport(p,{width,height:320,top:50,left:0});await inside(p,dialog,'작은 붙여넣기');await usable(p,dialog.getByRole('button',{name:'취소',exact:true}),'붙여넣기 취소');await dialog.getByRole('button',{name:'취소',exact:true}).click();assert.equal(await p.evaluate(()=>window.tabula.wb().getValue(0,5,0)),null);});
await test(width,'표 만들기 입력·확인·실행 취소',async p=>{await run(p,'createTable');const dialog=d(p,'표 만들기');await inside(p,dialog,'표 만들기');await usable(p,dialog.locator('input[type=text]').first(),'표 범위');await usable(p,dialog.getByRole('button',{name:'확인',exact:true}),'표 확인');await dialog.getByRole('button',{name:'확인',exact:true}).click();assert.equal(await p.evaluate(()=>window.tabula.wb().sheets[0].tables.length),1);await run(p,'undo');assert.equal(await p.evaluate(()=>window.tabula.wb().sheets[0].tables.length),0);});
await test(width,'피벗 옵션 모든 범주·입력·취소 접근',async p=>{await pivot(p);await run(p,'pivotOptions');const dialog=d(p,'피벗 테이블 옵션');await inside(p,dialog,'피벗 옵션');for(const tab of await dialog.locator('.opt-tabs button').all()){await usable(p,tab,'피벗 범주');await tab.click();const control=dialog.locator('.opt-page input:visible,.opt-page select:visible').last();if(await control.count())await usable(p,control,'피벗 옵션 입력');}await usable(p,dialog.getByRole('button',{name:'취소',exact:true}),'피벗 옵션 취소');await dialog.getByRole('button',{name:'취소',exact:true}).click();});
await test(width,'파일 메뉴 모든 범주·내용·뒤로 및 키보드 축소',async(p,width)=>{await run(p,'backstage');const stage=p.locator('.backstage'),nav=stage.getByRole('navigation',{name:'파일 메뉴'}),main=stage.locator('.backstage-main');await inside(p,stage,'시작 화면');await p.screenshot({path:'D:/Codex/Temp/wixel-mobile-home-'+width+'.png'});for(const key of ['new','open','templates','storage','share','info']){const button=nav.locator('[data-page="'+key+'"]');await usable(p,button,'파일 메뉴 '+key);await button.click();const controls=main.locator('button:visible,input:visible,select:visible,a:visible');for(const item of await controls.all()){await item.scrollIntoViewIfNeeded();await inside(p,item,'파일 '+key+' 조작');}}await viewport(p,{width,height:330,top:65,left:0});await inside(p,stage,'키보드 시작 화면');await usable(p,nav.locator('.back'),'작업 화면 복귀');await nav.locator('.back').click();assert.equal(await stage.count(),0);await run(p,'backstage');await p.keyboard.press('Escape');assert.equal(await stage.count(),0);});
await test(width,'인쇄 미리보기 페이지·인쇄·PDF·닫기 접근',async(p,width)=>{await p.evaluate(()=>{window.__nativePrint=0;window.print=()=>window.__nativePrint++;const t=window.tabula,w=t.wb();w.transact(()=>{for(let r=4;r<100;r++)w.setInput(0,r,0,String(r));});t.gv().renderAll();});await run(p,'print');const dialog=d(p,'인쇄 미리보기');await inside(p,dialog,'인쇄 미리보기');await p.screenshot({path:'D:/Codex/Temp/wixel-mobile-print-'+width+'.png'});for(const button of await dialog.locator('button:visible').all()){await button.scrollIntoViewIfNeeded();await inside(p,button,'인쇄 조작');}const next=dialog.getByRole('button',{name:'다음 인쇄 페이지'}),prev=dialog.getByRole('button',{name:'이전 인쇄 페이지'});assert.equal(await next.isEnabled(),true);await next.click();assert.equal(await prev.isEnabled(),true);await prev.click();const print=dialog.getByRole('button',{name:'인쇄',exact:true});await usable(p,print,'인쇄 버튼');await print.click();assert.equal(await p.evaluate(()=>window.__nativePrint),1);const download=p.waitForEvent('download');await dialog.getByRole('button',{name:'PDF 파일 저장',exact:true}).click();const pdf=await download;assert.ok(pdf.suggestedFilename().endsWith('.pdf'));await viewport(p,{width,height:310,top:80,left:0});await inside(p,dialog,'작은 인쇄창');await usable(p,dialog.locator('.dialog-foot').getByRole('button',{name:'닫기',exact:true}),'인쇄 닫기');await dialog.locator('.dialog-foot').getByRole('button',{name:'닫기',exact:true}).click();assert.equal(await dialog.count(),0);});
await test(width,'열린 메뉴가 키보드 viewport 이동·축소에 재배치',async(p,width)=>{await p.evaluate(()=>window.tabula.openNamedMenu('fillColor',{x:280,y:690}));const menu=p.locator('#menuLayer > .menu').last();await inside(p,menu,'색 메뉴');await viewport(p,{width:width-20,height:270,top:100,left:10});await inside(p,menu,'키보드 모의 색 메뉴');const last=menu.locator('.menu-item').last();await usable(p,last,'색 메뉴 마지막');await p.keyboard.press('Escape');});
}}finally{await browser.close();console.log(JSON.stringify({url,simulation:'Chromium viewport/visualViewport; actual mobile keyboard not tested',total:results.length,good:results.filter(x=>x.ok).length,bad:results.filter(x=>!x.ok).length,results},null,2));if(results.some(x=>!x.ok))process.exitCode=1;}
