// Synthetic grouping regression. Private documents and network writes are blocked.
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5180/',browser=await chromium.launch(),results=[];
const run=(p,cmd,value)=>p.evaluate(({cmd,value})=>window.tabula.run(cmd,value),{cmd,value});
const model=p=>p.evaluate(()=>structuredClone({shapes:window.tabula.wb().sheets[0].shapes,images:window.tabula.wb().sheets[0].images}));
async function select(p,ids){for(let i=0;i<ids.length;i++)await p.locator(`.obj[data-id="${ids[i]}"]`).first().click({position:{x:35,y:30},modifiers:i?['Control']:[]});}
async function group(p,ids=['ga','gb','gp']){await select(p,ids);await run(p,'objGroup');const m=await model(p),g=m.shapes.find(s=>s.kind==='group');assert.ok(g,'그룹 생성');return g;}
async function test(name,fn){const c=await browser.newContext({viewport:{width:1500,height:1000}}),p=await c.newPage(),errors=[],writes=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await c.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(q.method());return r.abort();}return u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?r.continue():r.abort();});try{await c.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;});await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());await p.evaluate(()=>{const t=window.tabula,w=t.wb(),canvas=document.createElement('canvas');canvas.width=120;canvas.height=80;const ctx=canvas.getContext('2d');ctx.fillStyle='#009999';ctx.fillRect(0,0,120,80);w.restore({sheets:[{name:'그룹 합성',cells:{'0,0':{raw:'보존'}},shapes:[{id:'ga',name:'첫 도형',kind:'rect',x:100,y:100,w:140,h:90,fill:'#4472c4',stroke:'#223366',text:'첫 도형',color:'#ffffff',z:1},{id:'gb',name:'둘째 도형',kind:'ellipse',x:280,y:150,w:140,h:90,fill:'#ed7d31',text:'둘째 도형',color:'#ffffff',z:2}],images:[{id:'gp',name:'그림',x:460,y:100,w:140,h:90,src:canvas.toDataURL(),opacity:.7,border:'#112233',borderW:2,radius:8,shadow:{dx:3,dy:4,blur:5,color:'#000000',opacity:.4},crop:{l:.1},z:3}]}]});t.switchSheet(0);t.selectCell(0,0);t.gv().renderAll();w.undoStack=[];w.redoStack=[];});await fn(p);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.equal(await p.evaluate(()=>window.tabula.wb().getRaw(0,0,0)),'보존');results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message,errors,writes});console.error('NG '+name+' '+e.stack);}finally{await c.close();}}
try{
await test('Ctrl멀티선택그룹화·그림효과·한번UndoRedo',async p=>{const before=await model(p),g=await group(p);assert.equal(g.groupItems.length,3);assert.equal((await model(p)).images.length,0);const svg=await p.locator(`.obj[data-id="${g.id}"]`).first().innerHTML();assert.match(svg,/첫 도형/);assert.match(svg,/둘째 도형/);assert.match(svg,/opacity="0.7"/);assert.match(svg,/stroke="#112233"/);assert.match(svg,/feDropShadow/);assert.equal(await p.evaluate(()=>window.tabula.wb().undoStack.length),1);await run(p,'undo');assert.deepEqual(await model(p),before);await run(p,'redo');assert.equal((await model(p)).shapes[0].kind,'group');});
await test('그룹크기·회전·대칭해제와Undo',async p=>{let g=await group(p);await run(p,'objW',g.w*1.5);await run(p,'objH',g.h*1.5);await run(p,'objRot',90);await p.evaluate(()=>{const t=window.tabula,w=t.wb(),g=w.sheets[0].shapes[0];w.transact(()=>w.setSheetProp(0,'shapes',[{...g,flip:true}]));t.gv().renderObjectsAll();});g=(await model(p)).shapes[0];assert.equal(g.rot,90);assert.equal(g.flip,true);await run(p,'objUngroup');const m=await model(p);assert.equal(m.shapes.length,2);assert.equal(m.images.length,1);assert.ok(m.shapes.every(s=>Math.abs(s.w-210)<1));assert.ok(m.shapes.every(s=>s.rot===90&&s.flip===true));assert.equal(m.images[0].opacity,.7);assert.equal(m.images[0].border,'#112233');await run(p,'undo');assert.equal((await model(p)).shapes[0].kind,'group');await p.screenshot({path:process.env.WIXEL_GROUP_SCREENSHOT||'D:/Codex/Temp/wixel-object-group.png'});});
await test('마우스모서리resize와해제좌표유지',async p=>{const g=await group(p,['ga','gb']);const handle=p.locator(`.obj[data-id="${g.id}"] .ch-h.se`).first(),b=await handle.boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(b.x+b.width/2+100,b.y+b.height/2+50,{steps:8});await p.mouse.up();const resized=(await model(p)).shapes.find(s=>s.kind==='group');assert.ok(resized.w>g.w+50);assert.deepEqual(resized.groupSize,g.groupSize);await run(p,'objUngroup');const m=await model(p);assert.equal(m.shapes.length,2);assert.ok(m.shapes[1].x>280);assert.ok(m.shapes[0].w>140);});
await test('선택창Ctrl다중선택그룹',async p=>{await run(p,'selectionPane');const rows=p.locator('.selpane-row');await rows.filter({hasText:'첫 도형'}).click();await rows.filter({hasText:'둘째 도형'}).click({modifiers:['Control']});await run(p,'objGroup');assert.equal((await model(p)).shapes[0].groupItems.length,2);});
await test('보호된개체그룹화와해제차단',async p=>{await select(p,['ga','gb']);await p.evaluate(()=>window.tabula.wb().setSheetProp(0,'protect',{on:true,allow:{}}));const before=await model(p);await run(p,'objGroup');assert.deepEqual(await model(p),before);await p.evaluate(()=>window.tabula.wb().setSheetProp(0,'protect',null));await run(p,'objGroup');assert.equal((await model(p)).shapes[0].kind,'group');await p.evaluate(()=>window.tabula.wb().setSheetProp(0,'protect',{on:true,allow:{}}));const grouped=await model(p);await run(p,'objUngroup');assert.deepEqual(await model(p),grouped);});
await test('중첩그룹해제는한단계만해제',async p=>{const g=await group(p,['ga','gb']);await group(p,[g.id,'gp']);let m=await model(p);assert.equal(m.shapes[0].groupItems.filter(x=>x.kind==='group').length,1);await run(p,'objUngroup');m=await model(p);assert.equal(m.shapes.length,1);assert.equal(m.shapes[0].kind,'group');assert.equal(m.images.length,1);});
}finally{await browser.close();}console.log(JSON.stringify({total:results.length,passed:results.filter(x=>x.ok).length,results},null,2));if(results.some(x=>!x.ok))process.exitCode=1;
