// 미디어 검색·미리보기·삽입. 공급자 응답/파일은 합성, 키/사용자 문서/원격 쓰기 없음.
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5191/', origin=new URL(url).origin;
const browser=await chromium.launch(),results=[];
const gif=Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64');
const cc='https://creativecommons.org/licenses/by/4.0/';
const dlg=p=>p.getByRole('dialog',{name:'온라인 그림',exact:true});
const images=p=>p.evaluate(()=>structuredClone(tabula.wb().sheets[0].images));
const snapshot=p=>p.evaluate(()=>JSON.stringify(tabula.wb().serialize()));
const settled=p=>p.waitForFunction(()=>{const g=document.querySelector('.online-grid');return g&&!g.hasAttribute('aria-busy')&&!document.querySelector('.online-status')?.textContent.includes('검색 중');});
async function open(p,kind='image'){if(kind==='image'){await p.evaluate(()=>tabula.openNamedMenu('picture',{x:120,y:120}));await p.getByRole('menuitem',{name:'온라인 그림...',exact:true}).click();}else await p.evaluate(k=>tabula.run(k==='gif'?'insertGif':'insertVideo'),kind);await dlg(p).waitFor();assert.equal(await dlg(p).getByLabel('미디어 종류',{exact:true}).inputValue(),kind);}
async function search(p,source='wikimedia'){await dlg(p).getByLabel('검색 사이트',{exact:true}).selectOption(source);await dlg(p).getByRole('searchbox',{name:'그림 검색어',exact:true}).fill('합성');await dlg(p).getByRole('button',{name:'검색',exact:true}).click();await settled(p);}
async function insert(p){await dlg(p).getByRole('button',{name:'삽입',exact:true}).click();}
async function test(name,fn){
 if(process.env.MEDIA_TEST_FILTER&&!name.includes(process.env.MEDIA_TEST_FILTER))return;
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage(),errors=[],writes=[],external=[];
 const net={configured:false,requests:[],tracks:0,failImage:false};p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
 await context.route('**/*',async r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(q.method());return r.abort();}
  if(u.hostname==='fixture.test'){if(u.pathname.endsWith('.webm'))return r.fulfill({contentType:'video/webm',body:net.video,headers:{'access-control-allow-origin':'*'}});if(u.pathname.endsWith('.gif'))return r.fulfill({contentType:'image/gif',body:gif,headers:{'access-control-allow-origin':'*'}});return r.fulfill({status:net.failImage?500:200,contentType:'image/png',body:net.png,headers:{'access-control-allow-origin':'*'}});}
  if(u.origin===origin&&u.pathname==='/api/media/track'){net.tracks++;return r.fulfill({json:{ok:true}});}
  if(u.origin===origin&&u.pathname==='/api/media/search'){
   net.requests.push({source:u.searchParams.get('source'),kind:u.searchParams.get('type'),headers:q.headers()});const s=u.searchParams.get('source'),kind=u.searchParams.get('type');
   if(!net.configured)return r.fulfill({json:{status:'unconfigured',items:[],hasMore:false,message:s+' 서버 API 키 설정 필요'}});
   return r.fulfill({json:{status:'ok',hasMore:false,items:[{id:s+'1',title:s+' 합성',kind,full:kind==='video'?'https://fixture.test/movie.webm':'https://fixture.test/full.png',thumb:'https://fixture.test/poster.png',poster:'https://fixture.test/poster.png',mime:kind==='video'?'video/webm':'image/png',credit:'합성 작가 / '+s,page:'https://fixture.test/source',license:s+' 라이선스',licenseUrl:'https://fixture.test/license',trackId:s==='unsplash'?'abc-12':undefined,source:s}]}});
  }
  if(u.hostname==='commons.wikimedia.org'){
   const video=u.searchParams.get('prop')==='videoinfo',isGif=u.searchParams.get('gsrsearch').includes('filemime:image/gif');net.requests.push({source:'wikimedia',kind:video?'video':isGif?'gif':'image'});
   const ii={mime:video?'video/webm':isGif?'image/gif':'image/png',url:video?'https://fixture.test/movie.webm':isGif?'https://fixture.test/original.gif':'https://fixture.test/full.png',thumburl:'https://fixture.test/poster.png',width:80,height:60,duration:.4,descriptionurl:'https://fixture.test/source',extmetadata:{License:{value:'cc-by'},LicenseUrl:{value:cc},LicenseShortName:{value:'CC BY 4.0'},Artist:{value:'합성 작가'}},...(video?{derivatives:[{type:'video/webm',src:'https://fixture.test/movie.webm',width:80,height:60}]}:{})};
   return r.fulfill({json:{query:{pages:{1:{pageid:1,index:1,title:video?'File:합성 영상':isGif?'File:합성 GIF':'File:합성 그림',[video?'videoinfo':'imageinfo']:[ii]}}}},headers:{'access-control-allow-origin':'*'}});
  }
  if(u.hostname==='api.openverse.org')return r.fulfill({json:{results:[],page_count:1},headers:{'access-control-allow-origin':'*'}});
  if(u.hostname==='api.inaturalist.org')return r.fulfill({json:{results:[],total_results:0},headers:{'access-control-allow-origin':'*'}});
  if(u.hostname==='images-api.nasa.gov')return r.fulfill({json:{collection:{items:[],metadata:{total_hits:0}}},headers:{'access-control-allow-origin':'*'}});
  if(u.origin===origin&&!u.pathname.startsWith('/api/'))return r.continue();if(u.origin===origin&&u.pathname==='/api/health')return r.fulfill({status:503,json:{ok:false}});external.push(u.href);return r.abort();
 });
 try{await context.addInitScript(()=>{window.WIXEL_SKIP_START=true;window.TABULA_STATIC=true;});await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());
  const media=await p.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=80;canvas.height=60;const x=canvas.getContext('2d');x.fillStyle='#4472c4';x.fillRect(0,0,80,60);const png=canvas.toDataURL();const stream=canvas.captureStream(10),rec=new MediaRecorder(stream,{mimeType:'video/webm'}),parts=[];rec.ondataavailable=e=>parts.push(e.data);const done=new Promise(resolve=>rec.onstop=resolve);rec.start();await new Promise(resolve=>setTimeout(resolve,400));rec.stop();await done;stream.getTracks().forEach(t=>t.stop());const bytes=new Uint8Array(await new Blob(parts,{type:'video/webm'}).arrayBuffer());return{png,video:Array.from(bytes)};});net.png=Buffer.from(media.png.split(',')[1],'base64');net.video=Buffer.from(media.video);
  await p.evaluate(()=>{const t=tabula,w=t.wb();w.restore({sheets:[{name:'미디어 합성',cells:{'0,0':{raw:'보존'},'0,1':{raw:'=1+1'}}}]});w.undoStack=[];w.redoStack=[];t.gv().layout();t.gv().renderAll();t.selectCell(2,2);});
  await fn(p,net);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.deepEqual(external,[]);results.push({name,ok:true});console.log('OK '+name);
 }catch(e){results.push({name,ok:false,error:e.message,errors,writes,external});console.error('NG '+name+': '+e.stack);}finally{await context.close();}
}
try{
 await test('7개 공급자·3종류·키미설정 안내/검색사이트링크/설정 도움말',async p=>{await open(p);assert.equal(await dlg(p).getByLabel('검색 사이트',{exact:true}).locator('option').count(),8);assert.equal(await dlg(p).getByLabel('미디어 종류',{exact:true}).locator('option').count(),3);await search(p,'unsplash');assert.equal(await dlg(p).locator('.online-card').count(),0);assert.match(await dlg(p).locator('.online-availability').innerText(),/API 키 설정/);assert.match(await dlg(p).getByRole('link',{name:'사이트에서 검색'}).getAttribute('href'),/^https:\/\/unsplash.com\/s\/photos\//);await dlg(p).getByRole('button',{name:'검색 사이트 설정'}).click();assert.match(await p.getByRole('dialog',{name:'추가 검색 사이트 설정',exact:true}).innerText(),/UNSPLASH_ACCESS_KEY[\s\S]*PEXELS_API_KEY[\s\S]*PIXABAY_API_KEY/);});
 await test('GIF 명령·원본미리보기·원본 바이트 삽입·Undo',async p=>{const before=await snapshot(p);await open(p,'gif');await search(p);await dlg(p).getByRole('button',{name:'합성 GIF 미리보기',exact:true}).click();const preview=p.getByRole('dialog',{name:'GIF 미리보기',exact:true});assert.equal(await preview.locator('img').getAttribute('src'),'https://fixture.test/original.gif');await preview.getByRole('button',{name:/^닫기/}).last().click();await dlg(p).getByRole('button',{name:'합성 GIF',exact:true}).click();await insert(p);await dlg(p).waitFor({state:'detached'});const im=(await images(p))[0];assert.equal(im.src,'data:image/gif;base64,'+gif.toString('base64'));await p.evaluate(()=>tabula.run('undo'));assert.equal(await snapshot(p),before);});
 await test('영상 명령·실제 WebM 미리보기 재생·웹영상 삽입·Undo',async p=>{const before=await snapshot(p);await open(p,'video');await search(p);await dlg(p).getByRole('button',{name:'합성 영상 미리보기',exact:true}).click();const preview=p.getByRole('dialog',{name:'영상 미리보기',exact:true}),video=preview.locator('video');assert.equal(await video.getAttribute('autoplay'),null);await video.evaluate(async v=>{await v.play();});await p.waitForFunction(()=>document.querySelector('.online-media-preview video')?.currentTime>0);await preview.getByRole('button',{name:/^닫기/}).last().click();await dlg(p).getByRole('button',{name:'합성 영상',exact:true}).click();await insert(p);await dlg(p).waitFor({state:'detached'});const im=(await images(p))[0];assert.equal(im.media.kind,'video');assert.equal(im.media.src,'https://fixture.test/movie.webm');assert.ok(im.src.startsWith('data:image/'));await p.evaluate(()=>tabula.run('undo'));assert.equal(await snapshot(p),before);});
 await test('Pexels 설정된 영상 결과·메타·삽입',async(p,n)=>{n.configured=true;await open(p,'video');await search(p,'pexels');await dlg(p).getByRole('button',{name:'pexels 합성',exact:true}).click();await insert(p);await dlg(p).waitFor({state:'detached'});assert.equal((await images(p))[0].media.source,'pexels');assert.ok(n.requests.every(x=>!x.headers||!x.headers['x-wixel-vault']));});
 await test('Unsplash 검색/미리보기에는 추적없음·삽입 때1회추적+hotlink',async(p,n)=>{n.configured=true;await open(p);await search(p,'unsplash');assert.equal(n.tracks,0);await dlg(p).getByRole('button',{name:'unsplash 합성',exact:true}).click();await insert(p);await dlg(p).waitFor({state:'detached'});assert.equal(n.tracks,1);assert.equal((await images(p))[0].src,'https://fixture.test/full.png');});
 await test('Pixabay 내장 필수 그림 다운로드 실패는 연결로 가장하지 않음',async(p,n)=>{n.configured=true;await open(p);await search(p,'pixabay');await dlg(p).getByRole('button',{name:'pixabay 합성',exact:true}).click();n.failImage=true;await insert(p);await dlg(p).getByRole('alert').waitFor();assert.match(await dlg(p).getByRole('alert').innerText(),/포함해야|다운로드/);assert.equal((await images(p)).length,0);});
 await test('CC는새공급자제외·GIF검색은Wikimedia만',async(p,n)=>{await open(p);await search(p,'all');assert.equal(n.requests.filter(x=>['unsplash','pexels','pixabay'].includes(x.source)).length,3);const at=n.requests.length;await dlg(p).getByLabel('Creative Commons만',{exact:true}).check();await settled(p);assert.ok(n.requests.slice(at).every(x=>!['unsplash','pexels','pixabay','nasa'].includes(x.source)));const at2=n.requests.length;await dlg(p).getByLabel('미디어 종류',{exact:true}).selectOption('gif');await settled(p);assert.deepEqual(n.requests.slice(at2).map(x=>x.source),['wikimedia']);});
 await test('영상 웹페이지주소 거절·WebM직접주소 삽입',async p=>{await open(p,'video');const field=dlg(p).getByRole('textbox',{name:'그림 웹 주소',exact:true});await field.fill('https://fixture.test/watch?v=1');await insert(p);await dlg(p).getByRole('alert').waitFor();assert.match(await dlg(p).getByRole('alert').innerText(),/직접 파일/);await field.fill('https://fixture.test/movie.webm');await insert(p);await dlg(p).waitFor({state:'detached'});assert.equal((await images(p))[0].media.src,'https://fixture.test/movie.webm');});
 await test('320px 검색·종류·사이트·삽입/취소 접근',async p=>{await p.setViewportSize({width:320,height:700});await open(p,'gif');await search(p);for(const selector of [dlg(p).getByLabel('미디어 종류',{exact:true}),dlg(p).getByRole('button',{name:'검색',exact:true}),dlg(p).getByRole('button',{name:'삽입',exact:true}),dlg(p).getByRole('button',{name:'취소',exact:true})]){const b=await selector.boundingBox();assert.ok(b&&b.x>=-1&&b.x+b.width<=321&&b.y>=-1&&b.y+b.height<=701,JSON.stringify(b));}await p.screenshot({path:process.env.MEDIA_SCREENSHOT||'D:/Codex/Temp/wixel-media-mobile.png'});});
}finally{await browser.close();}
console.log(JSON.stringify({url,total:results.length,passed:results.filter(r=>r.ok).length,failed:results.filter(r=>!r.ok).length,results},null,2));if(results.some(r=>!r.ok)||!results.length)process.exitCode=1;
