// 피벗 전용 우클릭: 합성 문서/격리 브라우저/클립보드 모의, 외부 및 API 쓰기 차단.
import assert from 'node:assert/strict';
import { gzipSync } from 'node:zlib';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolvePivot, computePivot } from '../src/pivot.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5191/',out=process.env.WIXEL_PIVOT_CONTEXT_OUT||'D:/Codex/Temp/wixel-pivot-context/source',filter=process.env.WIXEL_PIVOT_CONTEXT_FILTER||'';
await mkdir(out,{recursive:true});const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1400,height:1000}}),p=await context.newPage();const errors=[],writes=[],reads=[],results=[];let checks=0,current;
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);},ok=(a,m)=>{checks++;assert.ok(a,m);};
p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;window.__mockClipboard='';Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async s=>{window.__mockClipboard=s;},readText:async()=>window.__mockClipboard}});});
await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(u.pathname);return r.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/')){reads.push(u.pathname);return r.abort();}return r.continue();});
const data=[['지역','상품','매출','수량'],['서울','A',10,2],['서울','B',30,3],['부산','A',20,4]];
const base={name:'문맥피벗',source:'합성 원본',range:{r1:0,c1:0,r2:3,c2:3},rows:['지역'],cols:[],values:[{field:'매출',agg:'sum'},{field:'매출',agg:'average'}],layout:'tabular',top:1,left:1};
const run=c=>p.evaluate(c=>window.tabula.run(c),c),def=()=>p.evaluate(()=>window.tabula.wb().sheets[1].pivot),menu=()=>p.locator('#menuLayer>.menu[data-context-kind="pivot"]');
const dialog=name=>p.getByRole('dialog',{name,exact:true});
async function reset(patch={}){for(let i=0;i<5;i++)await p.keyboard.press('Escape');current={...base,...patch};const res=resolvePivot(data,current);current={...current};const computed=computePivot(res,res.def);await p.evaluate(({data,current})=>{const t=window.tabula,w=t.wb();if(t.si!==0)t.switchSheet(0);const cells={};data.forEach((row,r)=>row.forEach((v,c)=>cells[r+','+c]={raw:String(v)}));w.restore({sheets:[{name:'합성 원본',cells},{name:'피벗',cells:{},pivot:current},{name:'다른 시트',cells:{}}]});t.switchSheet(1,false);t.run('pivotRefresh');w.undoStack=[];w.redoStack=[];t.selectCell(2,2);}, {data,current});return computed;}
function point(role,computed){for(let r=0;r<computed.grid.length;r++)for(let c=0;c<computed.grid[r].length;c++)if(computed.grid[r][c]?.role===role)return {r:r+current.top,c:c+current.left};throw Error('역할 없음 '+role);}
async function open(role='data:1',mouse=false){const res=resolvePivot(data,current),pt=point(role,computePivot(res,res.def));await p.evaluate(({r,c})=>window.tabula.selectCell(r,c),pt);await p.locator('#cellEditor').focus();if(mouse){const at=await p.evaluate(({r,c})=>{const b=window.tabula.gv().clientRect({r1:r,c1:c,r2:r,c2:c});return{x:(b.left+b.right)/2,y:(b.top+b.bottom)/2};},pt);await p.mouse.click(at.x,at.y,{button:'right'});}else await p.keyboard.press('Shift+F10');await menu().waitFor();return pt;}
async function pick(name){await menu().getByRole('menuitem',{name}).click();}
async function sub(parent,child){await menu().getByRole('menuitem',{name:parent}).hover();await p.locator('#menuLayer .menu').getByRole('menuitem',{name:child,exact:true}).click();}
async function test(name,fn){if(filter&&!name.includes(filter))return;const start=errors.length;try{await p.setViewportSize({width:1400,height:1000});await reset();await fn();eq(errors.slice(start),[],'페이지 오류');results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message});console.error('NG '+name+' '+e.stack);await p.screenshot({path:out+'/failure-'+results.length+'.png'}).catch(()=>{});}}
try{
await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());
await test('실제 값 셀 우클릭은 피벗 메뉴와 미니 도구 모음을 표시한다',async()=>{await open('data:1',true);const text=await menu().textContent();for(const name of ['복사','셀 서식','필드 표시 형식','새로 고침','정렬','제거','값 요약 기준','값 표시 형식','자세한 정보 표시','값 필드 설정','피벗 테이블 옵션','필드 목록'])ok(text.includes(name),name);ok(!text.includes('표/범위에서 데이터 가져오기'));eq(await p.locator('.context-mini-toolbar').count(),1);await p.screenshot({path:out+'/value-menu.png'});});
await test('요약 기준은 중복 원본의 선택한 값 필드만 변경하고 Undo된다',async()=>{const before=await def();await open();await sub(/값 요약 기준/,'최대');eq((await def()).values.map(v=>v.agg),['sum','max']);eq(await p.evaluate(()=>window.tabula.wb().undoStack.length),1);await run('undo');eq((await def()).values,before.values);});
await test('값 표시 형식의 비율과 계산 없음이 실제 모델에 적용된다',async()=>{await open();await sub(/값 표시 형식/,'총합계 비율');eq((await def()).values[1].showAs,'percentOfTotal');await open();await sub(/값 표시 형식/,'계산 없음');eq((await def()).values[1].showAs,undefined);});
await test('기준 필드가 필요한 값 표시는 설정 창을 열고 취소하면 보존한다',async()=>{const before=await def();await open();await sub(/값 표시 형식/,'차이...');const d=dialog('값 필드 설정');await d.waitFor();eq(await d.locator('.vf-show').inputValue(),'difference');await d.getByRole('button',{name:'취소',exact:true}).click();eq(await def(),before);});
await test('공용 값 필드 설정과 내부 표시 형식은 한 번 확인으로 적용된다',async()=>{await open();await pick(/값 필드 설정/);const d=dialog('값 필드 설정');await d.locator('.vf-list').first().selectOption('count');await d.getByRole('button',{name:/표시 형식\(N\)/}).click();const f=dialog('표시 형식');await f.getByRole('combobox').selectOption('#,##0.00');await f.getByRole('button',{name:'확인',exact:true}).click();await d.getByRole('button',{name:'확인',exact:true}).click();eq((await def()).values[1].agg,'count');eq((await def()).values[1].numFmt.code,'#,##0.00');eq(await p.evaluate(()=>window.tabula.wb().undoStack.length),1);});
await test('필드 표시 형식은 값 필드 전체에 적용하고 다른 값은 보존한다',async()=>{const before=await def();await open();await pick(/필드 표시 형식/);const d=dialog('필드 표시 형식');await d.getByRole('combobox').selectOption('0.00%');await d.getByRole('button',{name:'확인',exact:true}).click();eq((await def()).values[1].numFmt.code,'0.00%');eq((await def()).values[0],before.values[0]);await run('undo');eq((await def()).values,before.values);});
await test('현재 값 필드 제거는 동일 원본 필드의 다른 요약을 남긴다',async()=>{await open();await pick(/제거\(E\)/);eq((await def()).values.map(v=>v.agg),['sum']);await run('undo');eq((await def()).values.length,2);});
await test('값 셀 정렬은 값 기준, 레이블 정렬은 이름 기준으로 적용한다',async()=>{await open();await sub(/^정렬/,'내림차순 정렬(O)');eq((await def()).sort.지역,{dir:'desc',by:1});await run('undo');await open('rowItem:0');eq(await menu().getByRole('menuitem',{name:/값 요약 기준/}).count(),0);await sub(/^정렬/,'오름차순 정렬(S)');eq((await def()).sort.지역,{dir:'asc'});});
await test('행 레이블 필드 설정과 제거는 값 필드를 변경하지 않는다',async()=>{await open('rowItem:0');await pick(/^필드 설정/);const d=dialog('필드 설정');await d.getByRole('textbox').fill('사업 지역');await d.getByRole('button',{name:'확인',exact:true}).click();eq((await def()).fieldCaptions.지역,'사업 지역');await open('rowItem:0');await pick(/제거\(E\)/);eq((await def()).rows,[]);eq((await def()).values.length,2);});
await test('행에 배치한 여러 값의 자세한 정보는 원본 행을 새 표로 만든다',async()=>{await reset({valuesOnRows:true});await open('data:1');await pick(/자세한 정보 표시/);eq(await p.evaluate(()=>window.tabula.wb().sheets.length),4);ok(await p.evaluate(()=>{const t=window.tabula;return t.wb().sheets[t.si].tables.length===1&&t.wb().usedRange(t.si).rows>1;}));await run('undo');eq(await p.evaluate(()=>window.tabula.wb().sheets.length),3);});
await test('세부 정보 금지와 시트·통합 문서 보호는 변경 항목을 막는다',async()=>{await reset({enableDrill:false});await open();eq(await menu().getByRole('menuitem',{name:/자세한 정보/}).isDisabled(),true);await p.keyboard.press('Escape');await p.evaluate(()=>{const w=window.tabula.wb();w.sheets[1].protect={on:true,allow:{selectLocked:true}};});await open();eq(await menu().getByRole('menuitem',{name:/값 요약 기준/}).isDisabled(),true);eq(await menu().getByRole('menuitem',{name:/복사/}).isDisabled(),false);await p.keyboard.press('Escape');await p.evaluate(()=>{const w=window.tabula.wb();w.sheets[1].protect=null;w.props.lockStructure=true;});await open();eq(await menu().getByRole('menuitem',{name:/자세한 정보/}).isDisabled(),true);});
await test('열린 값 필드 창은 다른 시트 전환 뒤 원래 피벗도 수정하지 않는다',async()=>{const before=await def();await open();await pick(/값 필드 설정/);const d=dialog('값 필드 설정');await d.locator('.vf-list').first().selectOption('min');await p.evaluate(()=>window.tabula.switchSheet(2));await d.getByRole('button',{name:'확인',exact:true}).click();eq(await def(),before);ok(await d.isVisible());});
await test('옵션 취소·필드 목록 숨김/표시·새로 고침이 실제 대상에 작동한다',async()=>{await open();await pick(/피벗 테이블 옵션/);const d=dialog('피벗 테이블 옵션');await d.waitFor();const before=await def();await d.getByRole('button',{name:'취소',exact:true}).click();eq(await def(),before);await open();await pick(/필드 목록 숨기기/);eq(await p.locator('#pivotPane').isVisible(),false);await open();await pick(/필드 목록 표시/);eq(await p.locator('#pivotPane').isVisible(),true);await open();await pick(/새로 고침/);eq((await def()).values,before.values);});
await test('390px 메뉴 스크롤과 하위 메뉴·Escape는 접근 가능하다',async()=>{await p.setViewportSize({width:390,height:844});await open();const b=await menu().boundingBox();ok(b.x>=-1&&b.x+b.width<=391&&b.y>=-1&&b.y+b.height<=845);await menu().getByRole('menuitem',{name:/값 요약 기준/}).scrollIntoViewIfNeeded();await menu().getByRole('menuitem',{name:/값 요약 기준/}).click();await p.locator('#menuLayer .menu').getByRole('menuitem',{name:'분산(전체)',exact:true}).scrollIntoViewIfNeeded();await p.screenshot({path:out+'/mobile-menu.png'});await p.keyboard.press('Escape');await p.keyboard.press('Escape');eq((await def()).values.map(v=>v.agg),['sum','average']);});
await test('레이블 필터는 실제 적용되고 대상 시트 변경 뒤에는 적용을 거부한다',async()=>{const choose=async()=>{await open('rowItem:0');await pick(/^필터/);await p.locator('.pf-sub').filter({hasText:'레이블 필터'}).hover();await p.locator('#menuLayer .menu').getByRole('menuitem',{name:'같음...',exact:true}).click();const d=dialog('레이블 필터(지역)');await d.getByRole('textbox').first().fill('서울');return d;};let d=await choose();await d.getByRole('button',{name:'확인',exact:true}).click();eq((await def()).fieldFilters.지역,{type:'label',op:'equal',v1:'서울',v2:''});await run('undo');const before=await def();d=await choose();await p.evaluate(()=>window.tabula.switchSheet(2));await d.getByRole('button',{name:'확인',exact:true}).click();eq(await def(),before);ok(await d.isVisible());});
await test('공개 읽기 전용 피벗은 복사만 허용하고 값·서식·상세 변경을 막는다',async()=>{const workbook=await p.evaluate(()=>window.tabula.wb().serialize());const hash=gzipSync(JSON.stringify({docName:'합성 공개 피벗',workbook,view:{headers:true}})).toString('base64url');await p.goto('about:blank');await p.goto(url.split('#')[0]+'#view='+hash,{waitUntil:'domcontentloaded',timeout:60000});await p.locator('.view-bar').waitFor();await p.evaluate(()=>window.tabula.switchSheet(1));await open();for(const name of [/값 요약 기준/,/필드 표시 형식/,/자세한 정보 표시/])eq(await menu().getByRole('menuitem',{name}).isDisabled(),true);eq(await menu().getByRole('menuitem',{name:/복사/}).isDisabled(),false);});
}finally{await browser.close();const summary={url,tests:results.length,passed:results.filter(r=>r.ok).length,checks,pageErrors:errors,remoteWrites:writes,blockedReads:reads,results};await writeFile(out+'/result.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));if(results.some(r=>!r.ok)||errors.length||writes.length)process.exitCode=1;}
