// 합성 표/범위 로컬 변환 회귀. 사용자 문서/시스템 클립보드/원격 API는 사용하지 않습니다.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = process.env.WIXEL_URL || 'http://127.0.0.1:5191/';
const out = process.env.WIXEL_RANGE_QUERY_OUT || 'D:/Codex/Temp/wixel-range-query/source';
const only = process.env.WIXEL_RANGE_QUERY_FILTER || '';
await mkdir(out,{recursive:true});
const browser = await chromium.launch(), context = await browser.newContext({viewport:{width:1366,height:900}}), p=await context.newPage();
const errors=[],writes=[],reads=[],results=[]; let checks=0;
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);};const ok=(a,m)=>{checks++;assert.ok(a,m);};
p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>'',writeText:async()=>{}}});});
await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(u.pathname);return r.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/')){reads.push(u.pathname);return r.abort();}return r.continue();});
const run=c=>p.evaluate(c=>window.tabula.run(c),c);
const dialog=()=>p.getByRole('dialog',{name:'표/범위에서 데이터 가져오기',exact:true});
const load=()=>dialog().getByRole('button',{name:/닫기 및 로드/}).click();
const raw=()=>p.evaluate(()=>{const w=window.tabula.wb();return w.rangeRead(1,0,0,w.usedRange(1).rows-1,w.usedRange(1).cols-1).map(row=>row.map(v=>v?.code?{code:v.code}:v));});
const state=()=>p.evaluate(()=>JSON.stringify(window.tabula.wb().serialize()));
async function reset(matrix=[['품목','금액','분류'],['가','1,200','광고'],['나','900','광고'],['가','1,200','기타'],[null,null,null],['다','1,300','광고'],['라','1,200','광고']],extra={}){
 for(let i=0;i<5;i++)await p.keyboard.press('Escape');
 await p.evaluate(({matrix,extra})=>{const t=window.tabula,w=t.wb();if(t.si!==0)t.switchSheet(0);const cells={};matrix.forEach((row,r)=>row.forEach((v,c)=>{if(v!==null&&v!==undefined)cells[r+','+c]=typeof v==='object'?{raw:v.code}:typeof v==='string'?{raw:v,inputType:'text'}:{raw:String(v)};}));w.restore({sheets:[{name:'합성 원본',cells,...extra}]});w.undoStack=[];w.redoStack=[];t.gv().setZoom(100);t.gv().layout();t.gv().renderAll();t.selectRange({r1:0,c1:0,r2:matrix.length-1,c2:matrix[0].length-1});},{matrix,extra});
}
async function open(){await run('fromTableRange');await dialog().waitFor();await dialog().locator('.range-query-editor').waitFor();return dialog();}
async function settled(){await p.waitForTimeout(160);}
async function test(name,fn){if(only&&!name.includes(only))return;const before=errors.length;try{await p.setViewportSize({width:1366,height:900});await reset();await fn();eq(errors.slice(before),[],'페이지 오류');results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message});console.error('NG '+name+' '+e.stack);await p.screenshot({path:out+'/failure-'+results.length+'.png'}).catch(()=>{});}}
try{
 await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());await p.evaluate(()=>document.fonts.ready);
 await test('원본 값 미리보기와 취소는 원본·Undo를 바꾸지 않는다',async()=>{const before=await state(),d=await open();eq(await d.locator('.rq-table tbody tr').count(),6);ok((await d.getByRole('status').textContent()).includes('결과 6행'));await d.getByRole('combobox',{name:'금액 유형',exact:true}).selectOption('number');await settled();await d.getByRole('button',{name:'취소',exact:true}).click();eq(await state(),before);eq(await p.evaluate(()=>window.tabula.wb().undoStack.length),0);});
 await test('열·유형·필터·정렬·중복을 적용해 새 표로 로드하고 한 번 Undo',async()=>{
  const before=await p.evaluate(()=>JSON.stringify(window.tabula.wb().serialize().sheets[0])),d=await open();
  await d.getByRole('textbox',{name:'새 시트 이름',exact:true}).fill('정리 결과');await d.getByRole('checkbox',{name:'분류 열 가져오기',exact:true}).uncheck();await d.getByRole('combobox',{name:'금액 유형',exact:true}).selectOption('number');
  await d.getByRole('button',{name:'필터 추가',exact:true}).click();await d.getByRole('combobox',{name:'필터 열',exact:true}).selectOption('1');await d.getByRole('combobox',{name:'필터 조건',exact:true}).selectOption('ge');await d.getByRole('textbox',{name:'필터 값',exact:true}).fill('1000');
  await d.locator('summary').filter({hasText:'정렬'}).click();await d.getByRole('button',{name:'정렬 추가',exact:true}).click();await d.getByRole('combobox',{name:'정렬 열',exact:true}).selectOption('1');await d.getByRole('combobox',{name:'정렬 방향',exact:true}).selectOption('desc');await d.getByRole('checkbox',{name:'중복 행 제거',exact:true}).check();await d.getByRole('checkbox',{name:'빈 행 제거',exact:true}).check();await settled();
  await p.screenshot({path:out+'/editor.png'});await load();await d.waitFor({state:'detached'});eq(await raw(),[['품목','금액'],['다',1300],['가',1200],['라',1200]]);eq(await p.evaluate(()=>JSON.stringify(window.tabula.wb().serialize().sheets[0])),before);eq(await p.evaluate(()=>window.tabula.wb().sheets[1].tables.length),1);eq(await p.evaluate(()=>window.tabula.wb().undoStack.length),1);await run('undo');eq(await p.evaluate(()=>window.tabula.wb().sheets.length),1);await run('redo');eq((await raw())[1],['다',1300]);
 });
 await test('유형 유지로 ID·수식 문자·0·FALSE·오류 값을 보존한다',async()=>{await reset([['ID','수식 문자','숫자','논리','오류'],['001','=1+1',0,false,{code:'#N/A'}]]);const d=await open();await load();await d.waitFor({state:'detached'});eq(await raw(),[['ID','수식 문자','숫자','논리','오류'],['001','=1+1',0,false,{code:'#N/A'}]]);eq(await p.evaluate(()=>!!window.tabula.wb().getCell(1,1,1).formula),false);});
 await test('유형 변환 오류는 로드를 막고 잘못된 값은 원본에 남는다',async()=>{await reset([['금액'],['12,34']]);const before=await state(),d=await open();await d.getByRole('combobox',{name:'금액 유형',exact:true}).selectOption('number');await settled();ok((await d.locator('.rq-error').textContent()).includes('오류 1개'));await load();const a=p.getByRole('dialog',{name:'데이터 가져오기',exact:true});await a.waitFor();eq(await p.evaluate(()=>window.tabula.wb().sheets.length),1);await p.keyboard.press('Escape');await d.getByRole('combobox',{name:'금액 유형',exact:true}).selectOption('keep');await d.getByRole('button',{name:'취소',exact:true}).click();eq(await state(),before);});
 await test('머리글 전환·빈 행 제거는 0·FALSE와 빈 좌표를 구분한다',async()=>{await reset([['첫 값','구분'],[0,false],[null,null],['끝','보존']]);const d=await open();await d.getByRole('checkbox',{name:'첫 행을 머리글로 사용',exact:true}).uncheck();await d.getByRole('checkbox',{name:'빈 행 제거',exact:true}).check();await d.getByRole('button',{name:'필터 추가',exact:true}).click();await d.getByRole('checkbox',{name:'첫 행을 머리글로 사용',exact:true}).check();eq(await d.getByRole('combobox',{name:'필터 열',exact:true}).locator('option').allTextContents(),['첫 값','구분']);await d.getByRole('button',{name:'필터 삭제',exact:true}).click();await d.getByRole('checkbox',{name:'첫 행을 머리글로 사용',exact:true}).uncheck();await load();await d.waitFor({state:'detached'});eq(await raw(),[['열1','열2'],['첫 값','구분'],[0,false],['끝','보존']]);});
 await test('표 내부 셀 선택은 전체 표를 읽고 합계행을 제외한다',async()=>{await reset([['항목','값'],['가',2],['나',3],['합계',5]],{tables:[{id:'query-test',name:'합성표',r1:0,c1:0,r2:3,c2:1,header:true,totals:true}]});await p.evaluate(()=>window.tabula.selectCell(1,1));const d=await open();ok((await d.locator('.rq-source').textContent()).includes('합성표'));await load();await d.waitFor({state:'detached'});eq(await raw(),[['항목','값'],['가',2],['나',3]]);});
 await test('원본 편집과 문서 구조 보호는 오래된 사본 로드를 차단한다',async()=>{const d=await open();await p.evaluate(()=>{const w=window.tabula.wb();w.transact(()=>w.setInput(0,1,0,'변경'));});await load();eq(await p.evaluate(()=>window.tabula.wb().sheets.length),1);ok(await d.isVisible());await d.getByRole('button',{name:'취소',exact:true}).click();await p.evaluate(()=>{window.tabula.wb().props.lockStructure=true;});await run('fromTableRange');eq(await p.locator('.range-query-editor').count(),0);});
 await test('전체 열 선택은 사용 범위만 읽고 초과한 유한 범위는 거부한다',async()=>{await p.evaluate(()=>window.tabula.selectRange({r1:0,c1:0,r2:1048575,c2:2},'cols'));let d=await open();ok((await d.locator('.rq-source').textContent()).includes('7행'));await d.getByRole('button',{name:'취소',exact:true}).click();await p.evaluate(()=>{const t=window.tabula,w=t.wb();w.transact(()=>w.setInput(0,100000,0,'합성 끝행'));t.selectRange({r1:0,c1:0,r2:100000,c2:2});});await run('fromTableRange');d=dialog();await d.waitFor();eq(await d.locator('.range-query-editor').count(),0);ok((await d.textContent()).includes('범위를 줄여'));});
 await test('날짜·논리값 변환과 필터가 실제 새 시트 값·서식에 반영된다',async()=>{await reset([['날짜','참거짓'],['2024-02-29','TRUE'],['2024-03-01','FALSE']]);const d=await open();await d.getByRole('combobox',{name:'날짜 유형',exact:true}).selectOption('date');await d.getByRole('combobox',{name:'참거짓 유형',exact:true}).selectOption('boolean');await d.getByRole('button',{name:'필터 추가',exact:true}).click();await d.getByRole('combobox',{name:'필터 조건',exact:true}).selectOption('ge');await d.getByRole('textbox',{name:'필터 값',exact:true}).fill('2024-03-01');await load();await d.waitFor({state:'detached'});const data=await raw();eq(data.length,2);eq(data[1][1],false);ok(typeof data[1][0]==='number');eq(await p.evaluate(()=>window.tabula.wb().getCell(1,1,0).style.numFmt),'date');});
 await test('390px 편집기 스크롤·입력·로드·취소 버튼은 화면에서 조작할 수 있다',async()=>{await p.setViewportSize({width:390,height:844});const d=await open();const b=await d.boundingBox();ok(b.x>=-1&&b.x+b.width<=391);eq(await d.evaluate(e=>e.scrollWidth<=e.clientWidth+1),true);for(const e of [d.getByRole('textbox',{name:'새 시트 이름',exact:true}),d.getByRole('button',{name:/닫기 및 로드/}),d.getByRole('button',{name:'취소',exact:true})]){await e.scrollIntoViewIfNeeded();ok(await e.evaluate(el=>{const r=el.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===el||el.contains(hit);}));}await p.screenshot({path:out+'/mobile.png'});await p.keyboard.press('Escape');eq(await p.evaluate(()=>window.tabula.wb().sheets.length),1);});
}finally{await browser.close();const summary={url,tests:results.length,passed:results.filter(r=>r.ok).length,checks,pageErrors:errors,remoteWrites:writes,blockedReads:reads,results};await writeFile(out+'/result.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary));if(results.some(r=>!r.ok)||errors.length||writes.length)process.exitCode=1;}
