import assert from 'node:assert/strict';
import { excelHash } from '../src/protect.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5180/',browser=await chromium.launch(),results=[];
const run=(p,cmd)=>p.evaluate(cmd=>window.tabula.run(cmd),cmd);
const dialog=(p,name)=>p.getByRole('dialog',{name,exact:true});
const unlock=p=>p.getByRole('dialog',{name:'범위 잠금 해제 — 암호 범위',exact:true});
const state=p=>p.evaluate(()=>{const t=window.tabula,w=t.wb();return{raw:w.getRaw(0,0,0),other:w.getRaw(0,0,2),protected:w.sheets[0].protect?.on,ranges:w.sheets[0].protectedRanges,notes:w.sheets[0].noteVisibility,undo:w.undoStack.length};});
async function test(name,fn){const ctx=await browser.newContext({viewport:{width:1400,height:1000}}),p=await ctx.newPage(),errors=[],writes=[];p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());await ctx.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(q.method());return r.abort();}return u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?r.continue():r.abort();});try{await ctx.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;Object.defineProperty(navigator,'clipboard',{value:{readText:async()=>'',writeText:async()=>{}}});});await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());await p.evaluate(hash=>{const t=window.tabula,w=t.wb();w.restore({sheets:[{name:'검토 합성',cells:{'0,0':{raw:'기존',comment:'첫째 메모'},'0,1':{raw:'자유'},'0,2':{raw:'바깥'},'2,2':{raw:'셋째',comment:'셋째 메모'}},protectedRanges:[{name:'암호 범위',hash,ranges:[{r1:0,c1:0,r2:1,c2:0}]},{name:'자유 범위',ranges:[{r1:0,c1:1,r2:1,c2:1}]}],protect:{on:true,allow:{selectLocked:true,selectUnlocked:true}}},{name:'다른 합성',cells:{'0,0':{raw:'다른 원본'}}}]});t.switchSheet(0);t.selectCell(0,0);w.undoStack=[];w.redoStack=[];},excelHash('synthetic'));await fn(p);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);results.push({name,ok:true});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message,errors,writes});console.error('NG '+name+': '+e.stack);}finally{await ctx.close();}}
async function edit(p,r,c,text){await p.evaluate(([r,c])=>window.tabula.selectCell(r,c),[r,c]);await p.locator('#cellEditor').focus();await p.keyboard.type(text);}
try{
await test('자동 범위 암호 창 취소는 값·보호·Undo 보존',async p=>{await edit(p,0,0,'9');await unlock(p).waitFor();await unlock(p).getByRole('button',{name:'취소',exact:true}).click();assert.equal((await state(p)).raw,'기존');assert.equal((await state(p)).undo,0);assert.equal((await state(p)).protected,true);});
await test('틀린 암호 거부 뒤 올바른 암호로 최초 편집 재개·Undo',async p=>{await edit(p,0,0,'9');await unlock(p).getByLabel('범위 암호(P)',{exact:true}).fill('wrong');await unlock(p).getByRole('button',{name:'확인',exact:true}).click();await dialog(p,'범위 잠금 해제').getByRole('button',{name:'확인',exact:true}).click();assert.equal((await state(p)).raw,'기존');await unlock(p).getByLabel('범위 암호(P)',{exact:true}).fill('synthetic');await unlock(p).getByRole('button',{name:'확인',exact:true}).click();await unlock(p).waitFor({state:'detached'});await p.locator('#cellEditor').press('Enter');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,0,0)==='9');assert.equal((await state(p)).protected,true);await run(p,'undo');assert.equal((await state(p)).raw,'기존');});
await test('암호 없는 범위만 편집 허용하고 밖의 잠금 유지',async p=>{await edit(p,0,1,'7');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>window.tabula.wb().getRaw(0,0,1)),'7');await edit(p,0,2,'8');await dialog(p,'WIXEL').waitFor();assert.equal((await state(p)).other,'바깥');});
await test('범위 세션 허가는 통합 문서 복원 후 이어지지 않음',async p=>{await run(p,'allowEditRanges');await dialog(p,'범위 편집 허용').getByRole('listbox').selectOption('0');await dialog(p,'범위 편집 허용').getByRole('button',{name:'범위 잠금 해제(U)',exact:true}).click();await unlock(p).getByLabel('범위 암호(P)',{exact:true}).fill('synthetic');await unlock(p).getByRole('button',{name:'확인',exact:true}).click();await unlock(p).waitFor({state:'detached'});await dialog(p,'범위 편집 허용').getByRole('button',{name:/^닫기/}).last().click();await p.evaluate(()=>{const t=window.tabula,w=t.wb();w.restore(w.serialize());t.selectCell(0,0);});await edit(p,0,0,'6');await unlock(p).waitFor();assert.equal((await state(p)).raw,'기존');});
await test('범위 정의는 새로 만들기·취소·저장·실행 취소',async p=>{await p.evaluate(()=>window.tabula.wb().sheets[0].protect.on=false);await run(p,'allowEditRanges');const manager=dialog(p,'범위 편집 허용');await manager.getByRole('button',{name:'새로 만들기(N)',exact:true}).click();let d=dialog(p,'새 편집 허용 범위');await d.getByLabel('제목(T)',{exact:true}).fill('새 범위');await d.getByRole('button',{name:'취소',exact:true}).click();assert.equal((await state(p)).ranges.length,2);await manager.getByRole('button',{name:'새로 만들기(N)',exact:true}).click();d=dialog(p,'새 편집 허용 범위');await d.getByLabel('제목(T)',{exact:true}).fill('새 범위');await d.getByLabel('셀 참조(R) — 여러 범위는 쉼표로 구분',{exact:true}).fill('D1:D3, F1:F2');await d.getByRole('button',{name:'확인',exact:true}).click();await d.waitFor({state:'detached'});assert.equal((await state(p)).ranges.length,3);await manager.getByRole('button',{name:/^닫기/}).last().click();await run(p,'undo');assert.equal((await state(p)).ranges.length,2);});
await test('보호된 시트에서는 범위 정의 변경 거부',async p=>{await run(p,'allowEditRanges');await dialog(p,'범위 편집 허용').getByRole('button',{name:'새로 만들기(N)',exact:true}).click();assert.equal(await dialog(p,'새 편집 허용 범위').count(),0);assert.equal((await state(p)).ranges.length,2);});
await test('모든 메모·개별 표시·숨김은 실제 카드 및 Undo에 반영',async p=>{await run(p,'showAllComments');await p.locator('.cell-note-visible[data-note-r="0"][data-note-c="0"]').waitFor();await p.locator('.cell-note-visible[data-note-r="2"][data-note-c="2"]').waitFor();await run(p,'toggleComment');assert.equal(await p.locator('.cell-note-visible[data-note-r="0"][data-note-c="0"]').count(),0);assert.equal(await p.locator('.cell-note-visible[data-note-r="2"][data-note-c="2"]').count(),1);await run(p,'undo');await p.locator('.cell-note-visible[data-note-r="0"][data-note-c="0"]').waitFor();await run(p,'hideAllComments');assert.equal(await p.locator('.cell-note-visible').count(),0);});
await test('범위 암호 입력 중 시트 전환은 다른 시트 편집 금지',async p=>{await edit(p,0,0,'5');await unlock(p).getByLabel('범위 암호(P)',{exact:true}).fill('synthetic');await p.evaluate(()=>window.tabula.switchSheet(1));await unlock(p).getByRole('button',{name:'확인',exact:true}).click();await unlock(p).waitFor({state:'detached'});assert.equal(await p.evaluate(()=>window.tabula.wb().getRaw(1,0,0)),'다른 원본');assert.equal((await state(p)).raw,'기존');});
await test('범위 대화상자 Alt 접근키는 새로 만들기·입력·삭제 동작',async p=>{await p.evaluate(()=>window.tabula.wb().sheets[0].protect.on=false);await run(p,'allowEditRanges');await p.keyboard.press('Alt+n');const d=dialog(p,'새 편집 허용 범위');await d.waitFor();await p.keyboard.press('Alt+t');assert.equal(await d.getByLabel('제목(T)',{exact:true}).evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Alt+r');assert.equal(await d.getByLabel('셀 참조(R) — 여러 범위는 쉼표로 구분',{exact:true}).evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');const manager=dialog(p,'범위 편집 허용');await manager.getByRole('listbox').selectOption('0');await p.keyboard.press('Alt+d');assert.equal((await state(p)).ranges.length,1);await manager.waitFor();});
await test('선택 붙여넣기 범위 암호 취소·허용·재확인·Undo',async p=>{await p.evaluate(()=>window.tabula.selectCell(0,1));await run(p,'copy');await p.evaluate(()=>window.tabula.selectCell(0,0));await p.locator('#cellEditor').focus();await p.keyboard.press('Control+Alt+v');const d=dialog(p,'선택하여 붙여넣기');await d.getByRole('radio',{name:'값',exact:true}).check();await d.getByRole('button',{name:'확인',exact:true}).click();await unlock(p).waitFor();await unlock(p).getByRole('button',{name:'취소',exact:true}).click();assert.equal((await state(p)).raw,'기존');await d.getByRole('button',{name:'확인',exact:true}).click();await unlock(p).getByLabel('범위 암호(P)',{exact:true}).fill('synthetic');await unlock(p).getByRole('button',{name:'확인',exact:true}).click();await unlock(p).waitFor({state:'detached'});assert.equal((await state(p)).raw,'기존');await d.getByRole('button',{name:'확인',exact:true}).click();await d.waitFor({state:'detached'});assert.equal((await state(p)).raw,'자유');assert.equal((await state(p)).protected,true);await run(p,'undo');assert.equal((await state(p)).raw,'기존');});
}finally{await browser.close();console.log(JSON.stringify({url,total:results.length,good:results.filter(x=>x.ok).length,bad:results.filter(x=>!x.ok).length,results},null,2));if(results.some(x=>!x.ok))process.exitCode=1;}
