// 슬라이서·혼합 개체의 다중 이동, 맞춤, 중단 원자성. 로컬 합성 문서만 사용.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url = process.env.WIXEL_URL || 'http://127.0.0.1:5191/';
if (!['localhost','127.0.0.1','[::1]'].includes(new URL(url).hostname)) throw Error('로컬 검증 서버에서만 실행하세요.');
const baseline = process.env.SLICER_ARRANGE_BASELINE ? execFileSync('git',['-c','safe.directory=D:/위셀/wixel-3','show',process.env.SLICER_ARRANGE_BASELINE+':tabula/src/app.js'],{encoding:'utf8',maxBuffer:8*1024*1024}) : null;
const browser=await chromium.launch(),results=[];let checks=0;
const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++;};const ok=(a,m)=>{assert.ok(a,m);checks++;};
const obj=(p,id)=>p.locator(`.obj[data-id="${id}"]`).first();
const state=p=>p.evaluate(()=>{const w=tabula.wb(),s=w.sheets[0];return{objects:[...s.slicers,...s.shapes].map(o=>({id:o.id,x:o.x,y:o.y,w:o.w,h:o.h})),undo:w.undoStack.length};});
async function choose(p,ids=['sl','sl2','shape']){await obj(p,ids[0]).locator('.sl-cap').click();for(const id of ids.slice(1)){const n=id==='shape'?obj(p,id):obj(p,id).locator('.sl-cap');await n.click({modifiers:['Control']});}}
async function start(p,id='sl'){const b=await obj(p,id).locator('.sl-cap').boundingBox();const a={x:b.x+30,y:b.y+b.height/2};await p.mouse.move(a.x,a.y);await p.mouse.down();return a;}
async function drag(p,dx,dy){const a=await start(p);await p.mouse.move(a.x+dx,a.y+dy,{steps:5});await p.mouse.up();}
async function menu(p,name,{disabled=false}={}){await p.evaluate(()=>tabula.openNamedMenu('objAlign',document.querySelector('[data-ribbon-menu="objAlign"]')||document.querySelector('#gridView')));const item=p.getByRole('menuitem',{name:new RegExp('^'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?:\\s|\\(|$)')});if(disabled){eq(await item.isDisabled(),true,'이동 제한 시 메뉴 비활성');await p.keyboard.press('Escape');}else await item.click();}

async function test(name,fn,options={}){
 if(process.env.SLICER_ARRANGE_FILTER&&!name.includes(process.env.SLICER_ARRANGE_FILTER))return;
 const context=await browser.newContext({viewport:{width:1500,height:1000}}),p=await context.newPage(),errors=[],writes=[];p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',r=>{const req=r.request(),u=new URL(req.url());if(!['GET','HEAD'].includes(req.method())){writes.push(req.method());return r.abort();}return u.origin===new URL(url).origin&&!u.pathname.startsWith('/api/')?r.continue():r.abort();});
 if(baseline)await context.route('**/src/app.js',r=>r.fulfill({contentType:'text/javascript',body:baseline}));
 try{
  await context.addInitScript(()=>{window.WIXEL_SKIP_START=true;window.TABULA_STATIC=true;Object.defineProperty(navigator,'clipboard',{value:{write:async()=>{},read:async()=>[],writeText:async()=>{},readText:async()=>''}});});
  await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());
  await p.evaluate(o=>{const w=tabula.wb();w.restore({sheets:[{name:'배치 검증',cells:{'0,0':{raw:'지역'},'0,1':{raw:'금액'},'1,0':{raw:'서울'},'1,1':{raw:'10'},'2,0':{raw:'부산'},'2,1':{raw:'20'}},tables:[{id:'table',name:'배치표',r1:0,c1:0,r2:2,c2:1,header:true}],slicers:[{id:'sl',caption:'지역 1',source:{kind:'table',table:'배치표',column:'지역'},x:220,y:100,w:160,h:180,z:1,locked:o.unlocked?false:undefined},{id:'sl2',caption:'지역 2',source:{kind:'table',table:'배치표',column:'지역'},x:440,y:160,w:180,h:190,z:2,noMove:o.noMove,locked:o.unlocked?false:undefined}],shapes:[{id:'shape',kind:'rect',x:700,y:120,w:60,h:70,fill:'#4472c4',stroke:'#000000',z:3,locked:o.unlocked?false:undefined},{id:'target',kind:'rect',x:825,y:480,w:60,h:70,fill:'#ef4444',stroke:'#000000',z:4}],...(o.protected?{protect:{on:true,allow:{selectLocked:true,selectUnlocked:true,objects:false}}}:{})},{name:'다른 시트',cells:{}}]});tabula.switchSheet(1);tabula.switchSheet(0);tabula.gv().layout();tabula.gv().renderAll();w.undoStack=[];w.redoStack=[];},options);
  await fn(p);eq(errors,[],'페이지 오류');eq(writes,[],'원격 쓰기');results.push({name,ok:true});console.log('OK '+name);
 }catch(e){results.push({name,ok:false,error:e.message,errors});console.error('NG '+name+': '+e.stack);}finally{await context.close();}
}
try{
 await test('혼합 개체 모두 같은 이동량·Undo 한 번·Redo',async p=>{await choose(p);const before=await state(p);await drag(p,80,45);const after=await state(p);eq(after.undo,1);for(let i=0;i<3;i++){eq(after.objects[i].x-before.objects[i].x,80);eq(after.objects[i].y-before.objects[i].y,45);}eq(after.objects[3],before.objects[3]);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);await p.evaluate(()=>tabula.run('redo'));eq(await state(p),after);});
 await test('공통 원점 제한은 선택 상대 간격 유지',async p=>{await choose(p);const before=await state(p),a=await start(p);await p.mouse.move(a.x-300,a.y-200,{steps:5});await p.mouse.up();const after=await state(p);eq(after.objects[0].x,0);eq(after.objects[0].y,0);for(let i=1;i<3;i++){eq(after.objects[i].x-after.objects[0].x,before.objects[i].x-before.objects[0].x);eq(after.objects[i].y-after.objects[0].y,before.objects[i].y-before.objects[0].y);}eq(after.undo,1);});
 await test('noMove 하나가 전체 이동과 맞춤을 차단',async p=>{await choose(p);const before=await state(p);await drag(p,60,40);eq(await state(p),before);await menu(p,'왼쪽 맞춤',{disabled:true});eq(await state(p),before);await menu(p,'선택한 개체를 셀 경계에 맞춤',{disabled:true});eq(await state(p),before);},{noMove:true});
 await test('보호 시 잠긴 선택 전체 이동 차단',async p=>{await choose(p);await p.evaluate(()=>{tabula.wb().sheets[0].protect={on:true,allow:{objects:false}};});const before=await state(p);await drag(p,60,40);eq(await state(p),before);});
 await test('보호 중 잠금 해제된 선택만은 이동 허용',async p=>{await choose(p);const before=await state(p);await drag(p,40,30);const after=await state(p);eq(after.undo,1);for(let i=0;i<3;i++)eq(after.objects[i].x,before.objects[i].x+40);},{protected:true,unlocked:true});
 await test('끌기 중 Escape는 모든 미리보기 원복·Undo 없음',async p=>{await choose(p);const before=await state(p),a=await start(p);await p.mouse.move(a.x+80,a.y+30,{steps:4});ok((await state(p)).objects[0].x!==before.objects[0].x);await p.keyboard.press('Escape');await p.mouse.up();eq(await state(p),before);});
 await test('끌기 중 시트 전환은 원본 미리보기 원복',async p=>{await choose(p);const before=await state(p),a=await start(p);await p.mouse.move(a.x+80,a.y+30,{steps:4});await p.evaluate(()=>tabula.switchSheet(1));await p.mouse.up();eq(await state(p),before);});
 await test('끌기 중 보호 전환은 원본 위치 보존',async p=>{await choose(p);const before=await state(p),a=await start(p);await p.mouse.move(a.x+80,a.y+30,{steps:4});await p.evaluate(()=>tabula.wb().transact(()=>tabula.wb().setSheetProp(0,'protect',{on:true,allow:{objects:false}})));await p.mouse.up();const after=await state(p);eq(after.objects,before.objects);eq(after.undo,1,'보호 설정 자체만 Undo');});
 await test('그룹 외곽 도형 스냅·상대 간격 유지',async p=>{await choose(p);await menu(p,'도형에 맞추기');const before=await state(p);await drag(p,60,30);const after=await state(p);eq(after.objects[2].x+after.objects[2].w,825,'그룹 오른쪽 외곽을 대상 왼쪽에 맞춤');for(let i=0;i<3;i++)eq(after.objects[i].x-before.objects[i].x,65);});
 await test('맞춤·가로 간격 배분 각각 Undo 한 번',async p=>{await choose(p);const before=await state(p);await menu(p,'위쪽 맞춤');const aligned=await state(p);eq(aligned.objects.slice(0,3).map(o=>o.y),[100,100,100]);eq(aligned.undo,1);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);await menu(p,'가로 간격을 동일하게');const after=await state(p),a=after.objects;eq(a[1].x-a[0].x-a[0].w,a[2].x-a[1].x-a[1].w);eq(after.undo,1);});

 await test('다중 맨 앞으로·뒤로는 내부 순서 유지·Undo',async p=>{await p.evaluate(()=>{const s=tabula.wb().sheets[0];s.slicers[0].z=2;s.slicers[1].z=3;s.shapes[0].z=1;tabula.gv().renderObjectsAll();});await choose(p,['sl','sl2']);const z=()=>p.evaluate(()=>[...tabula.wb().sheets[0].slicers,...tabula.wb().sheets[0].shapes].map(o=>({id:o.id,z:o.z})));const before=await z();for(const [name,label]of[['objForward','맨 앞으로 가져오기'],['objBackward','맨 뒤로 보내기']]){await p.evaluate(name=>tabula.openNamedMenu(name,document.querySelector('#gridView')),name);await p.getByRole('menuitem',{name:label,exact:true}).click();const after=await z();ok(after[0].z<after[1].z);if(name==='objForward')ok(after[0].z>after[3].z);else ok(after[1].z<after[2].z);eq((await state(p)).undo,1);await p.evaluate(()=>tabula.run('undo'));eq(await z(),before);}});
 await test('슬라이서 그룹 이동·비율 크기·행 높이 유지·Undo',async p=>{await choose(p,['sl','sl2']);await p.evaluate(()=>tabula.run('objGroup'));await p.locator('.slicer-group').first().waitFor();const before=await state(p);await drag(p,50,30);const moved=await state(p);for(let i=0;i<2;i++){eq(moved.objects[i].x,before.objects[i].x+50);eq(moved.objects[i].y,before.objects[i].y+30);}eq(moved.undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);const handle=await p.locator('.slicer-group .ch-h.se').first().boundingBox(),bounds=await p.locator('.slicer-group').first().boundingBox();await p.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await p.mouse.down();await p.mouse.move(handle.x+handle.width/2+bounds.width*.2,handle.y+handle.height/2+bounds.height*.3,{steps:5});await p.mouse.up();const resized=await state(p);for(let i=0;i<2;i++){ok(Math.abs(resized.objects[i].w-before.objects[i].w*1.2)<1);ok(Math.abs(resized.objects[i].h-before.objects[i].h*1.3)<1);}eq(await p.evaluate(()=>tabula.wb().sheets[0].slicers.map(o=>o.buttonHeight??null)),[null,null]);eq(resized.undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);});
 await test('슬라이서 그룹 최소 child 크기 보장',async p=>{await choose(p,['sl','sl2']);await p.evaluate(()=>tabula.run('objGroup'));const before=await state(p),handle=await p.locator('.slicer-group .ch-h.se').first().boundingBox();await p.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await p.mouse.down();await p.mouse.move(handle.x-390,handle.y-240,{steps:5});await p.mouse.up();const after=await state(p);for(const o of after.objects.slice(0,2)){ok(o.w>=80-1e-7);ok(o.h>=56-1e-7);}eq(after.undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);});
 await test('그룹과 개별 개체 맞춤은 그룹 내부 간격 보존',async p=>{await choose(p,['sl','sl2']);await p.evaluate(()=>tabula.run('objGroup'));await obj(p,'shape').click({modifiers:['Control']});const before=await state(p);await menu(p,'아래쪽 맞춤');const after=await state(p);eq(after.objects[1].y-after.objects[0].y,before.objects[1].y-before.objects[0].y);eq(after.objects[1].x-after.objects[0].x,before.objects[1].x-before.objects[0].x);eq(after.objects[2].y+after.objects[2].h,Math.max(...after.objects.slice(0,2).map(o=>o.y+o.h)));eq(after.undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await state(p),before);});

 await test('그룹 생성은 사이 도형을 넘어 최상위 선택 위치에 연속 배치',async p=>{await p.evaluate(()=>{const s=tabula.wb().sheets[0];s.slicers[1].z=3;s.shapes[0].z=2;tabula.gv().renderObjectsAll();});await choose(p,['sl','sl2']);const stack=()=>p.evaluate(()=>[...tabula.wb().sheets[0].slicers,...tabula.wb().sheets[0].shapes].map(o=>({id:o.id,z:o.z,group:o.objectGroup??null})).sort((a,b)=>a.z-b.z));const before=await stack();eq(before.map(o=>o.id),['sl','shape','sl2','target']);await p.evaluate(()=>tabula.run('objGroup'));const grouped=await stack();eq(grouped.map(o=>o.id),['shape','sl','sl2','target']);ok(grouped[1].group&&grouped[1].group===grouped[2].group);eq((await state(p)).undo,1);await p.evaluate(()=>tabula.run('undo'));eq(await stack(),before);await p.evaluate(()=>tabula.run('redo'));eq(await stack(),grouped);});
 await test('그룹 앞뒤 한 단계와 일반 개체의 그룹 건너뛰기·Undo',async p=>{await choose(p,['sl','sl2']);await p.evaluate(()=>tabula.run('objGroup'));const order=()=>p.evaluate(()=>[...tabula.wb().sheets[0].slicers,...tabula.wb().sheets[0].shapes].sort((a,b)=>a.z-b.z).map(o=>o.id));const move=async(name,label)=>{await p.evaluate(n=>tabula.openNamedMenu(n,document.querySelector('#gridView')),name);await p.getByRole('menuitem',{name:label,exact:true}).click();};const before=await state(p);await move('objForward','앞으로 가져오기');eq(await order(),['shape','sl','sl2','target']);eq((await state(p)).undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await order(),['sl','sl2','shape','target']);await obj(p,'shape').click();await move('objBackward','뒤로 보내기');eq(await order(),['shape','sl','sl2','target'],'일반 개체도 슬라이서 그룹 내부로 들어가지 않음');eq((await state(p)).undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await order(),['sl','sl2','shape','target']);});
 await test('그룹과 일반 개체 다중 앞뒤는 내부 순서·연속성 유지',async p=>{await choose(p,['sl','sl2']);await p.evaluate(()=>tabula.run('objGroup'));await obj(p,'shape').click({modifiers:['Control']});const order=()=>p.evaluate(()=>[...tabula.wb().sheets[0].slicers,...tabula.wb().sheets[0].shapes].sort((a,b)=>a.z-b.z).map(o=>o.id));const before=await state(p);await p.evaluate(()=>tabula.openNamedMenu('objForward',document.querySelector('#gridView')));await p.getByRole('menuitem',{name:'맨 앞으로 가져오기',exact:true}).click();eq(await order(),['target','sl','sl2','shape']);eq((await state(p)).undo,before.undo+1);await p.evaluate(()=>tabula.run('undo'));eq(await order(),['sl','sl2','shape','target']);});
}finally{await browser.close();}
console.log(JSON.stringify({total:results.length,passed:results.filter(r=>r.ok).length,checks,results},null,2));if(results.some(r=>!r.ok))process.exitCode=1;
