// Isolated synthetic SmartArt browser regression; no documents or network writes.
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.WIXEL_URL || 'http://127.0.0.1:5180/', browser=await chromium.launch(), results=[];
async function test(name,fn){
  const context=await browser.newContext({viewport:{width:1500,height:1000}}),p=await context.newPage(),errors=[],writes=[];
  p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*',r=>{const q=r.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(q.method());return r.abort();}return u.origin===new URL(base).origin&&!u.pathname.startsWith('/api/')?r.continue():r.abort();});
  try{
    await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;});await p.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());
    await p.evaluate(()=>{const t=window.tabula,w=t.wb();w.restore({sheets:[{name:'SmartArt 합성',cells:{'0,0':{raw:'보존'}}}]});t.switchSheet(0);t.selectCell(2,2);w.undoStack=[];w.redoStack=[];});
    await fn(p);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);assert.equal(await p.evaluate(()=>window.tabula.wb().getRaw(0,0,0)),'보존');results.push({name,ok:true});console.log('OK '+name);
  }catch(e){results.push({name,ok:false,error:e.message,errors,writes});console.error('NG '+name+' '+e.stack);}finally{await context.close();}
}
const dialog=p=>p.getByRole('dialog',{name:'SmartArt 그래픽',exact:true});
const shapes=p=>p.evaluate(()=>structuredClone(window.tabula.wb().sheets[0].shapes));
const run=(p,c)=>p.evaluate(c=>window.tabula.run(c),c);
async function open(p){await run(p,'insertSmartArt');await dialog(p).waitFor();return dialog(p);}
async function create(p){const d=await open(p);await d.getByRole('button',{name:'확인',exact:true}).click();return (await shapes(p))[0];}
async function edit(p){await run(p,'editSmartArt');await dialog(p).waitFor();return dialog(p);}
try{
  await test('8범주20갤러리와삽입취소',async p=>{const d=await open(p),c=d.getByLabel('SmartArt 범주');const opts=await c.locator('option').allTextContents();assert.equal(opts.length,8);let count=0;for(const x of opts){await c.selectOption({label:x});count+=await d.locator('.sa-layout').count();}assert.equal(count,20);await d.getByRole('button',{name:'취소',exact:true}).click();assert.equal((await shapes(p)).length,0);});
  await test('삽입SVG·한번UndoRedo',async p=>{const s=await create(p);assert.equal(s.kind,'smartart');assert.equal(await p.locator('.obj [data-smartart-node]').count(),3);assert.equal(await p.evaluate(()=>window.tabula.wb().undoStack.length),1);await run(p,'undo');assert.equal((await shapes(p)).length,0);await run(p,'redo');assert.equal((await shapes(p)).length,1);});
  await test('텍스트·항목추가삭제·수준·순서·취소',async p=>{const before=await create(p),d=await edit(p);await d.getByLabel('항목 1 텍스트',{exact:true}).fill('첫 제목');await d.getByRole('button',{name:'항목 추가',exact:true}).click();assert.equal(await d.locator('.sa-text-row').count(),4);await d.getByRole('button',{name:'수준 내리기',exact:true}).click();assert.match(await d.locator('.sa-text-row.on').getAttribute('style'),/14px/);await d.getByRole('button',{name:'수준 올리기',exact:true}).click();await d.getByRole('button',{name:'아래로 이동',exact:true}).click();await d.getByRole('button',{name:'위로 이동',exact:true}).click();await d.getByRole('button',{name:'항목 삭제',exact:true}).click();assert.equal(await d.locator('.sa-text-row').count(),3);await d.getByRole('button',{name:'취소',exact:true}).click();assert.deepEqual((await shapes(p))[0],before);});
  await test('텍스트·색·스타일확인1Undo·배율크기',async p=>{const before=await create(p),d=await edit(p);await d.getByLabel('항목 1 텍스트',{exact:true}).fill('수정한 제목');await d.getByLabel('SmartArt 색 변경').selectOption('2');await d.getByLabel('SmartArt 스타일').selectOption('shadow');await d.getByRole('button',{name:'확인',exact:true}).click();let s=(await shapes(p))[0];assert.equal(s.smartArt.nodes[0].text,'수정한 제목');assert.equal(s.smartArt.style,'shadow');assert.equal(s.smartArt.palette[0],'#375623');await run(p,'undo');assert.deepEqual((await shapes(p))[0],before);await run(p,'redo');
    const handle=p.locator(`.obj[data-id="${s.id}"] .ch-h.se`).first(),box=await handle.boundingBox();assert.ok(box);await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+80,box.y+box.height/2+40,{steps:8});await p.mouse.up();s=(await shapes(p))[0];assert.ok(s.w>before.w+30);assert.deepEqual(s.smartArt.nodes.map(n=>n.text),['수정한 제목','항목 2','항목 3']);
    for(const zoom of [50,125,100]){await p.evaluate(z=>{const g=window.tabula.gv();g.setZoom(z);g.renderAll();},zoom);const b=await p.locator(`.obj[data-id="${s.id}"] svg[aria-label="SmartArt"]`).first().boundingBox();assert.ok(Math.abs(b.width-s.w*zoom/100)<2,'배율에 맞는 SVG 크기');}
    await p.screenshot({path:process.env.WIXEL_SMARTART_SCREENSHOT||'D:/Codex/Temp/wixel-smartart.png'});
  });
  await test('로컬그림선택·그림배치·저장모델',async p=>{const d=await open(p);const png=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=120;c.height=80;const g=c.getContext('2d');g.fillStyle='#008899';g.fillRect(0,0,120,80);return c.toDataURL();});await d.getByLabel('선택 항목 그림 파일').setInputFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from(png.split(',')[1],'base64')});await p.waitForFunction(()=>document.querySelector('.sa-preview image'));await d.getByRole('button',{name:'확인',exact:true}).click();const s=(await shapes(p))[0];assert.equal(s.smartArt.layout,'pictureCards');assert.match(s.smartArt.nodes[0].picture,/^data:image\/png;base64,/);assert.equal(await p.locator('.obj image').count(),1);});
  await test('일반그룹변환과Undo',async p=>{await create(p);const d=await edit(p);await d.getByRole('button',{name:'일반 도형으로 변환',exact:true}).click();assert.equal((await shapes(p))[0].kind,'group');assert.ok((await shapes(p))[0].groupItems.length>=3);await run(p,'undo');assert.equal((await shapes(p))[0].kind,'smartart');});
  await test('보호시트삽입과열린편집창후보호변경차단',async p=>{await p.evaluate(()=>{const t=window.tabula;t.wb().setSheetProp(0,'protect',{on:true,allow:{}});});await run(p,'insertSmartArt');assert.equal(await dialog(p).count(),0);assert.equal((await shapes(p)).length,0);await p.evaluate(()=>window.tabula.wb().setSheetProp(0,'protect',null));await create(p);const d=await edit(p);await d.getByLabel('항목 1 텍스트',{exact:true}).fill('차단돼야 함');await p.evaluate(()=>window.tabula.wb().setSheetProp(0,'protect',{on:true,allow:{}}));await d.getByRole('button',{name:'확인',exact:true}).click();assert.equal(await dialog(p).count(),1);assert.notEqual((await shapes(p))[0].smartArt.nodes[0].text,'차단돼야 함');await d.getByRole('button',{name:'취소',exact:true}).click();});
  await test('열린창문서전환은다른문서에삽입하지않음',async p=>{const d=await open(p);await p.evaluate(()=>{const t=window.tabula;t.wb().restore({sheets:[{name:'다른 합성',cells:{'0,0':{raw:'보존'}}}]});});await d.getByRole('button',{name:'확인',exact:true}).click();assert.equal((await shapes(p)).length,0);assert.equal(await dialog(p).count(),1);await d.getByRole('button',{name:'취소',exact:true}).click();});
  await test('좌우·상하대칭메뉴가SVG에반영되고Undo된다',async p=>{const s=await create(p);for(const label of ['좌우 대칭','상하 대칭']){await p.evaluate(()=>window.tabula.openNamedMenu('objRotate',{x:300,y:150}));await p.getByRole('menuitem',{name:label,exact:true}).click();}const after=(await shapes(p))[0];assert.equal(after.flip,true);assert.equal(after.flipV,true);const transform=await p.locator(`.obj[data-id="${s.id}"] svg[aria-label="SmartArt"] > g`).first().getAttribute('transform');assert.match(transform,/scale\(-1,-1\)/);await run(p,'undo');assert.equal((await shapes(p))[0].flipV,undefined);assert.equal((await shapes(p))[0].flip,true);});
}finally{await browser.close();}
console.log(JSON.stringify({total:results.length,passed:results.filter(x=>x.ok).length,results},null,2));if(results.some(x=>!x.ok))process.exitCode=1;
