// 합성 문서만 사용한 데이터 유효성 검사 UI 회귀. 사용자 탭·클립보드·원격 문서에 접근하지 않는다.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const url=process.env.WIXEL_URL||'http://127.0.0.1:5191/',out=process.env.WIXEL_VALIDATION_OUT||'D:/Codex/Temp/wixel-validation/source',only=process.env.WIXEL_VALIDATION_FILTER||'';
await mkdir(out,{recursive:true});
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:1000}}),p=await context.newPage();
const results=[],errors=[],writes=[],blocked=[];let checks=0,assets=[];
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);},ok=(a,m)=>{checks++;assert.ok(a,m);};
p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.dismiss());
await context.addInitScript(()=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;localStorage.setItem('wixel:version','3.0.0');Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>'',writeText:async()=>{}}});});
await context.route('**/*',route=>{const q=route.request(),u=new URL(q.url());if(!['GET','HEAD','OPTIONS'].includes(q.method())){writes.push(u.pathname);return route.abort();}if(u.origin!==new URL(url).origin||u.pathname.startsWith('/api/')){blocked.push(u.pathname);return route.abort();}return route.continue();});
const run=cmd=>p.evaluate(cmd=>window.tabula.run(cmd),cmd),d=()=>p.getByRole('dialog',{name:'데이터 유효성',exact:true}),field=name=>d().locator('[name="'+name+'"]'),tab=name=>d().getByRole('tab',{name,exact:true});
const confirm=()=>d().getByRole('button',{name:'확인',exact:true}).click(),cancel=()=>d().getByRole('button',{name:'취소',exact:true}).click();
const rules=()=>p.evaluate(()=>window.tabula.wb().sheets.map(s=>s.validations||[])),undoCount=()=>p.evaluate(()=>window.tabula.wb().undoStack.length),raw=(r=1,c=1)=>p.evaluate(([r,c])=>window.tabula.wb().getRaw(0,r,c),[r,c]);
function fixture(){return{sheets:[{name:'검증 합성',cells:{'0,0':{raw:'사과'},'1,0':{raw:'배'},'2,0':{raw:'포도'},'1,1':{raw:'5'},'2,1':{raw:'25'},'3,1':{raw:'10'},'4,1':{raw:'4'},'0,3':{raw:'5'}}},{name:'다른 합성',cells:{'1,1':{raw:'다른 값'}}}]};}
const baseRule=(extra={})=>({r1:1,c1:1,r2:4,c2:1,type:'whole',op:'between',f1:'1',f2:'10',allowBlank:true,showPrompt:true,showError:true,errorStyle:'stop',...extra});
async function reset(){for(let i=0;i<5;i++)await p.keyboard.press('Escape');for(const b of await p.locator('#dialogLayer .dialog-head button[aria-label="닫기"]').all())await b.click();await p.setViewportSize({width:1440,height:1000});await p.evaluate(data=>{const t=window.tabula;if(t.mobile().active)t.run('mobileWorkMode');t.run('clearCircles');t.selectCell(0,0);const w=t.wb();w.restore(data);w.setSnapshots(data);t.switchSheet(1);t.switchSheet(0);t.selectRange({r1:1,c1:1,r2:4,c2:1});t.gv().layout();t.gv().renderAll();w.undoStack=[];w.redoStack=[];},fixture());}
async function setRules(list){await p.evaluate(list=>{const t=window.tabula,w=t.wb();w.transact(()=>w.setSheetProp(0,'validations',list));w.undoStack=[];w.redoStack=[];},list);}
async function open(){await p.locator('[data-ribbon-tab="data"]').click();const control=p.locator('#ribbon [data-ribbon-command="dataValidation"]');await control.scrollIntoViewIfNeeded();await control.click();await d().waitFor();}
async function configure(type,op='between',f1='1',f2='10'){await field('type').selectOption(type);if(await field('op').isVisible())await field('op').selectOption(op);if(await field('f1').isVisible())await field('f1').fill(f1);if(await field('f2').isVisible())await field('f2').fill(f2);}
async function edit(value,r=1,c=1){await p.evaluate(([r,c])=>window.tabula.selectCell(r,c),[r,c]);await p.locator('#cellEditor').focus();await p.keyboard.press('F2');await p.locator('#cellEditor').fill(value);await p.keyboard.press('Enter');}
async function closeError(button='취소'){const alert=p.getByRole('dialog').last();await alert.waitFor();await alert.getByRole('button',{name:button,exact:true}).click();}
async function assertRule(value){const rule=(await rules())[0][0];for(const [key,v]of Object.entries(value))eq(rule?.[key],v,key);}
async function test(name,fn){if(only&&!name.includes(only))return;const start=checks,startErrors=errors.length;try{await reset();await fn();eq(errors.slice(startErrors),[],'페이지 오류 없음');results.push({name,ok:true,checks:checks-start});console.log('OK '+name);}catch(e){results.push({name,ok:false,error:e.message,checks:checks-start});console.error('NG '+name+' '+e.stack);await p.screenshot({path:out+'/failure-'+results.length+'.png'}).catch(()=>{});}}
try{
await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb());assets=await p.locator('script[src]').evaluateAll(a=>a.map(e=>new URL(e.src).pathname));
await test('리본 메뉴의 세 명령과 네 탭은 실제 대화상자에 연결된다',async()=>{await p.locator('[data-ribbon-tab="data"]').click();await p.locator('#ribbon [data-ribbon-menu="validation"] .caret').click();const m=p.locator('#menuLayer .menu').last();for(const label of ['데이터 유효성 검사','잘못된 데이터','유효성 표시 지우기'])ok(await m.getByRole('menuitem',{name:new RegExp(label)}).isVisible(),label);await m.getByRole('menuitem',{name:/데이터 유효성 검사/}).click();eq(await d().getByRole('tab').allTextContents(),['설정','설명 메시지','오류 메시지','IME 모드']);eq(await field('type').locator('option').count(),8);eq(await field('op').locator('option').count(),8);await p.screenshot({path:out+'/settings.png'});await cancel();eq(await undoCount(),0);});
for(const spec of [
{type:'whole',f1:'1',f2:'10',good:'7',bad:'1.5'},
{type:'decimal',f1:'0.1',f2:'1.5',good:'0.75',bad:'2'},
{type:'list',f1:'사과,배,포도',good:'배',bad:'감'},
{type:'date',f1:'2026-01-01',f2:'2026-12-31',good:'2026-06-01',bad:'2027-01-01'},
{type:'time',f1:'09:00',f2:'18:00',good:'12:30',bad:'20:00'},
{type:'textLength',f1:'2',f2:'4',good:'위셀',bad:'너무긴텍스트'},
{type:'custom',f1:'=B2>0',good:'8',bad:'-1'},
])await test(({whole:'정수',decimal:'소수점',list:'목록',date:'날짜',time:'시간',textLength:'텍스트 길이',custom:'사용자 지정'})[spec.type]+' 조건은 실제 입력을 허용·차단하고 한 번 Undo된다',async()=>{await open();await configure(spec.type,'between',spec.f1,spec.f2);await confirm();await d().waitFor({state:'detached'});await assertRule({type:spec.type});eq(await undoCount(),1);const before=await raw();await edit(spec.good);await p.waitForFunction(()=>document.querySelector('#cellEditor').classList.contains('idle'));eq(await raw(),spec.good);await edit(spec.bad);await p.getByRole('dialog').last().waitFor();eq(await raw(),spec.good,'불허 입력 미반영');await closeError();eq(await raw(),spec.good);await run('undo');eq(await raw(),before,'유효 입력 Undo');await run('undo');eq((await rules())[0],[],'설정 Undo');});
await test('모든 값은 기존 제한을 없애고 셀 값은 보존한다',async()=>{await setRules([baseRule()]);await open();await field('type').selectOption('any');await confirm();eq((await rules())[0],[]);eq(await raw(),'5');eq(await undoCount(),1);await run('undo');await assertRule({type:'whole'});});
await test('여덟 제한 방법은 선택한 연산과 범위를 저장하고 입력에 적용한다',async()=>{for(const [op,good,bad]of [['between','7','11'],['notBetween','11','7'],['equal','5','6'],['notEqual','6','5'],['greaterThan','6','5'],['lessThan','4','5'],['greaterThanOrEqual','5','4'],['lessThanOrEqual','5','6']]){await p.evaluate(()=>window.tabula.selectRange({r1:1,c1:1,r2:4,c2:1}));await open();await configure('whole',op,op==='between'||op==='notBetween'?'1':'5','10');eq(await field('f2').isVisible(),['between','notBetween'].includes(op));await confirm();await assertRule({op});await edit(good);await p.waitForFunction(()=>document.querySelector('#cellEditor').classList.contains('idle'));eq(await raw(),good);await edit(bad);await p.getByRole('dialog').last().waitFor();await closeError();eq(await raw(),good);}});
await test('설명 메시지와 길이 제한은 저장·표시·비활성 상태에 반영된다',async()=>{await open();await configure('whole');await tab('설명 메시지').click();eq(await field('promptTitle').getAttribute('maxlength'),'32');eq(await field('prompt').getAttribute('maxlength'),'255');await field('promptTitle').fill('입력 안내');await field('prompt').fill('1부터 10까지 입력하세요.');await p.screenshot({path:out+'/input-message.png'});await confirm();await p.evaluate(()=>window.tabula.selectCell(2,1));await p.locator('.dv-prompt').waitFor();ok((await p.locator('.dv-prompt').innerText()).includes('입력 안내'));ok((await p.locator('.dv-prompt').innerText()).includes('1부터 10'));await open();await tab('설명 메시지').click();await field('showPrompt').uncheck();eq(await field('promptTitle').isDisabled(),true);await confirm();eq(await p.locator('.dv-prompt').count(),0);});
for(const style of ['stop','warning','info'])await test(({stop:'중지',warning:'경고',info:'정보'})[style]+' 오류 메시지는 실제 재시도·취소·허용 동작을 구분한다',async()=>{await open();await configure('whole');await tab('오류 메시지').click();eq(await field('errorTitle').getAttribute('maxlength'),'32');eq(await field('error').getAttribute('maxlength'),'225');await field('errorStyle').selectOption(style);await field('errorTitle').fill('합성 입력 제한');await field('error').fill('1부터 10 사이의 정수를 입력하세요.');if(style==='stop')await p.screenshot({path:out+'/error-message.png'});await confirm();await edit('99');const e=p.getByRole('dialog',{name:'합성 입력 제한',exact:true});await e.waitFor();eq(await raw(),'5');ok((await e.innerText()).includes('1부터 10 사이'));if(style==='stop'){await e.getByRole('button',{name:/^다시 시도(?:\(R\))?$/}).click();await p.locator('#cellEditor').fill('7');await p.keyboard.press('Enter');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='7');}else{await e.getByRole('button',{name:style==='warning'?/^예(?:\(Y\))?$/:/^확인$/}).click();await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='99');}await run('undo');eq(await raw(),'5');await edit('99');await p.getByRole('dialog',{name:'합성 입력 제한',exact:true}).getByRole('button',{name:'취소',exact:true}).click();eq(await raw(),'5');});
await test('오류 표시를 끄면 제한 밖 입력이 허용되며 설정은 유지된다',async()=>{await open();await configure('whole');await tab('오류 메시지').click();await field('showError').uncheck();eq(await field('errorStyle').isDisabled(),true);await confirm();await edit('99');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='99');eq(await p.getByRole('dialog').count(),0);await assertRule({showError:false,type:'whole'});});
await test('IME 모드 메타데이터는 선택·재열기·실행 취소로 보존된다',async()=>{await open();await configure('whole');await tab('IME 모드').click();eq(await field('imeMode').locator('option').evaluateAll(a=>a.map(e=>e.value).sort()),['noControl','on','off','disabled','hiragana','fullKatakana','halfKatakana','fullAlpha','halfAlpha','fullHangul','halfHangul'].sort());await field('imeMode').selectOption('fullHangul');await p.screenshot({path:out+'/ime.png'});await confirm();await assertRule({imeMode:'fullHangul'});await open();await tab('IME 모드').click();eq(await field('imeMode').inputValue(),'fullHangul');await cancel();await run('undo');eq((await rules())[0],[]);});
await test('동일 설정 적용은 떨어진 같은 규칙만 변경하고 한 번 Undo된다',async()=>{const a=baseRule(),b=baseRule({r1:1,c1:3,r2:2,c2:3}),c=baseRule({r1:6,c1:1,r2:8,c2:1,f2:'20'});await setRules([a,b,c]);await p.evaluate(()=>window.tabula.selectCell(1,1));await open();await field('applySame').check();await field('f2').fill('15');await confirm();const after=(await rules())[0];for(const [r,c]of [[1,1],[4,1],[1,3],[2,3]])eq(after.find(x=>r>=x.r1&&r<=x.r2&&c>=x.c1&&c<=x.c2)?.f2,'15','같은 설정 전체 범위');eq(after.find(x=>x.r1===6)?.f2,'20');eq(await undoCount(),1);await run('undo');eq((await rules())[0],[a,b,c]);});
await test('모두 지우기는 초안만 초기화하고 취소는 원래 규칙을 남긴다',async()=>{const a=baseRule({promptTitle:'안내',prompt:'기존 설명',imeMode:'fullHangul'});await setRules([a]);await open();await p.keyboard.press('Alt+c');await d().waitFor();eq(await field('type').inputValue(),'any');eq((await rules())[0],[a]);await cancel();eq((await rules())[0],[a]);eq(await undoCount(),0);await open();await d().getByRole('button',{name:/^모두 지우기/}).click();await confirm();eq((await rules())[0],[]);eq(await undoCount(),1);await run('undo');eq((await rules())[0],[a]);});
await test('잘못된 데이터 표시는 유효하지 않은 값만 둘러싸고 지우기는 값에 영향이 없다',async()=>{await setRules([baseRule()]);await run('circleInvalid');eq(await p.locator('.dv-circle').count(),1);eq(await raw(2,1),'25');await run('clearCircles');eq(await p.locator('.dv-circle').count(),0);eq(await undoCount(),0);eq(await raw(2,1),'25');});
await test('목록 드롭다운은 실제 선택과 실행 취소를 지원한다',async()=>{await setRules([baseRule({type:'list',f1:'사과,배,포도',showDropdown:true})]);await p.evaluate(()=>window.tabula.selectCell(1,1));await p.locator('#cellEditor').focus();await p.keyboard.press('Alt+ArrowDown');const list=p.locator('.dv-list');await list.waitFor();await list.getByRole('menuitem',{name:'배',exact:true}).click();eq(await raw(),'배');await run('undo');eq(await raw(),'5');});
await test('설정 초안의 Tab·Escape 및 IME Enter는 시트에 문자를 남기지 않는다',async()=>{await open();await configure('list','between','사과,배');const f=field('f1');await f.focus();await f.dispatchEvent('compositionstart',{data:'한'});await f.dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true,keyCode:229,bubbles:true});await d().waitFor();eq((await rules())[0],[]);await f.dispatchEvent('compositionend',{data:'한'});await p.keyboard.press('Tab');ok(await d().evaluate(e=>e.contains(document.activeElement)),'Tab은 창 안에 유지');await p.keyboard.press('Escape');eq(await d().count(),0);eq(await raw(),'5');eq(await undoCount(),0);});
await test('뒤늦은 시트 보호는 열린 설정의 적용을 차단한다',async()=>{await open();await configure('whole');await p.evaluate(()=>{window.tabula.wb().sheets[0].protect={on:true,allow:{selectLocked:true,selectUnlocked:true}};});await confirm();eq((await rules())[0],[]);eq(await undoCount(),0);});
await test('시트 전환 뒤 열린 설정은 원래 시트와 새 시트 모두 변경하지 않는다',async()=>{await open();await configure('whole');await p.evaluate(()=>window.tabula.switchSheet(1));if(await d().count())await confirm();eq(await rules(),[[],[]]);eq(await undoCount(),0);});
await test('통합 문서 복원 뒤 열린 설정은 새 문서를 변경하지 않는다',async()=>{await open();await configure('whole');await p.evaluate(()=>{const t=window.tabula;t.wb().restore({sheets:[{name:'교체 문서',cells:{'1,1':{raw:'새 값'}}}]});t.switchSheet(0);});if(await d().count())await confirm();eq((await rules())[0],[]);eq(await raw(),'새 값');});
await test('목록 원본 범위 선택은 격자 드래그·완료·취소 뒤 적용 대상을 보존한다',async()=>{await open();await configure('list','between','사과,배');await d().getByRole('button',{name:'원본 범위 선택',exact:true}).click();await d().getByRole('textbox',{name:'범위 참조',exact:true}).waitFor();const point=async(r,c)=>p.evaluate(([r,c])=>{const b=window.tabula.gv().clientRect({r1:r,c1:c,r2:r,c2:c});return{x:b.left+b.width/2,y:b.top+b.height/2};},[r,c]);let a=await point(0,0),b=await point(2,0);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:5});await p.mouse.up();ok((await d().getByRole('textbox',{name:'범위 참조',exact:true}).inputValue()).replaceAll('$','').includes('A1:A3'),'실제 격자 범위 입력');await d().getByRole('button',{name:'범위 선택 완료',exact:true}).click();const chosen=await field('f1').inputValue();await d().getByRole('button',{name:'원본 범위 선택',exact:true}).click();await d().getByRole('textbox',{name:'범위 참조',exact:true}).fill('=D1:D3');await p.keyboard.press('Escape');eq(await field('f1').inputValue(),chosen,'picker 취소');await confirm();await assertRule({r1:1,c1:1,r2:4,c2:1,type:'list'});eq(await raw(0,0),'사과');await edit('배');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='배');await run('undo');await run('undo');eq((await rules())[0],[]);});
await test('잘못된 조건·역전 범위·잘못된 수식은 설정을 저장하지 않는다',async()=>{await open();for(const [type,f1,f2]of [['whole','','10'],['whole','10','1'],['date','없는 날짜','2026-12-31'],['time','25:00','26:00'],['custom','=SUM(','']]){await configure(type,'between',f1,f2);await confirm();await d().waitFor();ok(await d().getByRole('alert').isVisible(),'구체적인 설정 오류');eq((await rules())[0],[]);eq(await undoCount(),0);}await cancel();});
await test('탭 방향키·Ctrl Tab·Alt 접근키는 입력 초점을 정확히 이동한다',async()=>{await open();await p.keyboard.press('Alt+a');eq(await field('type').evaluate(e=>document.activeElement===e),true);await tab('설정').focus();await p.keyboard.press('ArrowRight');eq(await tab('설명 메시지').getAttribute('aria-selected'),'true');await p.keyboard.press('Control+Tab');eq(await tab('오류 메시지').getAttribute('aria-selected'),'true');await p.keyboard.press('Control+Shift+Tab');eq(await tab('설명 메시지').getAttribute('aria-selected'),'true');await p.keyboard.press('Escape');eq(await d().count(),0);eq(await raw(),'5');});
await test('대상 선택을 바꾸면 열린 설정의 적용은 차단된다',async()=>{await open();await configure('whole');await p.evaluate(()=>window.tabula.selectCell(0,3));await confirm();eq((await rules())[0],[]);eq(await undoCount(),0);});
await test('수식 입력도 계산 결과가 제한을 벗어나면 원본 값을 보존한다',async()=>{await setRules([baseRule()]);await edit('=20+20');await p.getByRole('dialog').last().waitFor();eq(await raw(),'5');await closeError();eq(await undoCount(),0);await edit('=2+3');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='=2+3');eq(await p.evaluate(()=>window.tabula.wb().getValue(0,1,1)),5);await run('undo');eq(await raw(),'5');});
await test('공백 무시와 목록 단추 표시는 서로 독립적으로 적용된다',async()=>{await open();await configure('whole');await field('allowBlank').uncheck();await confirm();await edit('');await p.getByRole('dialog').last().waitFor();eq(await raw(),'5');await closeError();await open();await field('allowBlank').check();await confirm();await edit('');await p.waitForFunction(()=>window.tabula.wb().getRaw(0,1,1)==='');eq(await raw(),'');await p.evaluate(()=>window.tabula.selectCell(1,1));await open();await configure('list','between','사과,배');await field('showDropdown').uncheck();await confirm();await p.evaluate(()=>window.tabula.selectCell(1,1));eq(await p.locator('.dv-btn[title="목록에서 선택"]').count(),0);await open();await field('showDropdown').check();await confirm();eq(await p.locator('.dv-btn[title="목록에서 선택"]').count(),1);});
await test('정의된 이름을 목록 원본으로 지정하면 실제 셀 목록이 열린다',async()=>{await p.evaluate(()=>{window.tabula.wb().names=[{name:'과일목록',ref:"'검증 합성'!$A$1:$A$3",sheet:null}];});await open();await configure('list','between','=과일목록');await confirm();await p.evaluate(()=>window.tabula.selectCell(1,1));await p.locator('#cellEditor').focus();await p.keyboard.press('Alt+ArrowDown');const list=p.locator('.dv-list');await list.waitFor();eq(await list.getByRole('menuitem').allTextContents(),['사과','배','포도']);await list.getByRole('menuitem',{name:'포도',exact:true}).click();eq(await raw(),'포도');});
await test('경고 중 시트 전환은 차단되고 뒤늦은 보호는 불허 입력을 버린다',async()=>{await setRules([baseRule({errorStyle:'warning'})]);await edit('99');let alert=p.getByRole('dialog').last();await alert.waitFor();await p.evaluate(()=>window.tabula.switchSheet(1));eq(await p.evaluate(()=>window.tabula.si),0,'불허 입력 해결 전 시트 전환 차단');eq(await raw(),'5');await alert.getByRole('button',{name:'취소',exact:true}).click();await edit('99');alert=p.getByRole('dialog').last();await alert.waitFor();await p.evaluate(()=>{window.tabula.wb().sheets[0].protect={on:true,allow:{selectLocked:true,selectUnlocked:true}};});await alert.getByRole('button',{name:/^예(?:\(Y\))?$/}).click();await p.waitForTimeout(30);eq(await raw(),'5');eq(await p.evaluate(()=>window.tabula.wb().getRaw(1,1,1)),'다른 값');eq(await undoCount(),0);});
await test('목록의 표시 문구와 별개로 원본 숫자 정밀도와 수식처럼 보이는 문자열을 보존한다',async()=>{await p.evaluate(()=>{const w=window.tabula.wb();w.transact(()=>{w.setInput(0,0,0,'0.123456789');w.setStyle(0,0,0,{numFmt:'percent',decimals:0});w.setCellData(0,1,0,{raw:'=1+2',inputType:'text'});});});await setRules([baseRule({type:'list',f1:'=$A$1:$A$2',showDropdown:true})]);const show=async()=>{await p.evaluate(()=>window.tabula.selectCell(1,1));await p.locator('#cellEditor').focus();await p.keyboard.press('Alt+ArrowDown');await p.locator('.dv-list').waitFor();};await show();await p.locator('.dv-list').getByRole('menuitem',{name:'12%',exact:true}).click();eq(await p.evaluate(()=>window.tabula.wb().getValue(0,1,1)),0.123456789,'원본 소수 정밀도');eq(await undoCount(),1);await run('undo');eq(await raw(),'5');await show();await p.locator('.dv-list').getByRole('menuitem',{name:'=1+2',exact:true}).click();eq(await p.evaluate(()=>window.tabula.wb().getValue(0,1,1)),'=1+2','문자열을 수식으로 실행하지 않음');eq(await p.evaluate(()=>!!window.tabula.wb().getCell(0,1,1).formula),false);await run('undo');eq(await raw(),'5');});
await test('참조가 깨진 목록은 원본 오류를 표시하고 값을 변경하지 않는다',async()=>{await setRules([baseRule({type:'list',f1:'=없는범위',showDropdown:true})]);await p.evaluate(()=>window.tabula.selectCell(1,1));await p.locator('#cellEditor').focus();await p.keyboard.press('Alt+ArrowDown');const list=p.locator('.dv-list');await list.waitFor();eq(await list.getByRole('menuitem').count(),0);const text=await list.locator('.cell-pick-status').innerText();ok(text.includes('원본'),'원본 오류 설명');ok(text!=='선택할 항목이 없습니다.','일반 빈 목록과 구분');await p.keyboard.press('Escape');eq(await raw(),'5');eq(await undoCount(),0);});
for(const width of [390,320])await test(width+'px 모바일에서 네 탭·설정 입력·확인·취소를 사용할 수 있다',async()=>{await p.setViewportSize({width,height:844});await p.evaluate(()=>{if(!window.tabula.mobile().active)window.tabula.run('mobileWorkMode');});await run('dataValidation');await d().waitFor();for(const name of ['설정','설명 메시지','오류 메시지','IME 모드']){await tab(name).scrollIntoViewIfNeeded();await tab(name).click();const box=await d().boundingBox();ok(box.x>=-1&&box.x+box.width<=width+1,name+' 가로 범위');ok(await d().evaluate(e=>e.scrollWidth<=e.clientWidth+2),'창 가로 넘침 없음');}await tab('설정').click();await configure('list','between','사과,배');const b=d().getByRole('button',{name:'확인',exact:true});await b.scrollIntoViewIfNeeded();const box=await b.boundingBox();ok(box.y>=0&&box.y+box.height<=844&&box.x>=0&&box.x+box.width<=width);await p.screenshot({path:out+'/mobile-'+width+'.png'});await confirm();await assertRule({type:'list'});await run('dataValidation');await cancel();eq(await undoCount(),1);});
}finally{await browser.close();const result={url,assets,cases:results.length,passed:results.filter(x=>x.ok).length,checks,pageErrors:errors,remoteWrites:writes,blockedRequests:blocked,results};await writeFile(out+'/result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));if(results.some(x=>!x.ok)||errors.length||writes.length)process.exitCode=1;}
