// Synthetic browser regressions for the font catalogue, rendering, and delayed downloads.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {Workbook} from '../src/workbook.js';
import {writeXlsx,readXlsx} from '../src/xlsx.js';
const engine=process.env.WIXEL_BROWSER||'chromium',url=process.env.WIXEL_URL||'http://localhost:5178/',origin=new URL(url).origin;
const output=process.env.WIXEL_OUTPUT||`D:/Codex/Temp/wixel-web-fonts-${engine}`,filter=process.env.WIXEL_FILTER||'';
assert.ok(['localhost','127.0.0.1','[::1]'].includes(new URL(url).hostname)||(process.env.WIXEL_FONTS_PUBLIC==='1'&&origin==='https://wixel-3.wizx.workers.dev'),'Explicit synthetic test target required');
assert.ok(['chromium','firefox','webkit'].includes(engine));
const pw=await import(process.env.PLAYWRIGHT_MODULE||'playwright');await mkdir(output,{recursive:true});
const browser=await pw[engine].launch(),results=[],assets=new Set();let checks=0;
const eq=(a,b,m)=>{checks++;assert.deepEqual(a,b,m);},ok=(v,m)=>{checks++;assert.ok(v,m);};
const fontHosts=new Set(['fonts.googleapis.com','fonts.gstatic.com','cdn.jsdelivr.net']);
const frame=p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const command=async(p,cmd,arg)=>{await p.evaluate(({cmd,arg})=>tabula.run(cmd,arg),{cmd,arg});await frame(p);};
const state=p=>p.evaluate(()=>({data:JSON.stringify(tabula.wb().serialize()),version:tabula.wb().version,undo:tabula.wb().undoStack.length,redo:tabula.wb().redoStack.length}));
const style=p=>p.evaluate(()=>tabula.wb().styleAt(0,0,0));
const fixture={defaultFont:{name:'Arial',size:11},sheets:[{name:'Synthetic fonts',cells:{'0,0':{raw:'Wixel 가나다 123'},'1,0':{raw:'Unchanged'}}},{name:'Second',cells:{}}]};
async function install(p,data=fixture){await p.evaluate(data=>{const t=tabula,w=t.wb();w.restore(data);t.switchSheet(1);t.switchSheet(0);t.selectCell(0,0);t.gv().setZoom(100);t.gv().setScroll(0,0);t.gv().layout();t.gv().renderAll();w.undoStack=[];w.redoStack=[];},data);await frame(p);}
async function openMenu(p,mini=false){if(mini){const pt=await p.evaluate(()=>{const r=tabula.gv().clientRect({r1:0,c1:0,r2:0,c2:0});return{x:r.left+r.width/2,y:r.top+r.height/2};});await p.mouse.click(pt.x,pt.y,{button:'right'});await p.locator('.mini-font-picker button').click();}else{const b=p.locator('#ribbon .font-caret');await b.scrollIntoViewIfNeeded();await b.click();}await p.locator('.font-menu').waitFor();}
async function pick(p,name,{mini=false,query=name,enter=false}={}){await openMenu(p,mini);await p.locator('.font-search').fill(query);if(enter)await p.locator('.font-search').press('Enter');else await p.locator('.font-item[data-font-family="'+name.replace(/"/g,'\\"')+'"]').first().click();await frame(p);}
async function loaded(p,name){await p.waitForFunction(name=>[...document.fonts].some(f=>f.family.replace(/^["']|["']$/g,'')===name&&f.status==='loaded'),name,{timeout:60000});return p.evaluate(name=>[...document.fonts].filter(f=>f.family.replace(/^["']|["']$/g,'')===name).map(f=>({family:f.family,status:f.status,weight:f.weight})),name);}
async function openBytes(p,bytes,name){await p.evaluate(()=>{window.__previousFontBook=tabula.wb();});await p.locator('#fileInput').setInputFiles({name,mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(bytes)});await p.waitForFunction(()=>tabula.wb()!==window.__previousFontBook&&!document.querySelector('.load-progress'),null,{timeout:60000});await frame(p);}
async function test(name,fn,{mobile=false}={}){
 if(filter&&!filter.split('|').some(f=>name.includes(f)))return;
 const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1400,height:960},hasTouch:mobile,...(engine==='firefox'?{}:{isMobile:mobile}),serviceWorkers:'block',acceptDownloads:true}),p=await context.newPage();
 const errors=[],writes=[],blocked=[],requests=[],responses=[],start=checks,started=Date.now();let release=()=>{},gate=null,failFonts=false;
 const control={hold(){gate=new Promise(r=>release=r);},release(){gate=null;release();},fail(v){failFonts=v;},requests,responses};
 p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.type()==='beforeunload'?d.accept():d.dismiss());
 p.on('response',r=>{const u=new URL(r.url());if(fontHosts.has(u.hostname))responses.push({host:u.hostname,path:u.pathname,status:r.status(),type:r.request().resourceType()});});
 await context.addInitScript(mobile=>{window.TABULA_STATIC=true;window.WIXEL_SKIP_START=true;localStorage.setItem('wixel.mobile-work.v1',mobile?'on':'off');window.__savedFonts=[];window.showSaveFilePicker=async({suggestedName})=>({name:suggestedName,createWritable:async()=>({write:async bytes=>{window.__savedFonts=[...new Uint8Array(await new Blob([bytes]).arrayBuffer())];},close:async()=>{},abort:async()=>{}})});},mobile);
 await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(!['GET','HEAD','OPTIONS'].includes(req.method())){writes.push(req.method()+' '+u.origin+u.pathname);return route.abort();}if(u.origin===origin){if(u.pathname.startsWith('/api/'))return route.fulfill({status:404,contentType:'application/json',body:'{}'});return route.continue();}if(fontHosts.has(u.hostname)&&u.protocol==='https:'&&['stylesheet','font','fetch','other'].includes(req.resourceType())){requests.push({host:u.hostname,path:u.pathname,type:req.resourceType()});if(gate)await gate;if(failFonts)return route.abort('internetdisconnected');return route.continue();}blocked.push(u.origin+u.pathname);return route.abort();});
 try{await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.tabula?.wb(),null,{timeout:30000});for(const src of await p.locator('script[src]').evaluateAll(ns=>ns.map(n=>n.getAttribute('src'))))assets.add(src);await install(p);const observations=await fn(p,control);eq(errors,[],'No page errors');eq(writes,[],'No API or external writes');eq(blocked,[],'No unrelated external requests');await p.screenshot({path:output+'/'+name+'.png'});results.push({name,ok:true,checks:checks-start,elapsed:Date.now()-started,observations,requests,responses,errors,writes,blocked});console.log('PASS '+name+' '+(checks-start));}
 catch(e){await p.screenshot({path:output+'/'+name+'-failure.png'}).catch(()=>{});results.push({name,ok:false,checks:checks-start,elapsed:Date.now()-started,error:e.stack,errors,writes,blocked,requests,responses,view:await p.evaluate(()=>({dialogs:[...document.querySelectorAll('.dialog')].map(n=>n.innerText),fontMenu:document.querySelector('.font-menu')?.innerText,font:window.tabula?.wb()?.styleAt(0,0,0)?.font})).catch(()=>null)});console.error('FAIL '+name+' '+e.message);}
 finally{control.release();await context.close();}await writeFile(output+'/result.json',JSON.stringify({engine,url,total:results.length,passed:results.filter(r=>r.ok).length,checks,assets:[...assets],results},null,2));
}
try{
 await test('catalog-search-pagination',async(p,c)=>{
  await openMenu(p);const first=await p.locator('.font-item').count();ok(first>=100&&first<180,'Initial list is bounded but contains free font catalogue');ok(await p.locator('.font-more').isVisible(),'More fonts remain accessible');const before=c.requests.length;await p.locator('.font-more').click();const second=await p.locator('.font-item').count();ok(second>first&&second<=first+120,'More button adds one bounded page');ok(c.requests.length-before<20,'Opening another page does not download every face');for(let n=0;n<3;n++)await p.locator('.font-more').click();const fifth=await p.locator('.font-item').count();ok(fifth>400&&fifth<=first+420,'Paging passes the previous 400-family ceiling');
  await p.locator('.font-search').fill('Zilla Slab');ok(await p.locator('.font-item[data-font-family="Zilla Slab"]').count()>=1,'Late alphabet family reachable by search');ok(await p.locator('.font-item').count()<20,'Search filters large catalogue');await p.locator('.font-search').fill('');await p.locator('.font-source').selectOption('korean');ok(await p.locator('.font-item').count()>15,'Korean catalogue filter');await p.locator('.font-search').fill('나눔고딕');const korean=await p.locator('.font-item[data-font-family]').evaluateAll(ns=>ns.map(n=>n.dataset.fontFamily));ok(korean.some(f=>/Nanum.?Gothic|나눔고딕/i.test(f)),'Korean aliases find canonical family');await p.keyboard.press('Escape');return{first,second,fifth,korean};
 });
 await test('web-font-real-loading',async(p,c)=>{
  c.hold();await pick(p,'Bungee');eq((await style(p)).font,'Bungee','Actual choice is persisted');const dimensions=await p.evaluate(()=>{const w=tabula.wb(),s=w.sheets[0];return JSON.stringify([s.rowHeights,s.colWidths,s.merges,w.defaultFont]);});c.release();const face=await loaded(p,'Bungee');ok(c.responses.some(r=>r.host==='fonts.gstatic.com'&&r.status===200),'Actual Google font binary downloaded');const metrics=await p.evaluate(()=>{const canvas=document.createElement('canvas'),x=canvas.getContext('2d'),s='Wixel WWW 123';x.font='48px Arial';const before=x.measureText(s).width;x.font='48px Bungee';return{before,after:x.measureText(s).width};});ok(Math.abs(metrics.after-metrics.before)>1,'Loaded family changes rendered glyph metrics');eq(await p.evaluate(()=>{const w=tabula.wb(),s=w.sheets[0];return JSON.stringify([s.rowHeights,s.colWidths,s.merges,w.defaultFont]);}),dimensions,'Font download does not change workbook geometry');const before=await state(p);await command(p,'undo');eq((await style(p)).font||'Arial','Arial','One Undo restores font');eq((await state(p)).undo,before.undo-1,'Loading adds no Undo entry');await pick(p,'Black Han Sans',{query:'검은고딕',enter:true});eq((await style(p)).font,'Black Han Sans','Korean alias Enter chooses canonical name');const koreanFace=await loaded(p,'Black Han Sans');await pick(p,'SUIT');eq((await style(p)).font,'SUIT','Official Korean CDN family can be selected');const cdnFace=await loaded(p,'SUIT');ok(c.responses.some(r=>r.host==='cdn.jsdelivr.net'&&r.type==='font'&&r.status===200),'Actual official Korean CDN font binary downloaded');return{face,metrics,koreanFace,cdnFace};
 });
 await test('mobile-ribbon-context-pickers',async p=>{
  for(const mini of [false,true]){await openMenu(p,mini);ok(await p.evaluate(()=>!document.activeElement.matches('input,textarea,select')),'Mobile opening does not summon keyboard');eq(await p.locator('.font-search').evaluate(n=>getComputedStyle(n).fontSize),'16px','Search resists automatic input zoom');const b=await p.locator('.font-menu').boundingBox();ok(b.x>=-1&&b.y>=-1&&b.x+b.width<=391&&b.y+b.height<=845,'Font menu fits mobile viewport');await p.locator('.font-search').fill('Bungee');await p.locator('.font-item[data-font-family="Bungee"]').first().click();eq((await style(p)).font,'Bungee');await command(p,'undo');eq((await style(p)).font||'Arial','Arial');}await openMenu(p,true);await p.locator('.font-search').fill('Zilla');await p.screenshot({path:output+'/mobile-filtered-fonts.png'});
 },{mobile:true});
 await test('cell-format-and-default-font-options',async p=>{
  await command(p,'formatCells',2);let d=p.getByRole('dialog',{name:'셀 서식',exact:true});await d.locator('.fc-fontlist').waitFor();ok(await d.locator('.fc-fontlist option[value="Bungee"]').count()===1,'Cell format shares web catalogue');await d.locator('.fc-fontlist').selectOption('Bungee');ok((await d.locator('.fc-fontprev').evaluate(n=>getComputedStyle(n).fontFamily)).includes('Bungee'),'Cell format preview');await d.getByRole('button',{name:/^취소/}).click();eq((await style(p)).font||'Arial','Arial','Cancel preserves style');await command(p,'formatCells',2);d=p.getByRole('dialog',{name:'셀 서식',exact:true});await d.locator('.fc-fontlist').selectOption('Bungee');await d.getByRole('button',{name:/^확인/}).click();eq((await style(p)).font,'Bungee');await command(p,'undo');eq((await style(p)).font||'Arial','Arial');await command(p,'options');d=p.getByRole('dialog',{name:'WIXEL 옵션',exact:true});const defaultFont=d.getByLabel('기본 글꼴',{exact:true});ok(await defaultFont.locator('option[value="Bungee"]').count()===1,'New workbook default font includes catalogue');await defaultFont.selectOption('Bungee');await d.getByRole('button',{name:/^취소/}).click();eq((await style(p)).font||'Arial','Arial','Default font cancellation does not edit document');
 });
 await test('shape-partial-font-choice',async p=>{
  const doc=structuredClone(fixture);doc.sheets[0].shapes=[{id:'font-shape',kind:'textbox',x:60,y:70,w:440,h:150,text:'Alpha Beta',font:'Arial',size:18,fill:'#ffffff',stroke:'#4472c4',align:'left',valign:'top',paras:[{runs:[{t:'Alpha ',font:'Arial',b:true},{t:'Beta',font:'Arial',i:true}]}]}];await install(p,doc);await p.locator('.obj[data-id="font-shape"]').first().click({position:{x:4,y:4}});await p.keyboard.press('F2');const edit=p.getByRole('textbox',{name:'도형 텍스트 편집',exact:true});await edit.waitFor();await edit.evaluate(root=>{root.focus();const t=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),a=t.nextNode(),range=document.createRange();range.setStart(a,0);range.setEnd(a,5);const s=getSelection();s.removeAllRanges();s.addRange(range);document.dispatchEvent(new Event('selectionchange'));});await pick(p,'Bungee');await edit.press('Escape');const shape=await p.evaluate(()=>tabula.wb().sheets[0].shapes[0]);eq(shape.text,'Alpha Beta','Text unchanged');const runs=shape.paras.flatMap(p=>p.runs);eq(runs.filter(r=>r.font==='Bungee').map(r=>r.t).join(''),'Alpha','Font applies only to captured selection');ok(runs.some(r=>r.t.includes('Beta')&&r.font==='Arial'&&r.i),'Other rich formatting preserved');eq((await style(p)).font||'Arial','Arial','Cell is not formatted');await command(p,'undo');eq(await p.evaluate(()=>tabula.wb().sheets[0].shapes[0].paras),doc.sheets[0].shapes[0].paras,'Single Undo restores rich text');
 });
 await test('xlsx-font-names-and-document-list',async p=>{
  const doc=structuredClone(fixture);doc.defaultFont={name:'Bungee',size:11};doc.sheets[0].cells['0,0'].style={font:'Lobster'};doc.sheets[0].rowStyles={2:{font:'Synthetic Row Family'}};doc.sheets[0].colStyles={2:{font:'Synthetic Column Family'}};doc.sheets[0].shapes=[{id:'fonts-used',kind:'textbox',x:40,y:90,w:220,h:70,text:'Shapes Runs',font:'Synthetic Shape Family',paras:[{runs:[{t:'Shapes ',font:'Synthetic Shape Family'},{t:'Runs',font:'Synthetic Run Family'}]}]}];const bytes=writeXlsx(new Workbook(doc));await openBytes(p,bytes,'synthetic-fonts.xlsx');await openMenu(p);for(const name of ['Bungee','Lobster','Synthetic Row Family','Synthetic Column Family','Synthetic Shape Family','Synthetic Run Family']){await p.locator('.font-search').fill(name);ok(await p.locator('.font-item[data-font-family="'+name+'"]').count()>0,'Used document font remains selectable: '+name);}await p.keyboard.press('Escape');await p.evaluate(()=>tabula.exportXlsx('synthetic-fonts','xlsx'));await p.waitForFunction(()=>window.__savedFonts.length>0,null,{timeout:30000});const saved=Buffer.from(await p.evaluate(()=>window.__savedFonts));await writeFile(output+'/synthetic-fonts-saved.xlsx',saved);const back=new Workbook(readXlsx(saved).data);eq(back.defaultFont.name,'Bungee');eq(back.styleAt(0,0,0).font,'Lobster');eq(back.styleAt(0,2,0).font,'Synthetic Row Family');eq(back.styleAt(0,0,2).font,'Synthetic Column Family');await openBytes(p,saved,'synthetic-fonts-reopened.xlsx');eq(await p.evaluate(()=>tabula.wb().defaultFont.name),'Bungee');eq((await style(p)).font,'Lobster');await loaded(p,'Lobster');return{bytes:saved.length};
 });
 await test('delayed-download-undo-document-safety',async(p,c)=>{
  c.hold();await pick(p,'Bungee');eq((await style(p)).font,'Bungee','Style records before network completes');await p.waitForFunction(()=>document.querySelector('link[href*="fonts.googleapis.com"],style[data-web-font]')||[...document.fonts].some(f=>f.family.includes('Bungee')),null,{timeout:15000}).catch(()=>{});await command(p,'undo');const undone=await state(p);c.release();await loaded(p,'Bungee');eq(await state(p),undone,'Delayed load cannot undo Undo or add history');c.hold();await pick(p,'Lobster');const replacement=writeXlsx(new Workbook({...fixture,sheets:[{name:'Replacement',cells:{'0,0':{raw:'Other document',style:{font:'Arial',color:'#123456'}}}}]}));await openBytes(p,replacement,'replacement-fonts.xlsx');const next=await state(p);c.release();await loaded(p,'Lobster');eq(await state(p),next,'Delayed old font completion cannot edit new document');eq((await style(p)).font||await p.evaluate(()=>tabula.wb().defaultFont.name),'Arial');
 });
 await test('desktop-mini-repeat-and-stale-document-guard',async p=>{
  const pt=await p.evaluate(()=>{const r=tabula.gv().clientRect({r1:0,c1:0,r2:0,c2:0});return{x:r.left+r.width/2,y:r.top+r.height/2};});await p.mouse.click(pt.x,pt.y,{button:'right'});const font=p.locator('.mini-font'),size=p.locator('.mini-size');await font.fill('Consolas');await font.press('Enter');await frame(p);eq((await style(p)).font,'Consolas','First mini edit applies');await size.fill('14.5');await size.press('Enter');eq((await style(p)).size,14.5,'Second edit works after first autosave gives document an ID');await p.getByRole('button',{name:'굵게',exact:true}).last().click();eq((await style(p)).bold,true,'Same mini toolbar accepts a third edit');const stale=await font.elementHandle();await p.keyboard.press('Escape');await command(p,'undo');eq((await style(p)).bold||false,false);eq((await style(p)).size,14.5);await command(p,'undo');eq((await style(p)).size||11,11);eq((await style(p)).font,'Consolas');await command(p,'undo');eq((await style(p)).font||'Arial','Arial','Three edits have three meaningful Undo records');const replacement=writeXlsx(new Workbook({...fixture,sheets:[{name:'Other mini target',cells:{'0,0':{raw:'Other book',style:{color:'#123456'}}}}]}));await openBytes(p,replacement,'other-mini-target.xlsx');const before=await state(p);await stale.evaluate(n=>{n.value='Bungee';n.dispatchEvent(new Event('change',{bubbles:true}));});await frame(p);eq(await state(p),before,'Old popup callback cannot format a different document');
 });
 await test('offline-font-name-and-retry',async(p,c)=>{
  c.fail(true);await pick(p,'Bungee');eq((await style(p)).font,'Bungee','Offline keeps selected font name');await openMenu(p);await p.locator('.font-search').fill('Bungee');await p.waitForTimeout(300);const text=await p.locator('.font-menu').innerText();ok(/실패|연결|다시|불러오지|오프라인/.test(text),'Failed loading has visible fallback or retry explanation');await p.keyboard.press('Escape');const before=await state(p);c.fail(false);await pick(p,'Bungee');await loaded(p,'Bungee');eq((await state(p)).undo,before.undo,'Retry adds no duplicate formatting history');eq((await style(p)).font,'Bungee');
 });
}finally{await browser.close();}
const report={engine,url,total:results.length,passed:results.filter(r=>r.ok).length,checks,assets:[...assets],scope:'Isolated synthetic books. Only font CDN GETs are allowed externally; API and all writes are blocked. Mobile viewport is emulated, not a physical iOS test.',results};await writeFile(output+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({engine,passed:report.passed,total:report.total,checks,assets:[...assets],output}));if(results.some(r=>!r.ok))process.exitCode=1;
