import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Workbook} from '../src/workbook.js';
import {readXlsx,writeXlsx} from '../src/xlsx.js';
import {zip,unzip,textOf} from '../src/zip.js';
import {parseXml,child,kids,descendants} from '../src/xml.js';
import {normalizeObjectStyles,findObjectStyle,upsertObjectStyle,objectStylePatch,clearObjectStyle} from '../src/object-styles.js';
import {tableCellStyle} from '../src/tables.js';
import {slicerColors,slicerCssVars,slicerStyleElements} from '../src/slicerstyle.js';
import {resolvePivot,computePivot,pivotSourceData} from '../src/pivot.js';
import {presetStyleElements} from '../src/stylepresets.js';
const table={name:'표 "& 사용자',table:true,pivot:false,elements:[{type:'wholeTable',style:{color:'#234567',bh:true,bhc:'#102030'}},{type:'headerRow',style:{fill:'#123456',color:'#ffffff',bold:true}},{type:'firstRowStripe',size:2,style:{fill:'#ffff00'}},{type:'secondRowStripe',size:1,style:{fill:'#00ffff'}}]};
const pivot={name:'피벗 사용자',table:false,pivot:true,elements:[{type:'wholeTable',style:{color:'#112233'}},{type:'pageFieldLabels',style:{fill:'#ff0000',bold:true}},{type:'pageFieldValues',style:{fill:'#00ff00',bold:false}},{type:'headerRow',style:{fill:'#123456'}},{type:'firstSubtotalRow',style:{bold:true}},{type:'totalRow',style:{fill:'#fedcba',bold:false}}]};
const slicer={name:'슬라이서 사용자',elements:[{type:'wholeTable',style:{fill:'#fefefe',font:'Arial',size:12}},{type:'headerRow',style:{fill:'#f0f0f0',color:'#112233',bold:false}},{type:'selectedItemWithData',style:{fill:'#ff0000',color:'#ffffff',bb:true,bbs:'double',bbc:'#abcdef'}},{type:'unselectedItemWithData',style:{fill:'#00ff00',italic:true}},{type:'hoveredUnselectedItemWithNoData',style:{fill:'#0000ff',color:'#ffffff'}}]};
function fixture(){const wb=new Workbook({sheets:[{name:'자료',cells:{'0,0':{raw:'지역'},'0,1':{raw:'매출'},'0,2':{raw:'제품'},'1,2':{raw:'A'},'2,2':{raw:'B'},'1,0':{raw:'서울'},'1,1':{raw:'10'},'2,0':{raw:'부산'},'2,1':{raw:'20'}}},{name:'보고서',cells:{}}]});
 wb.setObjectStyles({tables:[table,pivot,{name:'사용하지 않는 표',table:true,pivot:false,elements:[{type:'wholeTable',style:{fill:'#abcdef'}}]}],slicers:[slicer,{name:'사용하지 않는 슬라이서',elements:[]}],defaultTableStyle:table.name,defaultPivotStyle:pivot.name,defaultSlicerStyle:slicer.name});
 wb.sheets[0].tables=[{id:'t1',name:'자료표',r1:0,c1:0,r2:2,c2:2,header:true,banded:true,...objectStylePatch('table',table)}];
 wb.sheets[0].slicers=[{id:'sl1',caption:'지역',source:{kind:'table',table:'자료표',column:'지역'},x:150,y:50,w:180,h:200,...objectStylePatch('slicer',slicer)}];
 wb.sheets[1].pivot={name:'피벗1',source:'자료',range:{r1:0,c1:0,r2:2,c2:2},top:0,left:0,rows:['제품'],pages:['지역'],values:[{field:'매출',agg:'sum'}],...objectStylePatch('pivot',pivot)};
 return wb;
}
function semantic(list){return list.map(e=>({type:e.type,...(e.size?{size:e.size}:{}),style:e.style}));}
test('이름 레지스트리는 입력과 별개이며 표/피벗 이름 충돌을 막고 수정은 명시한다',()=>{const input={tables:[table],slicers:[slicer]},r=normalizeObjectStyles(input);r.tables[0].elements[0].style.color='#000000';assert.equal(input.tables[0].elements[0].style.color,'#234567');assert.throws(()=>upsertObjectStyle(input,'pivot',{...pivot,name:table.name.toUpperCase()}),/같은 이름/);const next=upsertObjectStyle(input,'table',{...table,elements:[]},{replace:true});assert.equal(next.tables.length,1);assert.equal(input.tables[0].elements.length,4);assert.equal(findObjectStyle(input,'pivot',table.name),null);const patch=objectStylePatch('slicer',slicer);patch.styleElements[0].style.fill='#000000';assert.equal(slicer.elements[0].style.fill,'#fefefe');});
test('사용자 지정 표의 2행·1행 줄무늬와 안쪽선은 실제 셀에 적용한다',()=>{const t={r1:0,c1:0,r2:6,c2:1,header:true,banded:true,...objectStylePatch('table',table)};assert.equal(tableCellStyle(t,0,0).fill,'#123456');assert.deepEqual([1,2,3,4,5,6].map(r=>tableCellStyle(t,r,1).fill),['#ffff00','#ffff00','#00ffff','#ffff00','#ffff00','#00ffff']);assert.equal(tableCellStyle(t,2,0).bb,true);assert.equal(tableCellStyle(t,2,0).bbc,'#102030');});
test('피벗 보고서 필터 두 역할과 총합계 false서식을 실제 계산 출력에 구분 적용한다',()=>{const wb=fixture(),d=wb.sheets[1].pivot,res=resolvePivot(pivotSourceData(wb,d),d),r=computePivot(res,res.def);assert.equal(r.grid[0][0].style.fill,'#ff0000');assert.equal(r.grid[0][1].style.fill,'#00ff00');assert.equal(r.grid[0][1].style.bold,false);assert.equal(r.grid.at(-1).at(-1).style.fill,'#fedcba');assert.equal(r.grid.at(-1).at(-1).style.bold,false);});
test('슬라이서 상태별 색/글꼴/선은 재사용되고 개별 스타일보다 우선한다',()=>{const sl=objectStylePatch('slicer',slicer),c=slicerColors(sl),css=slicerCssVars(sl);assert.equal(c.selFill,'#ff0000');assert.equal(c.headFill,'#f0f0f0');assert.match(css,/--sl-header-weight:400/);assert.match(css,/--sl-selected-bottom:3px double #abcdef/);assert.match(css,/--sl-hover-empty-fill:#0000ff/);assert.deepEqual(slicerStyleElements(sl),slicer.elements);});
test('지우기는 오래된 custom/styleElements가 있어도 프리셋 서식을 다시 입히지 않는다',()=>{const t={r1:0,c1:0,r2:2,c2:1,...objectStylePatch('table',table),style:'None'};assert.equal(tableCellStyle(t,0,0),null);assert.equal(slicerColors({...objectStylePatch('slicer',slicer),style:'None',custom:{selFill:'#123456'}}).selFill,'#ffffff');assert.equal(clearObjectStyle('pivot').styleDef,undefined);});
test('내장 스타일 복제 원소는 사용자 지정 렌더에서도 같은 표 셀 서식이다',()=>{for(const name of ['TableStyleMedium2','WixelTableModern1']){const t={r1:0,c1:0,r2:4,c2:3,header:true,totals:true,banded:true,firstCol:true,style:name};const other={...t,style:'복제',styleElements:presetStyleElements(name)};for(let r=0;r<5;r++)for(let c=0;c<4;c++)assert.deepEqual(tableCellStyle(other,r,c),tableCellStyle(t,r,c));}});
test('XLSX 표준 정의로 세 사용자 지정 스타일·미사용 스타일·기본값이 왕복된다',()=>{const wb=fixture(),before=wb.serialize(),bytes=writeXlsx(wb),files=unzip(bytes),styles=parseXml(textOf(files['xl/styles.xml']));assert.equal(kids(child(styles,'tableStyles'),'tableStyle').length,5);assert.equal(descendants(styles,'slicerStyle').length,2);assert.match(textOf(files['xl/tables/table1.xml']),/표 &quot;&amp; 사용자/);const data=readXlsx(bytes).data,registry=data.objectStyles;assert.ok(findObjectStyle(registry,'table','사용하지 않는 표'));assert.ok(findObjectStyle(registry,'slicer','사용하지 않는 슬라이서'));assert.equal(registry.defaultTableStyle,table.name);assert.equal(registry.defaultPivotStyle,pivot.name);assert.equal(registry.defaultSlicerStyle,slicer.name);for(const [kind,def]of [['table',table],['pivot',pivot],['slicer',slicer]])assert.deepEqual(semantic(findObjectStyle(registry,kind,def.name).elements),semantic(def.elements));assert.equal(data.sheets[0].tables[0].style,table.name);assert.equal(data.sheets[0].slicers[0].style,slicer.name);assert.ok(data.sheets[1].pivot.styleElements);assert.deepEqual(wb.serialize(),before);const again=readXlsx(writeXlsx(new Workbook(data))).data;assert.deepEqual(semantic(findObjectStyle(again.objectStyles,'pivot',pivot.name).elements),semantic(pivot.elements));});
test('표 스타일 지우기의 이름 없는 tableStyleInfo는 다시 열어도 None이다',()=>{const wb=fixture();Object.assign(wb.sheets[0].tables[0],clearObjectStyle('table'));assert.equal(readXlsx(writeXlsx(wb)).data.sheets[0].tables[0].style,'None');});
test('미편집 DXF 테마참조·지원 밖 밑줄종류와 보호는 저장시 보존된다',()=>{const wb=fixture(),files=unzip(writeXlsx(wb));let x=textOf(files['xl/styles.xml']);x=x.replace('</dxf>','<protection locked="0"/></dxf>').replace('<color rgb="FF234567"/>','<color theme="4" tint="0.25"/><u val="double"/>');files['xl/styles.xml']=x;const data=readXlsx(zip(files)).data,out=textOf(unzip(writeXlsx(new Workbook(data)))['xl/styles.xml']);assert.match(out,/<protection locked="0"\/>/);assert.match(out,/<color theme="4" tint="0.25"\/>/);assert.match(out,/<u val="double"\/>/);const e=data.objectStyles.tables[0].elements[0];e.style.color='#ff00ff';const edited=textOf(unzip(writeXlsx(new Workbook(data)))['xl/styles.xml']);assert.match(edited,/FFFF00FF/);});

test('빈 사용자 슬라이서는 파랑 기본값을 상속하지 않고 지우기는 표준 중립 스타일로 왕복된다',()=>{assert.equal(slicerColors({style:'비어 있음',styleElements:[]}).selFill,'#ffffff');const wb=fixture();Object.assign(wb.sheets[0].slicers[0],clearObjectStyle('slicer'));Object.assign(wb.sheets[1].pivot,clearObjectStyle('pivot'));const bytes=writeXlsx(wb),files=unzip(bytes),xml=textOf(files['xl/styles.xml']);assert.doesNotMatch(xml,/<x14:slicerStyleElements><\/x14:slicerStyleElements>/);assert.doesNotMatch(textOf(files['xl/pivotTables/pivotTable1.xml']),/pivotTableStyleInfo name="None"/);const out=readXlsx(bytes).data;assert.equal(out.sheets[0].slicers[0].style,'None');assert.equal(out.sheets[1].pivot.style,'None');});
test('슬라이서 보조 표 정의보다 수정한 whole/header가 저장되며 다른 종류 이름 충돌을 막는다',()=>{const data=readXlsx(writeXlsx(fixture())).data,wb=new Workbook(data),sl=findObjectStyle(wb.objectStyles,'slicer',slicer.name);sl.elements[0].style.fill='#334455';Object.assign(wb.sheets[0].slicers[0],objectStylePatch('slicer',sl));const again=readXlsx(writeXlsx(wb)).data;assert.equal(findObjectStyle(again.objectStyles,'slicer',slicer.name).elements[0].style.fill,'#334455');assert.throws(()=>upsertObjectStyle({tables:[table]},'slicer',{name:table.name,elements:[]}),/같은 이름/);});
test('사용자 지정 글꼴·채움·숫자·대각선은 셀 적용과 XLSX 표준 DXF에 보존된다',()=>{const style={font:'Arial',size:14,bold:false,italic:true,underline:true,strike:true,fill:'#ffffff',pattern:'darkGrid',patternColor:'#334455',numFmt:'custom',code:'#,##0.000;[Red](#,##0.000)',dd:true,dds:'dashed',ddc:'#123456'};const def={name:'서식',table:true,pivot:false,elements:[{type:'wholeTable',style}]},wb=fixture();wb.setObjectStyles({tables:[def],slicers:[]});Object.assign(wb.sheets[0].tables[0],objectStylePatch('table',def));const rendered=tableCellStyle(wb.sheets[0].tables[0],1,1);for(const key of Object.keys(style))assert.deepEqual(rendered[key],style[key],key);const reread=readXlsx(writeXlsx(wb)).data;const actual=findObjectStyle(reread.objectStyles,'table','서식').elements[0].style;for(const key of ['font','size','bold','italic','underline','strike','fill','pattern','patternColor','code','dd','dds','ddc'])assert.deepEqual(actual[key],style[key],key);});
test('슬라이서 데이터 없음 위에 마우스 상태는 일반 항목 글꼴과 중간 상태를 모두 상속한다',()=>{const css=slicerCssVars({style:'사용자',styleElements:[{type:'unselectedItemWithData',style:{bold:true,font:'Arial'}},{type:'unselectedItemWithNoData',style:{italic:true}},{type:'hoveredUnselectedItemWithNoData',style:{color:'#ff0000'}}]});assert.match(css,/--sl-hover-empty-weight:700/);assert.match(css,/--sl-hover-empty-italic:italic/);assert.match(css,/--sl-hover-empty-color:#ff0000/);});

test('명시 채우기 없음은 상속된 무늬·그라데이션을 지우고 표준 DXF none으로 왕복된다',()=>{const def={name:'채우기 없음',table:true,pivot:false,elements:[{type:'wholeTable',style:{fill:'#ffff00',gradient:{deg:90,stops:[[0,'#ff0000'],[1,'#0000ff']]}}},{type:'headerRow',style:{fill:null}}]},wb=fixture();wb.setObjectStyles({tables:[def]});Object.assign(wb.sheets[0].tables[0],objectStylePatch('table',def));const st=tableCellStyle(wb.sheets[0].tables[0],0,0);assert.equal(st.fill,null);assert.equal(st.gradient,undefined);const bytes=writeXlsx(wb);assert.match(textOf(unzip(bytes)['xl/styles.xml']),/patternType="none"/);assert.equal(findObjectStyle(readXlsx(bytes).data.objectStyles,'table',def.name).elements[1].style.fill,null);const css=slicerCssVars({style:'빈채우기',styleElements:[{type:'wholeTable',style:def.elements[0].style},{type:'selectedItemWithData',style:{fill:null}}]});assert.match(css,/--sl-selected-fill:transparent/);assert.doesNotMatch(css,/--sl-selected-fill:linear-gradient/);});
test('슬라이서 무늬는 안전한 SVG 배경으로 렌더되고 잘못된 색을 CSS에 삽입하지 않는다',()=>{const css=slicerCssVars({style:'무늬',styleElements:[{type:'selectedItemWithData',style:{pattern:'darkGrid',fill:'#ffffff',patternColor:'#123456'}}]});assert.match(css,/--sl-selected-fill:url\(data:image\/svg\+xml,/);const bad=slicerCssVars({style:'색',styleElements:[{type:'wholeTable',style:{gradient:{stops:[[0,'red);display:none'],[1,'#000000']]}}}]});assert.doesNotMatch(bad,/display:none/);});

test('피벗 스타일 표시 형식은 기본 comma를 대체하지만 값 필드의 명시 형식은 보존한다',()=>{const wb=fixture(),d=wb.sheets[1].pivot;d.styleElements=[{type:'wholeTable',style:{numFmt:'custom',code:'0.000"원"'}},{type:'totalRow',style:{numFmt:'percent',decimals:1}}];let r=(()=>{const res=resolvePivot(pivotSourceData(wb,d),d);return computePivot(res,res.def)})();const numeric=r.grid.flat().find(cd=>cd?.role?.startsWith('data:'));assert.equal(numeric.style.code,'0.000"원"');assert.equal(r.grid.at(-1).at(-1).style.numFmt,'percent');d.values[0].numFmt={numFmt:'number',decimals:4};r=(()=>{const res=resolvePivot(pivotSourceData(wb,d),d);return computePivot(res,res.def)})();assert.equal(r.grid.at(-1).at(-1).style.numFmt,'number');assert.equal(r.grid.at(-1).at(-1).style.decimals,4);});
test('슬라이서 항목 DXF는 일반 표 스타일과 별도 x14 목록을 참조한다',()=>{const xml=parseXml(textOf(unzip(writeXlsx(fixture()))['xl/styles.xml'])),ext=kids(child(xml,'extLst'),'ext').find(e=>e.attrs.uri?.toUpperCase()==='{46F421CA-312F-682F-3DD2-61675219B42D}'),dxfs=kids(child(ext,'dxfs'),'dxf');assert.equal(dxfs.length,3);const selected=descendants(xml,'slicerStyleElement').find(e=>e.attrs.type==='selectedItemWithData');assert.equal(Number(selected.attrs.dxfId),0);assert.equal(child(child(dxfs[0],'fill'),'patternFill').children.find(e=>e.name==='fgColor').attrs.rgb,'FFFF0000');});

test('실제 Excel의 슬라이서 스타일 count와 확장순서·URI 철자를 따른다',()=>{const xml=textOf(unzip(writeXlsx(fixture()))['xl/styles.xml']),root=parseXml(xml),table=kids(child(root,'tableStyles'),'tableStyle').find(t=>t.attrs.name===slicer.name);assert.equal(Number(table.attrs.count),slicer.elements.length);assert.ok(xml.indexOf('{46F421CA-312F-682f-3DD2-61675219B42D}')<xml.indexOf('{EB79DEF2-80B8-43e5-95BD-54CBDDF9020C}'));});

test('Excel처럼 기본 슬라이서 스타일과 줄무늬 크기1 속성을 생략해도 같은 정의를 읽는다',()=>{const files=unzip(writeXlsx(fixture()));files['xl/slicers/slicer1.xml']=textOf(files['xl/slicers/slicer1.xml']).replace(' style="슬라이서 사용자"','');files['xl/styles.xml']=textOf(files['xl/styles.xml']).replace('type="secondRowStripe" size="1"','type="secondRowStripe"');const data=readXlsx(zip(files)).data;assert.equal(data.sheets[0].slicers[0].style,slicer.name);assert.equal(slicerColors(data.sheets[0].slicers[0]).selFill,'#ff0000');assert.equal(findObjectStyle(data.objectStyles,'table',table.name).elements.find(e=>e.type==='secondRowStripe').size,1);});

test('가져온 슬라이서 보조 정의는 중복 등록하지 않아 이름 변경·삭제 뒤 옛 이름을 다시 쓸 수 있다',()=>{const data=readXlsx(writeXlsx(fixture())).data,registry=normalizeObjectStyles(data.objectStyles);assert.equal(registry.tables.some(t=>t.name===slicer.name),false);const old=registry.slicers.find(s=>s.name===slicer.name);registry.slicers=registry.slicers.filter(s=>s.name!==slicer.name);const renamed=upsertObjectStyle(registry,'slicer',{...old,name:'새 이름'});assert.doesNotThrow(()=>upsertObjectStyle(renamed,'table',{name:slicer.name,elements:[]}));const reused=upsertObjectStyle(registry,'slicer',old);assert.equal(reused.slicers.filter(s=>s.name===slicer.name).length,1);const wb=fixture();wb.setObjectStyles({tables:[{name:'미참조 보조',table:false,pivot:false,elements:[{type:'wholeTable',style:{fill:'#112233'}}]}]});const kept=readXlsx(writeXlsx(wb)).data.objectStyles.tables.find(t=>t.name==='미참조 보조');assert.equal(kept.table,false);assert.equal(kept.pivot,false);assert.equal(kept.elements[0].style.fill,'#112233');});
