import test from 'node:test';
import assert from 'node:assert/strict';
import {primaryPointerModifier,installPointerModifierTracking} from '../src/pointer-modifiers.js';
import {GridView} from '../src/view.js';
function target(){const listeners=new Map();return{addEventListener(type,fn){const a=listeners.get(type)||[];a.push(fn);listeners.set(type,a);},removeEventListener(type,fn){listeners.set(type,(listeners.get(type)||[]).filter(x=>x!==fn));},emit(type,event={}){event.type=type;event.target??=this;for(const fn of listeners.get(type)||[])fn(event);return event;}};}
function setup(apple=true){const win=target();win.navigator=apple?{platform:'MacIntel',maxTouchPoints:5}:{platform:'Win32',maxTouchPoints:0};win.document={...target(),hidden:false};const element={ownerDocument:{defaultView:win}},stop=installPointerModifierTracking(win);return{win,element,stop,event:(patch={})=>({target:element,view:win,button:0,clientX:20,clientY:30,...patch})};}
test('직접 Ctrl/Meta는 기기 감지·설치 여부 없이 보존한다',()=>{assert.equal(primaryPointerModifier({ctrlKey:true}),true);assert.equal(primaryPointerModifier({metaKey:true}),true);assert.equal(primaryPointerModifier({altKey:true}),false);});
test('iPad modifier 없는 휠은 눌린 Control/Meta를 보완하고 keyup 후 해제한다',()=>{const s=setup();for(const[key,code]of[['Control','ControlLeft'],['Meta','MetaLeft']]){s.win.emit('keydown',{key,code});assert.equal(primaryPointerModifier(s.event()),true);s.win.emit('keyup',{key,code});assert.equal(primaryPointerModifier(s.event()),false);}s.stop();});
test('일반 데스크톱은 held 키를 추정하지 않는다',()=>{const s=setup(false);s.win.emit('keydown',{key:'Control'});assert.equal(primaryPointerModifier(s.event()),false);assert.equal(primaryPointerModifier(s.event({ctrlKey:true})),true);s.stop();});
test('요소 blur는 유지하고 window blur는 상태를 해제한다',()=>{const s=setup();s.win.emit('keydown',{key:'Control'});s.win.emit('blur',{target:s.element});assert.equal(primaryPointerModifier(s.event()),true);s.win.emit('blur');assert.equal(primaryPointerModifier(s.event()),false);s.stop();});
test('hidden/pagehide/pageshow에서 키 상태가 남지 않는다',()=>{const s=setup();for(const kind of ['hidden','pagehide','pageshow']){s.win.emit('keydown',{key:'Meta'});if(kind==='hidden'){s.win.document.hidden=true;s.win.document.emit('visibilitychange');}else s.win.emit(kind);assert.equal(primaryPointerModifier(s.event()),false);}s.stop();});
test('pointerdown→mousedown modifier는 보류 전달 뒤에도 같은 Event에만 보존한다',()=>{const s=setup();s.win.emit('pointerdown',s.event({ctrlKey:true,pointerId:1,isPrimary:true}));const down=s.win.emit('mousedown',s.event());s.win.emit('pointerup',s.event({pointerId:1}));assert.equal(primaryPointerModifier(down),true);const later=s.win.emit('mousedown',s.event());assert.equal(primaryPointerModifier(later),false);s.stop();});
test('같은 mousedown의 false 결과도 나중 키 입력에 의해 바뀌지 않는다',()=>{const s=setup();const down=s.win.emit('mousedown',s.event());s.win.emit('keydown',{key:'Control'});assert.equal(primaryPointerModifier(down),false);assert.equal(primaryPointerModifier(s.event()),true);s.stop();});
test('pointer snapshot은 다른 위치·대상·버튼·secondary pointer에 전파되지 않는다',()=>{const s=setup();for(const patch of [{clientX:40},{target:{ownerDocument:{defaultView:s.win}}},{button:2}]){s.win.emit('pointerdown',s.event({ctrlKey:true,pointerId:1}));assert.equal(primaryPointerModifier(s.win.emit('mousedown',s.event(patch))),false);}s.win.emit('pointerdown',s.event({ctrlKey:true,pointerId:2,isPrimary:false}));assert.equal(primaryPointerModifier(s.win.emit('mousedown',s.event())),false);s.stop();});
test('pointerup/cancel/mouseup/새 down/keyup/blur는 미사용 snapshot을 폐기한다',()=>{const s=setup();for(const kind of ['pointerup','pointercancel','mouseup','pointerdown','keyup','blur']){s.win.emit('pointerdown',s.event({metaKey:true,pointerId:1}));s.win.emit(kind,kind==='blur'?{}:s.event({pointerId:1,key:'Meta'}));assert.equal(primaryPointerModifier(s.win.emit('mousedown',s.event())),false,kind);}s.stop();});
test('호환 mousedown snapshot은 600ms가 지나면 만료한다',()=>{const s=setup(),now=Date.now;let time=1000;Date.now=()=>time;try{s.win.emit('pointerdown',s.event({ctrlKey:true,pointerId:1}));time+=600;assert.equal(primaryPointerModifier(s.win.emit('mousedown',s.event())),false);}finally{Date.now=now;s.stop();}});
test('중복 설치와 반복 dispose는 리스너를 안전하게 해제한다',()=>{const s=setup(),stop2=installPointerModifierTracking(s.win);s.stop();s.stop();s.win.emit('keydown',{key:'Control'});assert.equal(primaryPointerModifier(s.event()),true);stop2();s.win.emit('keydown',{key:'Control'});assert.equal(primaryPointerModifier(s.event()),false);});
function wheelHarness(list=null){const zoom=[],scroll={scrollLeft:0,scrollTop:0},grid={viewH:600,z:1,scroll,host:{onZoomWheel:d=>zoom.push(d)}};return{grid,zoom,scroll,send(patch={}){const e={target:{closest:()=>list},deltaX:0,deltaY:-120,deltaMode:0,prevented:false,preventDefault(){this.prevented=true;},...patch};GridView.prototype.onWheel.call(grid,e);return e;}};}
test('Ctrl/Command 휠은 슬라이서 스크롤보다 확대가 우선이다',()=>{for(const modifier of ['ctrlKey','metaKey']){const h=wheelHarness({scrollHeight:300,clientHeight:100,scrollTop:50});assert.equal(h.send({[modifier]:true}).prevented,true);assert.deepEqual(h.zoom,[10]);assert.equal(h.scroll.scrollTop,0);}});
test('수평 Ctrl 휠과 delta0은 배율을 변경하지 않는다',()=>{const h=wheelHarness();assert.equal(h.send({ctrlKey:true,deltaX:120,deltaY:0}).prevented,true);h.send({metaKey:true,deltaY:0});assert.deepEqual(h.zoom,[]);assert.deepEqual(h.scroll,{scrollLeft:0,scrollTop:0});});
test('일반/Shift/줄 단위 휠과 슬라이서 내부 기본 스크롤은 유지한다',()=>{const h=wheelHarness();h.send({deltaY:40});h.send({shiftKey:true,deltaY:20});assert.deepEqual(h.scroll,{scrollLeft:20,scrollTop:40});h.send({deltaMode:1,deltaY:1});assert.ok(h.scroll.scrollTop>=80);const list=wheelHarness({scrollHeight:300,clientHeight:100,scrollTop:50});assert.equal(list.send().prevented,false);assert.deepEqual(list.zoom,[]);});

test('일반 키의 명시 modifier false로 누락된 keyup 상태를 복구한다',()=>{const s=setup();s.win.emit('keydown',{key:'Control'});s.win.emit('keydown',{key:'a',ctrlKey:false,metaKey:false});assert.equal(primaryPointerModifier(s.event()),false);s.stop();});
test('오른쪽 modifier keyup도 반대쪽 키가 여전히 눌렸으면 유지한다',()=>{const s=setup();for(const[key,code,flag]of[['Control','ControlRight','ctrlKey'],['Meta','MetaRight','metaKey']]){s.win.emit('keydown',{key,[flag]:true});s.win.emit('keyup',{key,code,[flag]:true});assert.equal(primaryPointerModifier(s.event()),true);s.win.emit('keyup',{key,[flag]:false});assert.equal(primaryPointerModifier(s.event()),false);}s.stop();});
