import test from 'node:test';
import assert from 'node:assert/strict';
import { Workbook } from '../src/workbook.js';
import { readXlsx,writeXlsx } from '../src/xlsx.js';
import { unzip,zip } from '../src/zip.js';
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
function fixture(styles,sheet){const files=unzip(writeXlsx(new Workbook()));files['xl/styles.xml']=`<styleSheet xmlns="${ns}">${styles}</styleSheet>`;files['xl/worksheets/sheet1.xml']=`<worksheet xmlns="${ns}">${sheet}</worksheet>`;return new Workbook(readXlsx(zip(files)).data);}
const common=`<numFmts count="0"/><fonts count="2"><font><sz val="11"/><name val="맑은 고딕"/></font><font><sz val="10"/><name val="Arial"/><b/><i/><u/><strike/><color rgb="FF123456"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFF0000"/></patternFill></fill></fills><borders count="2"><border/><border><top style="thin"/></border></borders><cellStyleXfs count="1"><xf fontId="0" fillId="0" borderId="0" numFmtId="0"/></cellStyleXfs><cellXfs count="3"><xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0"/><xf fontId="1" fillId="2" borderId="1" numFmtId="2" xfId="0"><alignment horizontal="right" vertical="top" wrapText="1" shrinkToFit="1" textRotation="30" indent="2"/></xf><xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyNumberFormat="1" applyAlignment="1"><alignment horizontal="general" vertical="bottom" wrapText="0" shrinkToFit="0" textRotation="0"/></xf></cellXfs>`;
function verify(w){const a=w.styleAt(0,1,0),b=w.styleAt(0,1,1),c=w.styleAt(0,2,0);assert.equal(a.size,11);assert.equal(a.font,'맑은 고딕');for(const key of ['bold','italic','underline','strike','wrap','shrink','bt'])assert.equal(!!a[key],false,key);assert.equal(a.fill||'', '');assert.equal(a.rotate||0,0);assert.equal(a.indent||0,0);assert.equal(a.align,'general');assert.equal(a.numFmt||'general','general');assert.equal(b.size,10);assert.equal(b.bold,true);assert.equal(b.fill,'#ff0000');assert.equal(c.size,10);assert.equal(c.italic,true);}
test('explicit default row XF masks column font, fill, alignment and border without expanding cells',()=>{const w=fixture(common,'<cols><col min="1" max="3" style="1"/></cols><sheetData><row r="2" s="2" customFormat="true"><c r="B2" s="1"><v>5</v></c></row><row r="3"/></sheetData>');verify(w);assert.equal(w.sheets[0].cells.size,1);verify(new Workbook(readXlsx(writeXlsx(w)).data));});
test('default column components mask non-default workbook base XF',()=>{const styles=common.replace('<font><sz val="11"/>','<font><b/><sz val="11"/>').replace('<xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0"/>','<xf fontId="0" fillId="2" borderId="0" numFmtId="0" xfId="0"/>').replace('<font><sz val="10"/><name val="Arial"/><b/><i/><u/><strike/><color rgb="FF123456"/></font>','<font><sz val="11"/><name val="맑은 고딕"/></font>').replace('<xf fontId="1" fillId="2" borderId="1" numFmtId="2" xfId="0">','<xf fontId="1" fillId="0" borderId="0" numFmtId="0" xfId="0">');const w=fixture(styles,'<cols><col min="2" max="2" style="1"/></cols><sheetData/>');assert.equal(w.styleAt(0,0,0).bold,true);assert.equal(w.styleAt(0,0,0).fill,'#ff0000');assert.equal(w.styleAt(0,0,1).bold,false);assert.equal(w.styleAt(0,0,1).fill,'');});

test('wide column style ranges preserve all 16384 columns with shared style objects',()=>{const w=fixture(common,'<cols><col min="1" max="16384" style="1"/></cols><sheetData/>');const sh=w.sheets[0];assert.equal(Object.keys(sh.colStyles).length,16384);assert.equal(sh.colStyles[0],sh.colStyles[16383]);for(const c of [0,999,1000,16383]){assert.equal(w.styleAt(0,12,c).size,10);assert.equal(w.styleAt(0,12,c).bold,true);assert.equal(w.styleAt(0,12,c).fill,'#ff0000');}assert.equal(sh.cells.size,0);});
