/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=tabula/cloudflare/wrangler.jsonc --include-runtime=false tabula/cloudflare/worker-configuration.d.ts` (hash: 9587c953e437d708cf7c09c3ace93598)
interface __BaseEnv_Env {
	API_RATE: RateLimit;
	FETCH_RATE: RateLimit;
	VAULT_RATE: RateLimit;
	ASSETS: Fetcher;
	VAULTS: DurableObjectNamespace<import("./worker").UserVault>;
	PUBLISHED: DurableObjectNamespace<import("./worker").PublishedDocument>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "UserVault" | "PublishedDocument";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
